import type { Localized, TrackId } from './challenges';
import { hbm4AdvancedContext } from './hbm4-advanced-context';

export type ArchitectureNode = { id: string; label: Localized; kind: 'digital' | 'boundary' | 'analog' };
export type Architecture = { title: Localized; subtitle: Localized; nodes: ArchitectureNode[] };
export type LabContext = {
  blockId: string;
  placement: Localized;
  why: Localized[];
  review: Localized[];
  boundary: Localized;
};

const b = (zh: string, en: string): Localized => ({ zh, en });
const node = (id: string, zh: string, en: string, kind: ArchitectureNode['kind'] = 'digital'): ArchitectureNode => ({ id, label: b(zh, en), kind });

export const architectures: Record<TrackId, Architecture> = {
  dram: {
    title: b('通用 DRAM Controller 數位架構', 'Generic DRAM controller digital architecture'),
    subtitle: b('正確性過濾在前，效能政策在後；所有命令最後經由 PHY 合約送出。', 'Correctness filtering comes before performance policy; all commands leave through the PHY contract.'),
    nodes: [node('frontend', 'Host / AXI Frontend', 'Host / AXI frontend'), node('decode', 'Address Mapping', 'Address mapping'), node('queue', 'Read / Write Queues', 'Read / write queues'), node('bank', 'Per-bank State', 'Per-bank state'), node('timing', 'Timing Scoreboards', 'Timing scoreboards'), node('scheduler', 'QoS / FR-FCFS', 'QoS / FR-FCFS'), node('refresh', 'Refresh / RAS', 'Refresh / RAS'), node('adapter', 'Command Adapter', 'Command adapter', 'boundary'), node('phy', 'PHY + DRAM Array', 'PHY + DRAM array', 'analog')],
  },
  hbm: {
    title: b('HBM Stack Controller 階層架構', 'HBM stack-controller hierarchy'),
    subtitle: b('以 channel → pseudo-channel → bank-group → bank 分散狀態與仲裁，避免巨大 critical path。', 'Distribute state and arbitration by channel, pseudo-channel, bank group, and bank to avoid a giant critical path.'),
    nodes: [node('frontend', 'NoC / AXI Frontend', 'NoC / AXI frontend'), node('channel', '32-Channel Steering', '32-channel steering'), node('pc', '64 PC Queues', '64 PC queues'), node('bank', '1024-Bank State', '1024-bank state'), node('timing', 'Timing Scoreboards', 'Timing scoreboards'), node('refresh', 'REF / RFM / DRFM', 'REF / RFM / DRFM'), node('scheduler', 'Hierarchical Scheduler', 'Hierarchical scheduler'), node('adapter', 'Dual-Cmd / CA Adapter', 'Dual-cmd / CA adapter', 'boundary'), node('phy', 'PHY / Microbumps / Stack', 'PHY / microbumps / stack', 'analog')],
  },
  lpddr: {
    title: b('LPDDR Controller 與低功耗控制', 'LPDDR controller and low-power control'),
    subtitle: b('除資料路徑外，controller 還要管理 initialization、DVFS、self-refresh 與 power isolation。', 'Beyond the datapath, the controller owns initialization, DVFS, self-refresh, and power isolation.'),
    nodes: [node('frontend', 'CPU / DMA Frontend', 'CPU / DMA frontend'), node('queue', 'Request Queues', 'Request queues'), node('scheduler', 'DRAM Scheduler', 'DRAM scheduler'), node('power', 'Power / DVFS FSM', 'Power / DVFS FSM'), node('training', 'Init / Training Control', 'Init / training control'), node('dfi', 'DFI / Vendor Adapter', 'DFI / vendor adapter', 'boundary'), node('phy', 'PHY / IO / LPDDR Die', 'PHY / IO / LPDDR die', 'analog')],
  },
  gddr: {
    title: b('GDDR Controller 高速資料路徑', 'GDDR high-speed controller datapath'),
    subtitle: b('高吞吐排程之後仍要滿足 bank-group timing、bus turnaround、CRC／重送與 PHY 合約。', 'High-throughput scheduling must still satisfy bank-group timing, bus turnaround, CRC/retry, and the PHY contract.'),
    nodes: [node('frontend', 'GPU / NoC Frontend', 'GPU / NoC frontend'), node('queue', 'Traffic-class Queues', 'Traffic-class queues'), node('scheduler', 'Bank-aware Scheduler', 'Bank-aware scheduler'), node('turnaround', 'Bus Direction Guard', 'Bus-direction guard'), node('reliability', 'CRC / Retry / EDC', 'CRC / retry / EDC'), node('adapter', 'Command Encoder', 'Command encoder', 'boundary'), node('phy', 'PHY / High-speed IO', 'PHY / high-speed IO', 'analog')],
  },
  pcie: {
    title: b('PCIe Controller 分層架構', 'Layered PCIe controller architecture'),
    subtitle: b('Transaction、Data Link、LTSSM/MAC 必須分層；PIPE 以下的高速類比收發器不屬於本課 RTL。', 'Transaction, Data Link, and LTSSM/MAC responsibilities stay layered; the high-speed transceiver below PIPE is outside this RTL course.'),
    nodes: [node('frontend', 'AXI / DMA Bridge', 'AXI / DMA bridge'), node('tlp', 'TLP Packetizer / Parser', 'TLP packetizer / parser'), node('credit', 'FC Credits', 'FC credits'), node('tag', 'Tags / Completions', 'Tags / completions'), node('replay', 'DLL Sequence / Replay', 'DLL sequence / replay'), node('ltssm', 'LTSSM / MAC', 'LTSSM / MAC'), node('pipe', 'PIPE Interface', 'PIPE interface', 'boundary'), node('phy', 'SerDes / PLL / Channel', 'SerDes / PLL / channel', 'analog')],
  },
};

const ctx = (blockId: string, placement: Localized, why: Localized[], review: Localized[], boundary: Localized): LabContext => ({ blockId, placement, why, review, boundary });

export const labContext: Record<string, LabContext> = {
  ...hbm4AdvancedContext,
  'dram-address-map': ctx('decode', b('位於 ingress frontend 後、queue selection 前；mapping 直接決定平行度與 row locality。', 'After ingress and before queue selection; mapping directly controls parallelism and row locality.'), [b('錯一個 bit 就會把 transaction 送到錯誤 bank/channel。', 'One wrong bit routes a transaction to the wrong bank or channel.'), b('Mapping 是 workload locality、hotspot 與 QoS 的架構選擇，不只是切線。', 'Mapping is a locality, hotspot, and QoS decision—not merely bit slicing.')], [b('page interleaving 與 cache-line interleaving 的 row-hit/parallelism 取捨？', 'How do page and cache-line interleaving trade row hits for parallelism?'), b('Mapping 改版時如何維持資料布局相容？', 'How is data-layout compatibility preserved when mapping changes?')], b('這是數位 RTL；實體 channel/bank 組織與合法 mapping 來自產品規格。', 'This is digital RTL; physical organization and legal mappings come from the product profile.')),
  'dram-bank-fsm': ctx('bank', b('每個 bank 或 partition 一份狀態，供 legality filter 與 scheduler 查詢。', 'One state record per bank or partition, queried by legality filters and the scheduler.'), [b('ACT、RD/WR、PRE 的合法性取決於 open-row 狀態。', 'ACT, RD/WR, and PRE legality depends on open-row state.'), b('分散 bank state 才能擴展到大量 banks。', 'Distributed bank state is required to scale to many banks.')], [b('同拍 PRE 與 ACT 指向同 bank 時如何定義 priority？', 'How is priority defined for same-cycle PRE and ACT to one bank?'), b('Reset/self-refresh 後 metadata 如何收斂？', 'How does metadata converge after reset or self-refresh?')], b('PHY 回報 acceptance/training；bank FSM 不猜測類比完成時間。', 'The PHY reports acceptance/training; the FSM does not guess analog completion.')),
  'dram-trcd-guard': ctx('timing', b('在 scheduler candidate 進入 issue arbiter 前遮罩非法 RD/WR。', 'Masks illegal RD/WR candidates before issue arbitration.'), [b('tRCD 是 ACT 到 column command 的最短距離。', 'tRCD is the minimum ACT-to-column-command spacing.'), b('Timer 只能在真正 issue 時更新，不能在 candidate 階段更新。', 'Timers update only on actual issue, never merely on candidate.')], [b('Elapsed counter、deadline timestamp、shift register 的 PPA 取捨？', 'PPA tradeoffs of elapsed counters, deadline timestamps, and shift registers?'), b('DVFS 時 timing parameter 如何無 glitch 更新？', 'How are timing parameters updated glitch-free during DVFS?')], b('數值來自合法取得的 speed bin 與 PHY operating point；本站數值為縮小教學 profile。', 'Values come from the licensed speed bin and PHY operating point; site values are reduced profiles.')),
  'dram-frfcfs-select': ctx('scheduler', b('位於 legality filter 之後，只能在 timing-legal candidates 中做效能政策。', 'After legality filtering; policy selects only timing-legal candidates.'), [b('Row hit 可省 ACT/PRE，但無界優先會讓 row miss 飢餓。', 'Row hits save ACT/PRE, but unbounded priority can starve row misses.'), b('Correctness、QoS、fairness 與 efficiency 必須分層。', 'Correctness, QoS, fairness, and efficiency must remain separate.')], [b('如何證明最大等待時間有上界？', 'How do you prove a bounded maximum wait?'), b('Urgent read 與 write batching 衝突時如何仲裁？', 'How are urgent reads arbitrated against write batching?')], b('純數位政策，但參數需由 bandwidth/thermal/power model 驗證。', 'A digital policy whose parameters require bandwidth, thermal, and power validation.')),
  'dram-refresh-deadline': ctx('refresh', b('Refresh manager 與一般 scheduler 平行，deadline 到達時升級優先權。', 'The refresh manager runs beside the scheduler and escalates at deadline.'), [b('Refresh 不能看平均值，必須追蹤可延後/提前 credit 與最壞 deadline。', 'Refresh cannot use averages; postponed/pulled-in credits and worst deadlines matter.'), b('錯誤 priority 可能造成 retention failure 或 QoS 抖動。', 'Wrong priority can cause retention failure or QoS jitter.')], [b('All-bank 與 per-bank refresh 如何影響 queue drain？', 'How do all-bank and per-bank refresh affect queue draining?'), b('溫度改變 tREFI 時既有 deadline 如何安全重算？', 'How are active deadlines recomputed when temperature changes tREFI?')], b('溫度感測與 retention physics 在邊界外；controller 消費數位狀態。', 'Temperature sensing and retention physics are outside; the controller consumes digital status.')),
  'dram-write-drain': ctx('queue', b('Read/write queues 與 scheduler 之間以 hysteresis 降低資料匯流排轉向。', 'Hysteresis between read/write queues and the scheduler reduces bus turnarounds.'), [b('頻繁 R↔W 會浪費 turnaround cycles。', 'Frequent R↔W switching wastes turnaround cycles.'), b('高低水位必須搭配 starvation override。', 'High/low watermarks require a starvation override.')], [b('如何自適應 threshold 又避免震盪？', 'How can thresholds adapt without oscillation?'), b('Write drain 中 refresh 如何搶占？', 'How does refresh preempt a write drain?')], b('Queue policy 是數位；實際 turnaround 來自 DRAM/PHY operating point。', 'Queue policy is digital; actual turnaround comes from the DRAM/PHY operating point.')),
  'dram-timing-wheel': ctx('timing', b('集中在 command legality layer，以timestamp產生每類命令的下一合法時間。', 'Centralized in the command-legality layer, producing the next legal time for each command class.'), [b('集中deadline可避免數十個timer互相矛盾。', 'Central deadlines prevent dozens of timers from contradicting one another.'), b('回繞比較與真正issue更新是矽上常見corner。', 'Wraparound comparison and issue-only updates are common silicon corners.')], [b('哪一些constraint適合per-bank、per-BG或global state？', 'Which constraints belong to per-bank, per-BG, or global state?'), b('時脈切換時timestamp domain怎麼轉換？', 'How are timestamp domains converted across clock changes?')], b('RTL處理logical cycles；PHY與speed-bin表提供最終參數。', 'RTL handles logical cycles; PHY and speed-bin tables provide final parameters.')),
  'dram-command-generator': ctx('scheduler', b('位於bank metadata/timing scoreboard之後、command adapter之前，是單bank issue決策的整合點。', 'After bank metadata and timing scoreboards and before the command adapter—the integration point for one-bank issue decisions.'), [b('它把request意圖轉成PRE/ACT/RD微命令。', 'It translates request intent into PRE/ACT/RD micro-commands.'), b('policy不可繞過legality，否則效能最佳化會破壞協定。', 'Policy must never bypass legality, or performance optimization breaks the protocol.')], [b('多bank winner如何與此micro-sequencer銜接？', 'How does a multi-bank winner feed this micro-sequencer?'), b('命令被PHY back-pressure時哪份state可更新？', 'Which state may update when the PHY back-pressures the command?')], b('Command adapter以下的electrical encoding與training不在本題。', 'Electrical encoding and training below the command adapter are outside this lab.')),
  'hbm-pseudo-channel-map': ctx('channel', b('Ingress steering 將 request 分散到 channel 與 pseudo-channel 本地 queues。', 'Ingress steering distributes requests into channel- and pseudo-channel-local queues.'), [b('HBM 擴展靠階層分割，不是單一全域 arbiter。', 'HBM scales through hierarchy, not one global arbiter.'), b('Mapping 決定 channel utilization、row locality 與 NoC hotspot。', 'Mapping determines channel utilization, row locality, and NoC hotspots.')], [b('32 channels／64 pseudo-channels 如何 pipeline decode？', 'How would you pipeline decode for 32 channels and 64 pseudo-channels?'), b('Hash mapping 如何與 RAS remap 共存？', 'How does hashed mapping coexist with RAS remap?')], b('Microbump connectivity、PHY slices 與 package topology 由實體整合定義。', 'Microbump connectivity, PHY slices, and package topology are physical-integration inputs.')),
  'hbm-bankgroup-tccd': ctx('timing', b('每個 pseudo-channel 的 column scoreboard 在局部 arbiter 前檢查 same/different BG spacing。', 'A per-pseudo-channel scoreboard checks same/different-BG spacing before local arbitration.'), [b('Bank-group 關係會改變 column-command 最短距離。', 'Bank-group relationships change minimum column-command spacing.'), b('局部 timing state 可讓多 channels 平行。', 'Local timing state enables parallel channels.')], [b('同拍多 PC command 的 shared-resource constraint 放哪裡？', 'Where are shared-resource constraints for same-cycle PC commands enforced?'), b('如何壓縮 1024-bank timer state？', 'How do you compress timer state for 1024 banks?')], b('RTL 保證 logical spacing；PHY 負責 alignment、training 與 electrical timing。', 'RTL guarantees logical spacing; the PHY owns alignment, training, and electrical timing.')),
  'hbm-hierarchical-arbiter': ctx('scheduler', b('局部pseudo-channel winner進入channel/global arbiter，形成兩級可pipeline的仲裁樹。', 'Local pseudo-channel winners enter channel/global arbitration as a two-level pipelineable tree.'), [b('扁平1024-bank仲裁器無法合理收斂timing與佈線。', 'A flat 1024-bank arbiter is unlikely to close timing or routing.'), b('Round-robin state必須只在真正grant時前進。', 'Round-robin state advances only on a real grant.')], [b('pipeline插入後priority snapshot如何保持一致？', 'How is the priority snapshot preserved across pipeline stages?'), b('如何證明bounded fairness？', 'How do you prove bounded fairness?')], b('純數位仲裁；實體floorplan會回饋pipeline切點。', 'Digital arbitration; physical floorplanning feeds back into pipeline cuts.')),
  'hbm-refresh-domain': ctx('bank', b('refresh manager為每個pseudo-channel保存busy/deadline，使其他domain繼續服務。', 'The refresh manager stores busy/deadline per pseudo-channel so other domains continue service.'), [b('過度global blocking會浪費HBM最重要的平行度。', 'Overly global blocking wastes HBM’s key parallelism.'), b('局部狀態讓重疊refresh可以被明確驗證。', 'Local state makes overlapping refreshes explicitly verifiable.')], [b('shared command bus是否仍形成global exclusion？', 'Does a shared command bus still create global exclusion?'), b('per-bank refresh與RAS scrub如何仲裁？', 'How do per-bank refresh and RAS scrub arbitrate?')], b('Retention physics在DRAM die；RTL只執行規格化refresh合約。', 'Retention physics is on the DRAM die; RTL executes the specified refresh contract.')),
  'hbm-channel-capstone': ctx('scheduler', b('每個 channel 一份 dual-issue slice：兩個 PC 的 row/column legality 與獨立 policy 在此匯合，maintenance transaction 則取得 channel-wide ownership。', 'One dual-issue slice per channel combines row/column legality and independent policy for two PCs while maintenance transactions acquire channel-wide ownership.'), [b('資深設計的核心是把 correctness mask、performance selector 與 commit/backpressure 分層。', 'Senior design separates correctness masks, performance selection, and commit/backpressure.'), b('Row/column 可同拍並行，但 refresh/MRS/power 等 common operation 必須先 drain 並排他。', 'Row and column paths may run concurrently, while refresh/MRS/power common operations first drain and run exclusively.')], [b('兩個獨立 arbiter 如何在同拍共享 PHY bundle 又保持 atomic commit？', 'How do two independent arbiters share one PHY bundle while preserving atomic commit?'), b('maintenance_valid 持續為 1 時，如何證明 normal traffic 最終排空而不再接受新工作？', 'How do you prove normal traffic eventually drains while maintenance_valid remains asserted?'), b('32 個 channel 複製後，哪些 state local、哪些 resource 真正 global？', 'After replication across 32 channels, which state remains local and which resources are truly global?')], b('Capstone 停在同步 command-bundle interface；pin encoding、training、CK/DQ timing 與 microbump physical behavior由 PHY/實體整合。', 'The capstone ends at the synchronous command-bundle interface; PHY/physical integration owns pin encoding, training, CK/DQ timing, and microbump behavior.')),
  'lpddr-power-sequence': ctx('power', b('Power manager 橫跨 scheduler、clock/reset、isolation、DFI 與 firmware CSR。', 'The power manager spans scheduler, clock/reset, isolation, DFI, and firmware CSRs.'), [b('低功耗進出是跨模組 protocol，順序錯會造成資料遺失或 X propagation。', 'Low-power entry/exit is a cross-block protocol; wrong ordering risks data loss or X propagation.'), b('必須先 quiesce/drain，再 isolation 與 power-off。', 'Traffic must quiesce and drain before isolation and power-off.')], [b('Sleep request 與新 request 同拍時誰負責 back-pressure？', 'Who applies back-pressure when sleep and a new request coincide?'), b('Power-good stuck-low 的 timeout/recovery？', 'What is the timeout/recovery path for power-good stuck low?')], b('Retention/isolation cells、power switch 與 rail ramp 由 UPF/實體設計實現。', 'Retention/isolation cells, power switches, and rail ramps are implemented by UPF/physical design.')),
  'lpddr-init-sequencer': ctx('training', b('Reset/CSR之後、正常scheduler enable之前，驅動DFI/vendor training合約。', 'After reset/CSR and before normal scheduler enable, driving the DFI/vendor training contract.'), [b('初始化是可觀察、可timeout的協定，不應藏在firmware delay裡。', 'Initialization is an observable, timeout-capable protocol, not hidden firmware delay.'), b('ready只能在所有mode與training步驟完成後成立。', 'Ready asserts only after every mode and training step completes.')], [b('warm reset可跳過哪些步驟？', 'Which steps may warm reset skip?'), b('training failure如何記錄、重試與降速？', 'How are training failures logged, retried, and downshifted?')], b('Delay-line校準、eye training與IO類比在PHY；RTL只握手。', 'Delay-line calibration, eye training, and analog IO live in the PHY; RTL handshakes.')),
  'lpddr-dvfs-quiesce': ctx('power', b('Power/DVFS manager以back-pressure關閉frontend並等待scheduler/outstanding排空。', 'The power/DVFS manager closes the frontend with back-pressure and waits for scheduler/outstanding drain.'), [b('頻率切換時仍有transaction會造成資料或timing state錯亂。', 'Transactions in flight during a frequency change corrupt data or timing state.'), b('quiesce、PHY ack與參數commit必須是原子序列。', 'Quiesce, PHY acknowledgment, and parameter commit must be an atomic sequence.')], [b('timeout後是rollback還是fatal reset？', 'On timeout, is recovery rollback or fatal reset?'), b('多clock domain如何同步quiescent proof？', 'How is quiescence proven across clock domains?')], b('PLL lock與rail settling是類比狀態，透過同步status回報。', 'PLL lock and rail settling are analog states returned as synchronized status.')),
  'lpddr-controller-capstone': ctx('scheduler', b('Frontend admission與command issue的頂層合約，匯合init、power、DVFS、queue、timing與PHY狀態。', 'Top-level contract for frontend admission and command issue, combining init, power, DVFS, queue, timing, and PHY state.'), [b('req_ready與cmd_issue代表不同資源階段，不能混用。', 'req_ready and cmd_issue represent different resource stages and cannot be conflated.'), b('所有maintenance模式都必須有一致的traffic gate。', 'Every maintenance mode needs a coherent traffic gate.')], [b('已接受但未issue的request在sleep前如何處置？', 'What happens to accepted but unissued requests before sleep?'), b('哪些狀態需要retention？', 'Which states require retention?')], b('本題停在DFI/PHY合約；類比初始化由外部status封裝。', 'This lab ends at the DFI/PHY contract; analog initialization is abstracted as status.')),
  'gddr-turnaround-guard': ctx('turnaround', b('Column scheduler 與 PHY datapath adapter 之間追蹤最後方向與下一合法時間。', 'Between the column scheduler and PHY adapter, tracking direction and next legal time.'), [b('共享 DQ 改變方向需要 dead cycles，避免 controller 與 DRAM 同時驅動。', 'Shared DQ needs dead cycles on direction changes to prevent simultaneous drive.'), b('R→W 與 W→R 不對稱，不能只有一個 busy bit。', 'R→W and W→R are asymmetric; one busy bit is insufficient.')], [b('Burst length 改變時 deadline 以 command 還是 data edge 計算？', 'When burst length changes, is the deadline based on command or data edges?'), b('Multi-rank 是否共享 turnaround state？', 'Is turnaround state shared across ranks?')], b('DQ gating、termination、sampling eye 與 training 屬 PHY/IO。', 'DQ gating, termination, sampling eye, and training belong to PHY/IO.')),
  'gddr-command-parity': ctx('reliability', b('Command encoder送往PHY前產生parity，RX/monitor path在解碼前驗證。', 'The command encoder generates parity before the PHY; the RX/monitor path verifies it before decode.'), [b('CA錯誤可能把合法資料命令變成破壞性命令。', 'A CA error can turn a legal data command into a destructive command.'), b('valid gating可避免idle X被誤報。', 'Valid gating prevents idle X states from becoming false errors.')], [b('錯誤後是retry、reset還是poison？', 'Does an error trigger retry, reset, or poison?'), b('parity coverage與multi-bit fault限制？', 'What are parity coverage and multi-bit-fault limits?')], b('IO上的實際parity sampling與margin屬PHY；RTL處理邏輯碼字。', 'Physical parity sampling and margin belong to the PHY; RTL handles the logical codeword.')),
  'gddr-retry-queue': ctx('reliability', b('Data CRC產生器旁保留尚未ACK的payload ownership，NACK從此重送。', 'Beside the data CRC generator, retaining payload ownership until ACK and replaying on NACK.'), [b('沒有ownership規則，上游可能覆寫待重送資料。', 'Without ownership, upstream may overwrite data awaiting replay.'), b('ACK/NACK與新資料同拍需要明確priority。', 'Same-cycle ACK/NACK and new data need explicit priority.')], [b('多entry replay window如何處理sequence wrap？', 'How does a multi-entry replay window handle sequence wrap?'), b('永久錯誤的retry上限與降級策略？', 'What retry limit and degradation policy handle permanent faults?')], b('CRC bit error來源在channel/IO；數位邏輯接收ACK/NACK結果。', 'CRC errors originate in channel/IO; digital logic consumes ACK/NACK status.')),
  'gddr-controller-capstone': ctx('scheduler', b('Scheduler與PHY adapter間的最後commit gate，整合timing、turnaround與reliability ownership。', 'The final commit gate between scheduler and PHY adapter, combining timing, turnaround, and reliability ownership.'), [b('Retry不是新transaction，必須優先保持原始順序。', 'A retry is not a new transaction and must preserve original ordering.'), b('issue gate是所有局部guard的原子交集。', 'The issue gate is the atomic intersection of all local guards.')], [b('retry長時間阻塞如何避免全系統死鎖？', 'How is system deadlock avoided during prolonged retry?'), b('資料與命令pipeline不同深度時如何對齊commit？', 'How is commit aligned across unequal command/data pipelines?')], b('最終DQ launch、CRC sampling與equalization留在PHY。', 'Final DQ launch, CRC sampling, and equalization remain in the PHY.')),
  'pcie-credit-manager': ctx('credit', b('Transaction Layer TX arbitration 前追蹤各 traffic class 的 header/data credits。', 'Tracks per-traffic-class header/data credits before Transaction-Layer TX arbitration.'), [b('Credit 是 lossless flow control；任一類 underflow 都是 protocol failure。', 'Credits provide lossless flow control; underflow is a protocol failure.'), b('更新與消耗同拍要明確定義飽和、順序與 assertion。', 'Same-cycle update/consume needs explicit saturation, ordering, and assertions.')], [b('為何六類 FC credit 不能合併？', 'Why can the six FC credit types not be merged?'), b('Advertisement latency 如何影響 sizing？', 'How does advertisement latency affect sizing?')], b('Credit manager 是數位 Transaction Layer；PHY 只傳 encoded blocks。', 'Credit management is digital Transaction Layer logic; the PHY carries encoded blocks.')),
  'pcie-tag-tracker': ctx('tag', b('Requester 送出 non-posted TLP 前配置 tag，completion parser 回收。', 'The requester allocates before a non-posted TLP; the completion parser frees it.'), [b('Tag 是 out-of-order completion 與 recovery 的 transaction identity。', 'Tags identify transactions for out-of-order completion and recovery.'), b('重複配置或過早回收會把資料交給錯誤 request。', 'Duplicate allocation or early reuse can deliver data to the wrong request.')], [b('Extended tags 與 function 隔離如何擴展 allocator？', 'How does the allocator scale for extended tags and function isolation?'), b('FLR/hot reset 時 outstanding tags 如何 abort？', 'How are outstanding tags aborted on FLR or hot reset?')], b('純數位 bookkeeping，不依賴 SerDes 類比行為。', 'Purely digital bookkeeping, independent of SerDes analog behavior.')),
  'pcie-replay-timer': ctx('replay', b('Data Link Layer 在 TX sequence/replay buffer 旁追蹤 ACK/NAK 與 timeout。', 'The Data Link Layer tracks ACK/NAK and timeout beside the TX replay buffer.'), [b('Replay 重送相同 sequence，不是建立新 transaction。', 'Replay resends the same sequence; it does not create a new transaction.'), b('ACK priority、restart 與 wrap-around 必須逐拍定義。', 'ACK priority, restart, and wraparound must be cycle-accurate.')], [b('多筆 outstanding packet 如何管理 replay window？', 'How is the replay window managed for multiple outstanding packets?'), b('Link retrain 時 replay buffer 保留或 flush？', 'Is the replay buffer retained or flushed during link retraining?')], b('Equalization 與 bit-error mechanism 在 PHY/channel；DLL 只接收 error status。', 'Equalization and bit-error mechanisms are in PHY/channel; DLL receives status.')),
  'controller-tag-completion': ctx('tag', b('跨 requester、completion parser 與 DMA response 的 end-to-end invariant checker。', 'An end-to-end invariant checker across requester, completion parser, and DMA response.'), [b('局部 protocol pass 不代表 transaction exactly once。', 'Local protocol success does not prove exactly-once completion.'), b('Sticky error 與 outstanding bitmap 讓罕見 race 可觀察。', 'Sticky errors and outstanding bitmaps make rare races observable.')], [b('同拍 accept/complete 同 tag 的語意？', 'Semantics of same-cycle accept/complete for one tag?'), b('如何轉成 bindable SVA 與 coverage？', 'How does this become bindable SVA and coverage?')], b('實體 link error 經 protocol status 注入此數位 checker。', 'Physical-link errors enter this digital checker through protocol status.')),
  'pcie-tlp-router': ctx('tlp', b('位於AXI/DMA bridge與各Transaction Layer engine之間，依header類別分流。', 'Between the AXI/DMA bridge and Transaction Layer engines, routing by header class.'), [b('posted、non-posted、completion有不同credit與completion責任。', 'Posted, non-posted, and completion traffic have different credit and completion obligations.'), b('malformed必須在造成side effect前被隔離。', 'Malformed packets must be isolated before causing side effects.')], [b('不同function/VF的routing與權限在哪一層？', 'Where are routing and permissions enforced for functions/VFs?'), b('ECRC與malformed的error precedence？', 'What is the precedence between ECRC and malformed errors?')], b('Packet decode是數位；8b/10b或128b/130b等線路編碼在PHY/MAC邊界。', 'Packet decode is digital; line coding belongs at the PHY/MAC boundary.')),
  'pcie-replay-buffer': ctx('replay', b('Data Link TX在送往MAC前保存所有尚未ACK的packet與sequence。', 'Data Link TX retains every unacknowledged packet and sequence before the MAC.'), [b('Replay需要原封不動重送，不能重新配置tag或credit。', 'Replay resends unchanged packets without reallocating tags or credits.'), b('ACK只允許移動合法window head。', 'ACK may advance only a legal window head.')], [b('累计ACK與NAK如何移動window？', 'How do cumulative ACK and NAK move the window?'), b('buffer容量如何由round-trip latency決定？', 'How is capacity derived from round-trip latency?')], b('SerDes錯誤透過DLL status觸發replay；buffer本身為數位RAM。', 'SerDes errors trigger replay through DLL status; the buffer itself is digital RAM.')),
  'pcie-completion-reorder': ctx('tag', b('Completion parser後、AXI/DMA response前，以tag接收、以request order retire。', 'After the completion parser and before AXI/DMA response, receiving by tag and retiring by request order.'), [b('PCIe允許completion亂序，而某些上游介面要求有序。', 'PCIe permits completion reordering while some upstream interfaces require order.'), b('資料、done與tag ownership必須一起移動。', 'Data, done state, and tag ownership must move together.')], [b('split completion如何追蹤byte count？', 'How are byte counts tracked for split completions?'), b('completion timeout與late completion如何處置？', 'How are completion timeout and late completion handled?')], b('純Transaction Layer storage；不依賴PHY類比實作。', 'Pure Transaction Layer storage, independent of analog PHY implementation.')),
  'pcie-ltssm-recovery': ctx('ltssm', b('MAC/PIPE上方管理link生命週期，link_up直接gate Transaction/Data Link traffic。', 'Above MAC/PIPE, managing link lifecycle; link_up directly gates Transaction/Data Link traffic.'), [b('鏈路錯誤時繼續送TLP會破壞protocol state。', 'Continuing TLP traffic during link error corrupts protocol state.'), b('狀態輸出應從單一state decode避免旗標漂移。', 'Outputs should decode from one state to avoid flag drift.')], [b('Recovery時credit/tag/replay各自保留或清除？', 'Which credit/tag/replay states persist through Recovery?'), b('timeout與速度降級如何加入？', 'How are timeout and speed downgrade added?')], b('Equalization、CDR、PLL在SerDes；LTSSM以PIPE status控制。', 'Equalization, CDR, and PLL are in the SerDes; LTSSM controls through PIPE status.')),
  'pcie-controller-capstone': ctx('frontend', b('Requester入口的atomic admission gate，橫跨link、flow control、tag與replay資源。', 'The requester’s atomic admission gate spanning link, flow control, tag, and replay resources.'), [b('只檢查部分資源會造成接受後無法完成的transaction。', 'Checking only some resources accepts transactions that cannot complete.'), b('allocate與consume必須綁定同一accept事件。', 'Allocation and consumption must bind to the same accept event.')], [b('多traffic class下如何避免head-of-line blocking？', 'How is head-of-line blocking avoided across traffic classes?'), b('如何寫assertion證明資源不underflow且exactly once？', 'Which assertions prove no resource underflow and exactly-once behavior?')], b('Controller停在PIPE/PHY數位邊界；SerDes signoff另屬類比與實體流程。', 'The controller stops at the PIPE/PHY digital boundary; SerDes signoff is a separate analog/physical flow.')),
};

export const boundaryLegend = {
  digital: b('本課實作的數位 RTL', 'Digital RTL implemented here'),
  boundary: b('數位／PHY 合約邊界', 'Digital/PHY contract boundary'),
  analog: b('說明但不實作：PHY、PLL、IO、封裝／通道', 'Explained, not implemented: PHY, PLL, IO, package/channel'),
};
