import type { Localized } from './challenges';
import type { LabSpec } from './lab-specs';

const b = (zh: string, en: string): Localized => ({ zh, en });
const e = (cycle: string, zhDrive: string, enDrive: string, zhExpect: string, enExpect: string) => ({ cycle, drive: b(zhDrive, enDrive), expect: b(zhExpect, enExpect) });
const sync = b('所有狀態在 clk 上升緣更新；rst_n 為同步低有效 reset。candidate 只是查詢，只有 issue/accepted 事件可以提交狀態。', 'All state updates on the rising edge of clk; rst_n is synchronous active-low reset. A candidate is only a query; only issue/accepted events commit state.');
const comb = b('純組合模組；輸出由本拍輸入唯一決定，不含隱藏狀態或 clock。', 'Purely combinational; outputs are determined only by current inputs, with no hidden state or clock.');
const reset = {
  clk: b('Controller clock；只在上升緣提交狀態。', 'Controller clock; state commits only on rising edges.'),
  rst_n: b('同步低有效 reset；清除 ownership、history、counter 與 sticky 狀態。', 'Synchronous active-low reset; clears ownership, history, counters, and sticky state.'),
};
const make = (purpose: Localized, clocking: Localized, ports: Record<string, Localized>, algorithm: Localized[], example: ReturnType<typeof e>[], priority: Localized[] = [], assumptions: Localized[] = []): LabSpec => ({ purpose, clocking, ports, algorithm, example, priority, assumptions });

export const hbm4AdvancedSpecs: Record<string, LabSpec> = {
  'hbm-dual-command-gate': make(
    b('實作每個 HBM4 channel 的最後一層 command acceptance gate。它區分可與 column command 並行的一般 row command，以及必須讓兩個 pseudo-channel 一起 quiesce 的 channel-common row command。', 'Implement the final command-acceptance gate for one HBM4 channel. It distinguishes ordinary row commands that may run beside a column command from channel-common row commands that require both pseudo-channels to quiesce.'),
    comb,
    { row_valid: b('本拍 row-command candidate 有效。', 'A row-command candidate is valid this cycle.'), row_global: b('1 表示 MRS/PDE/SRE 類 channel-common 命令；0 表示一般 bank/PC row 命令。', 'One marks an MRS/PDE/SRE-like channel-common command; zero marks an ordinary bank/PC row command.'), col_valid: b('本拍 column-command candidate 有效。', 'A column-command candidate is valid this cycle.'), pc_idle: b('bit i=1 表示 pseudo-channel i 沒有 outstanding/queued command。', 'Bit i is one when pseudo-channel i has no outstanding or queued command.'), phy_ready: b('PHY adapter 本拍可接受命令 bundle。', 'The PHY adapter can accept a command bundle this cycle.'), row_fire: b('row candidate 本拍真正提交；下游與 metadata 只能看此訊號更新。', 'The row candidate truly commits this cycle; downstream state updates only from this signal.'), col_fire: b('column candidate 本拍真正提交。', 'The column candidate truly commits this cycle.'), blocked: b('至少一個 valid candidate 未能 fire；供 stall/coverage 使用。', 'At least one valid candidate failed to fire; used for stall accounting and coverage.') },
    [b('一般 row：row_fire=row_valid&&phy_ready；column 可同時 fire。', 'Ordinary row: row_fire=row_valid&&phy_ready, and column may fire concurrently.'), b('Channel-common row：必須 pc_idle==11、col_valid==0、phy_ready==1；同拍不得有 column fire。', 'Channel-common row requires pc_idle==11, no column candidate, and phy_ready; no column may fire that cycle.'), b('blocked 不是 error；它表示 scheduler 必須保留 candidate 並稍後重試。', 'blocked is not an error; the scheduler retains and retries the candidate.')],
    [e('C0', '一般 row_valid=1、col_valid=1、phy_ready=1', 'ordinary row_valid=1, col_valid=1, phy_ready=1', 'row_fire=1、col_fire=1', 'row_fire=1 and col_fire=1'), e('C1', 'row_global=1、col_valid=1', 'row_global=1 and col_valid=1', '兩者都不 fire、blocked=1', 'neither fires and blocked=1'), e('C2', 'row_global=1、col_valid=0、pc_idle=11', 'row_global=1, col_valid=0, pc_idle=11', 'row_fire=phy_ready', 'row_fire follows phy_ready')],
    [b('PHY readiness > common-command exclusion > ordinary dual issue。', 'PHY readiness > common-command exclusion > ordinary dual issue.')],
    [b('這裡使用抽象 row_global；實際 opcode decode 必須追溯 JESD270-4A command truth tables。', 'row_global is abstract here; real opcode decode must trace to the JESD270-4A command truth tables.')],
  ),
  'hbm-bank-state-table': make(
    b('建立一個 pseudo-channel 內四個 bank 的 architectural state table。組合部分提供合法性與 row-locality 分類，sequential 部分只在合法 command commit 時更新。', 'Build architectural state for four banks in one pseudo-channel. Combinational logic reports legality and row locality; sequential logic updates only on a legal command commit.'),
    sync,
    { ...reset, cmd_valid: b('本拍有命令要求；為 0 時 cmd/bank/row 不得改變狀態。', 'A command is requested; when low, cmd/bank/row cannot change state.'), cmd: b('0=ACT、1=RD、2=WR、3=PRE。', '0=ACT, 1=RD, 2=WR, 3=PRE.'), bank: b('目標 bank 0–3。', 'Target bank 0–3.'), row: b('ACT 要開啟或 RD/WR 要命中的 8-bit 教學 row。', 'Eight-bit teaching row to open with ACT or hit with RD/WR.'), cmd_ok: b('目前 state 是否允許這個 command；與 cmd_valid 同拍組合產生。', 'Whether current state allows the command; combinational with cmd_valid.'), row_hit: b('目標 bank open 且 open row 等於 row。', 'Target bank is open and its open row equals row.'), row_conflict: b('目標 bank open 但 open row 不等於 row。', 'Target bank is open but its open row differs from row.'), row_open: b('四個 bank 的 open bitmap；bit i 對應 bank i。', 'Four-bank open bitmap; bit i corresponds to bank i.') },
    [b('先依 bank 選出 opened row，再組合計算 row_hit/row_conflict。', 'Select the bank’s open row, then compute row_hit and row_conflict combinationally.'), b('Closed 只允許 ACT；open+hit 允許 RD/WR；open 允許 PRE。', 'Closed allows only ACT; open+hit allows RD/WR; open allows PRE.'), b('合法 ACT 設 open bit 並寫 row；合法 PRE 清 open bit；RD/WR 不改 metadata。', 'Legal ACT sets the open bit and row; legal PRE clears the bit; RD/WR leave metadata unchanged.')],
    [e('C0', 'reset 後 bank0 RD row10', 'bank0 RD row10 after reset', 'cmd_ok=0、row_open=0000', 'cmd_ok=0 and row_open=0000'), e('C1', 'bank0 ACT row10', 'bank0 ACT row10', 'edge 後 row_open=0001；查 row10 得 row_hit=1', 'after edge row_open=0001; querying row10 gives row_hit=1'), e('C2', 'bank0 RD row11', 'bank0 RD row11', 'row_conflict=1、cmd_ok=0，metadata 不變', 'row_conflict=1 and cmd_ok=0; metadata unchanged')],
    [b('Reset > 合法 command commit；非法命令沒有副作用。', 'Reset > legal command commit; illegal commands have no side effect.')],
    [b('縮小為四 banks；full stack 應分片或以 metadata RAM 實作，語意相同。', 'Reduced to four banks; a full stack should shard or RAM-back the metadata while preserving semantics.')],
  ),
  'hbm-row-timing-scoreboard': make(
    b('用三個飽和倒數器產生單 bank 的 ACT、column、PRE legality mask。這一層只回答「現在可不可以」，不決定哪個 request 優先。', 'Use three saturating countdowns to create ACT, column, and PRE legality masks for one bank. This layer answers only whether a command is legal now; it does not choose policy.'),
    sync,
    { ...reset, act_issue: b('ACT 已被 PHY 接受；同時啟動 tRCD 與 tRAS。', 'An ACT was accepted by the PHY; starts tRCD and tRAS.'), pre_issue: b('PRE 已被接受；啟動 tRP。', 'A PRE was accepted; starts tRP.'), act_ok: b('tRP 已到期且本拍沒有 PRE trigger。', 'tRP has expired and no PRE triggers this cycle.'), col_ok: b('tRCD 已到期且本拍沒有 ACT trigger。', 'tRCD has expired and no ACT triggers this cycle.'), pre_ok: b('tRAS 已到期且本拍沒有 ACT trigger。', 'tRAS has expired and no ACT triggers this cycle.') },
    [b('act_issue：rcd←TRCD、ras←TRAS；否則非零 counter 每拍減一。', 'act_issue loads rcd=TRCD and ras=TRAS; otherwise nonzero counters decrement.'), b('pre_issue：rp←TRP；否則非零 counter 每拍減一。', 'pre_issue loads rp=TRP; otherwise a nonzero counter decrements.'), b('allowed output 必須排除 trigger 當拍，即使舊 counter 原本為 0。', 'Each allowed output excludes its trigger cycle even if the old counter was zero.')],
    [e('A0', 'act_issue=1、TRCD=3、TRAS=5', 'act_issue=1 with TRCD=3 and TRAS=5', 'col_ok=0、pre_ok=0', 'col_ok=0 and pre_ok=0'), e('A3', '三個後續 edge 完成', 'three later edges complete', 'col_ok=1、pre_ok 仍為 0', 'col_ok=1 while pre_ok remains 0'), e('P0–P3', 'pre_issue 後等待三拍', 'wait three cycles after pre_issue', 'act_ok 從 0 精確轉為 1', 'act_ok changes from 0 to 1 exactly')],
    [b('Reset > reload > decrement；同一 counter 一拍只能有一個決策。', 'Reset > reload > decrement; each counter has one decision per cycle.')],
    [b('題目數值是縮短 profile；產品 counter 由 speed bin、controller clock ratio 與 JEDEC rounding rule 產生。', 'Values are shortened profiles; product counters derive from the speed bin, controller clock ratio, and JEDEC rounding rules.')],
  ),
  'hbm-activate-window': make(
    b('在 pseudo-channel timing layer 合併 tRRD_S/L 與 rolling tFAW。候選 ACT 必須同時通過 bank-group spacing 與 power/current window，任何一條失敗都不能 issue。', 'Combine tRRD_S/L and rolling tFAW at the pseudo-channel timing layer. A candidate ACT must pass both bank-group spacing and activation-window limits before issue.'),
    sync,
    { ...reset, issue: b('本拍 ACT 真正發出；只在此事件記錄 history。', 'An ACT truly issued this cycle; history records only this event.'), issue_bg: b('已發 ACT 的 bank group。', 'Bank group of the issued ACT.'), candidate_bg: b('目前被 legality layer 查詢的 ACT bank group。', 'Bank group of the ACT candidate being queried.'), allowed: b('候選同時滿足 tRRD_S/L 與 tFAW。', 'The candidate satisfies both tRRD_S/L and tFAW.') },
    [b('last ACT age：issue 時設 1，idle 時飽和加一；same BG 需 age>=4，different BG 需 age>=2。', 'Set last-ACT age to one on issue and saturating-increment while idle; same BG needs age>=4, different BG age>=2.'), b('hist[7:0] 每拍 shift，LSB 寫入 issue；used 為八位 popcount。', 'Shift hist[7:0] every cycle and insert issue at the LSB; used is its eight-bit popcount.'), b('allowed=spacing_ok && used<4；blocked candidate 因 issue=0，只會讓 window 自然老化。', 'allowed=spacing_ok && used<4; a blocked candidate has issue=0 and only ages the window naturally.')],
    [e('C0', '發 ACT 到 BG0', 'issue ACT to BG0', '下一拍 same BG 與 different BG 都暫時 blocked', 'both same and different BG are initially blocked'), e('C2', 'candidate BG1', 'candidate BG1', 'different-BG spacing 到期，allowed=1', 'different-BG spacing expires, allowed=1'), e('window full', '最近八拍已有四個 ACT', 'four ACTs exist in the last eight cycles', '不論 BG，allowed=0', 'allowed=0 regardless of BG')],
    [b('Reset > history shift；issue 同時更新 spacing history 與 tFAW history。', 'Reset > history shift; issue updates spacing and tFAW history together.')],
    [b('本 lab 只建模每 pseudo-channel 個別計時；channel-shared command-bus collision 由 dual-command gate 處理。', 'This lab models per-pseudo-channel timing only; the dual-command gate handles shared-bus collisions.')],
  ),
  'hbm-rw-turnaround': make(
    b('建立 data-bus direction legality block。它把 W→R 的 same/different-bank-group 時序與 R→W turnaround 分開，並與 tCCD block 正交組合。', 'Build the data-bus direction legality block. It distinguishes same/different-bank-group W→R timing from R→W turnaround and composes orthogonally with tCCD.'),
    sync,
    { ...reset, issue: b('column command 已 issue；更新 direction history。', 'A column command issued and updates direction history.'), issue_write: b('被 issue 的方向：1=WR、0=RD。', 'Direction issued: 1=WR, 0=RD.'), issue_bg: b('被 issue 命令的 bank group。', 'Bank group of the issued command.'), candidate_write: b('候選方向：1=WR、0=RD。', 'Candidate direction: 1=WR, 0=RD.'), candidate_bg: b('候選 bank group；只在 W→R 選 S/L 時使用。', 'Candidate bank group; used to choose S/L only for W→R.'), allowed: b('此方向 guard 是否允許候選；仍需與 tCCD 等 mask 相 AND。', 'Whether this direction guard allows the candidate; it still ANDs with tCCD and other masks.') },
    [b('沒有 history 或同方向時 allowed=1；同方向 spacing 交給 tCCD。', 'With no history or the same direction, allowed=1; tCCD handles same-direction spacing.'), b('last WR、candidate RD：同 BG 需要 age>=5，不同 BG 需要 age>=3。', 'For last WR and candidate RD, same BG needs age>=5 and different BG age>=3.'), b('last RD、candidate WR：需要 age>=4，與 BG 無關。', 'For last RD and candidate WR, age>=4 independent of BG.')],
    [e('W0', 'issue WR 到 BG1', 'issue WR to BG1', '下一拍候選 RD/BG2 blocked', 'next-cycle RD/BG2 is blocked'), e('W3', 'age=3、候選 RD/BG2', 'age=3, candidate RD/BG2', 'allowed=1', 'allowed=1'), e('W3-L', '同 age 改候選 BG1', 'same age but candidate BG1', '仍 blocked，到 age=5 才放行', 'still blocked until age=5')],
    [b('Reset > issue history update > idle age increment。', 'Reset > issue-history update > idle age increment.')],
    [b('實際值由 selected speed bin 與 latency/MR configuration 決定。', 'Actual values depend on the selected speed bin and latency/MR configuration.')],
  ),
  'hbm-refresh-credit': make(
    b('用一個有上限的 debt 表示 refresh 排程義務。這讓一般 traffic scheduler 能清楚區分「可以延後」與「已接近最壞上限必須搶占」。', 'Represent refresh scheduling obligations with bounded debt so the traffic scheduler can distinguish deferrable refresh from a near-bound urgent preemption.'),
    sync,
    { ...reset, interval_tick: b('一個抽象 tREFI interval 到期；增加一筆義務。', 'One abstract tREFI interval elapsed, adding one obligation.'), refresh_issued: b('一筆合格 refresh 已被命令端接受；消耗一筆 debt。', 'A qualifying refresh was accepted at the command port, consuming one debt.'), debt: b('0–8 飽和 refresh 義務數；不是 DRAM 內部 refresh counter。', 'Saturating 0–8 refresh-obligation count; not the DRAM’s internal refresh counter.'), urgent: b('debt>=7；要求 policy layer 暫停一般流量優先權。', 'debt>=7; tells policy to stop prioritizing normal traffic.') },
    [b('10：debt<8 時 +1；01：debt>0 時 -1。', '10 increments below eight; 01 decrements above zero.'), b('11：本 interval 的到期與一筆 refresh 互相抵銷，debt 保持。', '11 means one due interval and one refresh cancel, so debt holds.'), b('counter 在 0/8 飽和，不得 underflow/overflow。', 'The counter saturates at zero and eight without underflow or overflow.')],
    [e('D0–D7', '連續七個 interval_tick', 'seven interval ticks', 'debt=7、urgent=1', 'debt=7 and urgent=1'), e('same', 'interval_tick=1、refresh_issued=1', 'interval_tick=1 and refresh_issued=1', 'debt 保持', 'debt holds'), e('pull-in', '只有 refresh_issued=1', 'refresh_issued only', 'debt 減一；在 0 時維持 0', 'debt decrements; it holds at zero')],
    [b('Reset > 兩事件的四路 case；同拍語意明確且唯一。', 'Reset > four-way event case with unique simultaneous semantics.')],
    [b('完整 JEDEC postpone/pull-in 規則需加入 operation type、temperature 與 per-bank 序列；本題先隔離 accounting kernel。', 'Full JEDEC postpone/pull-in behavior adds operation type, temperature, and per-bank sequencing; this lab isolates the accounting kernel.')],
  ),
  'hbm-rfm-counter': make(
    b('實作 controller 建議的 per-bank RAA accounting kernel。它記錄 ACT 活動並依 RFMpb/RFMab 降低相應 bank counters，向 maintenance arbiter 輸出 need_rfm bitmap。', 'Implement a controller-side per-bank RAA accounting kernel. It records ACT activity, decrements counters on RFMpb/RFMab, and presents a need_rfm bitmap to the maintenance arbiter.'),
    sync,
    { ...reset, act: b('ACT 已 issue；增加 act_bank 的 RAA。', 'An ACT issued and increments the RAA of act_bank.'), act_bank: b('ACT 目標 bank 0–3。', 'ACT target bank 0–3.'), rfmpb: b('RFMpb 已 issue；降低 rfm_bank。', 'RFMpb issued and decrements rfm_bank.'), rfm_bank: b('RFMpb 目標 bank。', 'RFMpb target bank.'), rfmab: b('RFMab 已 issue；降低全部四個 bank。', 'RFMab issued and decrements all four banks.'), need_rfm: b('bit i=1 表示 bank i counter 已達教學 threshold 4。', 'Bit i is one when bank i reaches the teaching threshold of four.') },
    [b('ACT：選定 counter +1，最大飽和於 7。', 'ACT increments the selected counter, saturating at seven.'), b('RFMpb：選定 counter 減 3，若原值<=3 則降為 0。', 'RFMpb subtracts three from the selected counter, flooring at zero.'), b('RFMab：對全部 counter 套用相同 decrement；need_rfm 為四個並行比較器。', 'RFMab applies the decrement to every counter; need_rfm is four parallel comparators.')],
    [e('A0–A3', 'bank2 連續四個合法 ACT', 'four legal ACTs to bank2', 'need_rfm=0100', 'need_rfm=0100'), e('R0', 'RFMpb bank2', 'RFMpb bank2', 'counter 4→1，need_rfm[2]=0', 'counter 4→1 and need_rfm[2]=0'), e('global', 'bank0/1 都達 threshold 後 RFMab', 'RFMab after banks 0 and 1 reach threshold', '兩者同步降低', 'both decrement together')],
    [b('Reset > RFMab > RFMpb > ACT；maintenance command 優先，避免同拍加減歧義。', 'Reset > RFMab > RFMpb > ACT; maintenance wins to avoid ambiguous add/subtract semantics.')],
    [b('RAAIMT/RAAMMT/RAADEC 與 adaptive levels 是 device-discovered product parameters；4/3/7 僅為可跑測試的縮小值。', 'RAAIMT/RAAMMT/RAADEC and adaptive levels are device-discovered product parameters; 4/3/7 are reduced executable values.')],
  ),
  'hbm-drfm-sequencer': make(
    b('保存一筆 host-directed refresh transaction 的 ownership。controller 以帶 DRFM sample 的 ACT 取得 row，完成正常 access/close 後，才對同 bank 送出 DRFMpb。', 'Own one host-directed refresh transaction. The controller captures a row with a DRFM-sampled ACT, completes normal access/closure, then issues DRFMpb to the same bank.'),
    sync,
    { ...reset, act_capture: b('一筆帶 sample 意圖的 ACT 已 issue；嘗試取得 DRFM slot。', 'A sampled ACT issued and attempts to acquire the DRFM slot.'), act_bank: b('要保存的 bank。', 'Bank to retain.'), act_row: b('要保存的 row。', 'Row to retain.'), bank_closed: b('captured bank 的 open-row metadata 已關閉。', 'The captured bank is closed according to metadata.'), drfm_issued: b('對 captured bank 的 DRFMpb 已被接受。', 'DRFMpb for the captured bank was accepted.'), pending: b('slot ownership；為 1 時 captured bank/row 不得覆寫。', 'Slot ownership; captured bank/row cannot change while high.'), request_pre: b('pending 且 bank 尚未關閉，請 command generator 安排 PRE。', 'Pending while bank remains open; asks the command generator for PRE.'), request_drfm: b('pending 且 bank 已關閉，請 maintenance arbiter 安排 DRFMpb。', 'Pending with bank closed; asks maintenance arbitration for DRFMpb.'), captured_bank: b('第一筆成功 capture 的 bank。', 'Bank of the first successful capture.'), captured_row: b('第一筆成功 capture 的 row。', 'Row of the first successful capture.'), sample_error: b('Sticky：pending 期間又收到 capture，表示 ownership protocol 遭破壞。', 'Sticky: another capture arrived while pending, violating ownership.') },
    [b('!pending && act_capture：pending←1 並 snapshot bank/row。', 'When idle and act_capture, set pending and snapshot bank/row.'), b('pending && act_capture：只設 sample_error，不覆寫 snapshot。', 'When pending and act_capture, set sample_error without overwriting the snapshot.'), b('pending && bank_closed && drfm_issued：清 pending；下一筆 capture 才能進入。', 'When pending, closed, and drfm_issued, clear pending so another capture may enter.')],
    [e('S0', 'capture bank2,row55，bank_closed=0', 'capture bank2,row55 with bank_closed=0', 'pending=1、request_pre=1', 'pending=1 and request_pre=1'), e('S1', '再 capture bank1,rowAA', 'capture bank1,rowAA again', 'sample_error=1；snapshot 仍是 2/55', 'sample_error=1; snapshot remains 2/55'), e('S2', 'bank_closed=1', 'bank_closed=1', 'request_drfm=1，直到 drfm_issued edge', 'request_drfm=1 until drfm_issued edge')],
    [b('Reset > capture ownership/error > successful completion；同拍完成只針對既有 pending。', 'Reset > capture ownership/error > successful completion; same-cycle completion applies only to existing ownership.')],
    [b('DRAM 內部鄰近列選擇不可見；RTL 只管理 JESD270-4A 定義的 address-capture/DRFM command contract。', 'Internal neighboring-row selection is invisible; RTL manages only the address-capture/DRFM command contract defined by JESD270-4A.')],
  ),
  'hbm-mrs-quiesce': make(
    b('實作 shared mode-register update transaction。從 firmware request 開始關閉 admission，等待兩個 pseudo-channel 都 idle，產生 MRS pulse，並在 tMOD 窗完成後回報 done。', 'Implement a shared mode-register update transaction. Close admission after a firmware request, wait for both pseudo-channels to idle, pulse MRS, and report done only after the tMOD window.'),
    sync,
    { ...reset, mrs_req: b('Firmware/CSR 提出一次 mode-register update。', 'Firmware/CSR requests one mode-register update.'), pc_idle: b('兩個 PC 的 quiescent proof；必須同時為 11。', 'Quiescence proof for both PCs; both must be one.'), accept_enable: b('1 才能接受新 host request；DRAIN/ISSUE/WAIT 都為 0。', 'New host requests may enter only when high; low in DRAIN/ISSUE/WAIT.'), mrs_issue: b('一拍 commit pulse，交給 command adapter。', 'One-cycle commit pulse to the command adapter.'), done: b('一拍 completion pulse，表示可恢復 host traffic。', 'One-cycle completion pulse indicating host traffic may resume.') },
    [b('RUN 收到 mrs_req 後下一狀態 DRAIN，立即停止新的 accept。', 'A request in RUN moves to DRAIN and closes further admission.'), b('DRAIN 只有 pc_idle==11 才進 ISSUE；ISSUE 只 pulse MRS 一拍並載入 count=3。', 'DRAIN advances only when pc_idle==11; ISSUE pulses MRS once and loads count=3.'), b('WAIT 精確倒數三拍；到期同拍回 RUN 並 pulse done。', 'WAIT counts exactly three cycles, then returns to RUN and pulses done.')],
    [e('Q0', 'mrs_req=1', 'mrs_req=1', '下一拍 accept_enable=0', 'accept_enable=0 next cycle'), e('Qn', 'pc_idle 從 01 變 11', 'pc_idle changes from 01 to 11', '進 ISSUE；下一拍 mrs_issue=1', 'enter ISSUE; mrs_issue=1 next cycle'), e('Qn+4', 'tMOD teaching count 到期', 'teaching tMOD count expires', 'done=1、accept_enable=1', 'done=1 and accept_enable=1')],
    [b('Reset > state transition；mrs_issue/done 每拍先清零。', 'Reset > state transition; clear mrs_issue/done by default every cycle.')],
    [b('實際 MR contents、合法變更條件與 tMOD 取自產品 profile；本 lab 聚焦 quiesce/commit ownership。', 'Actual MR contents, legal update conditions, and tMOD come from the product profile; this lab focuses on quiesce/commit ownership.')],
  ),
  'hbm-ca-parity': make(
    b('在 command adapter 建立 controller 端 CA parity 與錯誤紀錄。Parity 保護的是送到 DRAM 的 command/address bundle；AERR 表示 DRAM 偵測到 parity 問題，命令本身仍可能執行，因此必須留下可診斷狀態。', 'Add controller-side CA parity and error recording at the command adapter. Parity protects the command/address bundle sent to DRAM; AERR reports a detected parity problem, and the command may still execute, so diagnostic state must persist.'),
    sync,
    { ...reset, cmd_valid: b('本拍 ca bundle 有效；無效時 apar 固定 0。', 'The ca bundle is valid this cycle; apar is zero when invalid.'), ca: b('縮小的 19-bit row/column/address teaching bundle。', 'Reduced 19-bit row/column/address teaching bundle.'), aerr_sample: b('已同步到 controller clock 的 AERR event。', 'An AERR event synchronized to the controller clock.'), apar: b('偶同位元；valid 時 ^{ca,apar}=0。', 'Even parity; when valid, ^{ca,apar}=0.'), sticky_error: b('任一 AERR 後保持 1，直到 reset。', 'Remains one after any AERR until reset.') },
    [b('cmd_valid=1：apar=^ca；cmd_valid=0：apar=0。', 'When cmd_valid=1, apar=^ca; otherwise apar=0.'), b('aerr_sample 在上升緣設 sticky_error=1；沒有 software clear 路徑。', 'aerr_sample sets sticky_error on the rising edge; there is no software clear path.'), b('Parity error 不在此 block 重播或取消命令；系統 recovery policy 由上層 RAS 控制。', 'This block neither replays nor cancels a command on parity error; system RAS owns recovery policy.')],
    [e('P0', 'cmd_valid=1、ca=12345', 'cmd_valid=1, ca=12345', '^{ca,apar}=0', '^{ca,apar}=0'), e('P1', 'cmd_valid=0', 'cmd_valid=0', 'apar=0', 'apar=0'), e('E0', 'aerr_sample=1 一拍', 'aerr_sample=1 for one cycle', 'edge 後 sticky_error=1 並保持', 'sticky_error=1 after the edge and remains high')],
    [b('Reset 清除錯誤；其餘時間只有 set，沒有隱含 clear。', 'Reset clears the error; otherwise it is set-only with no implicit clear.')],
    [b('實際 parity 集合與 edge 行為必須依 JESD270-4A clause 6.4 與 PHY pin mapping；19-bit bundle 是公開教學抽象。', 'The actual parity set and edge behavior must follow JESD270-4A clause 6.4 and PHY pin mapping; the 19-bit bundle is a public teaching abstraction.')],
  ),
  'hbm-power-state': make(
    b('管理兩個 pseudo-channel 共用的 power-down ownership。新 traffic 必須先被 backpressure，既有 traffic 排空後才能送 PDE；PDX 後仍需等待 exit window 才恢復 admission。', 'Manage power-down ownership shared by both pseudo-channels. Backpressure new traffic, drain existing work before PDE, and wait through an exit window after PDX before reopening admission.'),
    sync,
    { ...reset, sleep_req: b('Power manager 要求進入 power-down。', 'Power manager requests power-down entry.'), wake_req: b('Power manager 要求離開 power-down。', 'Power manager requests exit.'), pc_idle: b('兩個 pseudo-channel 的 queue/outstanding idle proof。', 'Queue/outstanding-idle proof for both pseudo-channels.'), phy_ready: b('PHY 可接受 PDE/PDX command。', 'PHY can accept PDE/PDX.'), accept_enable: b('只有 RUN 為 1；其他狀態 backpressure host。', 'High only in RUN; all other states backpressure the host.'), pde: b('一拍 power-down-entry commit pulse。', 'One-cycle power-down-entry commit pulse.'), pdx: b('一拍 power-down-exit commit pulse。', 'One-cycle power-down-exit commit pulse.'), sleeping: b('state=SLEEP 的直接 decode。', 'Direct decode of state=SLEEP.') },
    [b('RUN 收到 sleep_req 進 DRAIN；DRAIN 等 pc_idle=11 && phy_ready。', 'RUN enters DRAIN on sleep_req; DRAIN waits for pc_idle=11 and phy_ready.'), b('條件成立時 pulse PDE 並進 SLEEP；SLEEP 只接受 wake_req&&phy_ready。', 'When ready, pulse PDE and enter SLEEP; SLEEP accepts only wake_req&&phy_ready.'), b('接受 wake 時 pulse PDX、載入 exit count=2；兩拍後回 RUN。', 'On wake, pulse PDX, load exit count=2, and return to RUN after two cycles.')],
    [e('L0', 'sleep_req=1、pc_idle=00', 'sleep_req=1, pc_idle=00', '進 DRAIN、accept_enable=0、PDE=0', 'enter DRAIN, accept_enable=0, PDE=0'), e('L1', 'pc_idle=11、phy_ready=1', 'pc_idle=11, phy_ready=1', 'edge 後 PDE pulse、sleeping=1', 'PDE pulses and sleeping=1 after edge'), e('W0–W2', 'wake_req 後等待兩拍', 'wait two cycles after wake_req', 'PDX 只 pulse 一拍，之後 accept_enable=1', 'PDX pulses once, then accept_enable=1')],
    [b('Reset > state；每拍先清 PDE/PDX，狀態只允許其中一個 command。', 'Reset > state; clear PDE/PDX each cycle, and the state allows only one of them.')],
    [b('Rail gating、clock analog behavior 與 physical power cells 不在本 RTL；此處只產生 HBM command-level protocol。', 'Rail gating, analog clock behavior, and physical power cells are outside this RTL; this block emits only the HBM command-level protocol.')],
  ),
  'hbm-stack-dispatch': make(
    b('建立 full-stack 的第一級 pipeline。它不做 DRAM timing，而是把 request 穩定地送到 32 個 channel/64 個 pseudo-channel 的其中一個 local queue，並在 backpressure 下保持原子性。', 'Build the first full-stack pipeline stage. It does not enforce DRAM timing; it reliably routes a request to one of 32 channels and 64 pseudo-channels while preserving atomicity under backpressure.'),
    sync,
    { ...reset, req_valid: b('本拍 host request 與 addr 有效。', 'Host request and addr are valid this cycle.'), addr: b('21-bit 教學位址；channel=addr[10:6]、PC=addr[5]，其餘成為 local address。', '21-bit teaching address; channel=addr[10:6], PC=addr[5], and remaining bits form the local address.'), channel_ready: b('32 個 channel ingress queue 的 ready bitmap。', 'Ready bitmap for 32 channel ingress queues.'), req_ready: b('目前 addr 選到的 channel_ready bit。', 'The channel_ready bit selected by current addr.'), out_valid: b('上一拍 accept 的 registered valid；一拍 latency。', 'Registered valid for the prior cycle’s acceptance; one-cycle latency.'), out_channel: b('被接受 request 的 5-bit channel snapshot。', 'Five-bit channel snapshot of the accepted request.'), out_pc: b('被接受 request 的 pseudo-channel snapshot。', 'Pseudo-channel snapshot of the accepted request.'), out_local_addr: b('去除 channel/PC 欄位後的 15-bit local address snapshot。', 'Fifteen-bit local-address snapshot after removing channel/PC fields.') },
    [b('組合 ch=addr[10:6]、req_ready=channel_ready[ch]、accept=req_valid&&req_ready。', 'Combinationally derive ch=addr[10:6], req_ready=channel_ready[ch], and accept=req_valid&&req_ready.'), b('每個 edge 都令 out_valid←accept；只有 accept=1 才更新三個 payload registers。', 'Every edge sets out_valid=accept; update the three payload registers only on accept.'), b('accept=0 時 payload 可保持舊值，但 out_valid 必須為 0，避免 ghost transaction。', 'When accept=0, payload may hold but out_valid must be zero to prevent a ghost transaction.')],
    [e('S0', 'addr 選 channel31、ready[31]=0、req_valid=1', 'addr selects channel31, ready[31]=0, req_valid=1', 'req_ready=0；下一拍 out_valid=0', 'req_ready=0; out_valid=0 next cycle'), e('S1', 'ready[31] 變 1，addr/valid 保持', 'ready[31] becomes one while addr/valid hold', 'accept；下一拍 out_valid=1、channel=31、PC/address 為 snapshot', 'accept; next cycle out_valid=1 with channel31 and captured PC/address'), e('S2', 'req_valid=0 並改 addr', 'req_valid=0 and addr changes', '下一拍 out_valid=0；舊 payload 不構成 transaction', 'out_valid=0 next cycle; held payload is not a transaction')],
    [b('Reset > out_valid update；payload update 受 accept gate。', 'Reset > out_valid update; payload updates only on accept.')],
    [b('實際 mapping/hash/RAS remap 由 SoC address-map contract 決定；這裡驗證 32-channel pipeline 與 ownership。', 'The SoC address-map contract defines actual mapping, hashing, and RAS remap; this lab verifies the 32-channel pipeline and ownership.')],
  ),
};

export type LabReference = { source: Localized; topics: Localized; profile: Localized };

const ref = (clause: string, topicsZh: string, topicsEn: string): LabReference => ({
  source: b(`JEDEC JESD270-4A，${clause}`, `JEDEC JESD270-4A, ${clause}`),
  topics: b(topicsZh, topicsEn),
  profile: b('網站使用縮小、獨立撰寫的可執行參數；產品實作請回查合法取得的標準與 vendor speed-bin。', 'The site uses reduced, independently written executable parameters; product implementations must use the licensed standard and vendor speed bin.'),
});

export const hbm4AdvancedReferences: Record<string, LabReference> = {
  'hbm-dual-command-gate': ref('§3.1.2、§3.1.3、§6.3', 'Pseudo-channel 共用資源、row/column 雙命令介面、command truth tables', 'Pseudo-channel shared resources, dual row/column interfaces, command truth tables'),
  'hbm-bank-state-table': ref('§3.3、§6.3.2–6.3.3', 'Bank state、ACT/PRE/RD/WR 合法轉移', 'Bank state and legal ACT/PRE/RD/WR transitions'),
  'hbm-row-timing-scoreboard': ref('§6.3.2、§10', 'tRCD、tRAS、tRP 與 row timing rounding', 'tRCD, tRAS, tRP, and row-timing rounding'),
  'hbm-activate-window': ref('§3.2.1、§6.3.2.2、§10', 'Bank-group tRRD_S/L 與 tFAW', 'Bank-group tRRD_S/L and tFAW'),
  'hbm-rw-turnaround': ref('§3.1.2、§3.2.1、§6.3.3、§10', 'Per-PC column timing、tWTR_S/L、tRTW', 'Per-PC column timing, tWTR_S/L, and tRTW'),
  'hbm-refresh-credit': ref('§6.3.2.5.1–6.3.2.5.2', 'REFab/REFpb interval、postpone/pull-in 與 scheduling', 'REFab/REFpb intervals, postpone/pull-in, and scheduling'),
  'hbm-rfm-counter': ref('§6.3.2.5.3–6.3.2.5.4', 'RFM、RAA accounting 與 adaptive levels', 'RFM, RAA accounting, and adaptive levels'),
  'hbm-drfm-sequencer': ref('§6.3.2.5.5', 'DRFM address capture、bank close 與 DRFMpb', 'DRFM address capture, bank closure, and DRFMpb'),
  'hbm-mrs-quiesce': ref('§5、§6.3.2.7', 'Shared mode registers、MRS 與 tMOD', 'Shared mode registers, MRS, and tMOD'),
  'hbm-ca-parity': ref('§6.4', 'Command/address parity 與 AERR', 'Command/address parity and AERR'),
  'hbm-power-state': ref('§3.1.2、§6.3.2.8–6.3.2.9', 'Pseudo-channel common power-down/self-refresh control', 'Pseudo-channel-common power-down/self-refresh control'),
  'hbm-stack-dispatch': ref('§3.1–3.2', 'Channel/pseudo-channel organization 與 addressing', 'Channel/pseudo-channel organization and addressing'),
};
