import type { Localized } from './challenges';
import type { LabContext } from './architectures';

const b = (zh: string, en: string): Localized => ({ zh, en });
const ctx = (
  blockId: string,
  placementZh: string,
  placementEn: string,
  whyZh: [string, string],
  whyEn: [string, string],
  reviewZh: [string, string, string],
  reviewEn: [string, string, string],
  boundaryZh: string,
  boundaryEn: string,
): LabContext => ({
  blockId,
  placement: b(placementZh, placementEn),
  why: [b(whyZh[0], whyEn[0]), b(whyZh[1], whyEn[1])],
  review: [b(reviewZh[0], reviewEn[0]), b(reviewZh[1], reviewEn[1]), b(reviewZh[2], reviewEn[2])],
  boundary: b(boundaryZh, boundaryEn),
});

export const hbm4SystemContext: Record<string, LabContext> = {
  'hbm-pin-ownership': ctx('adapter', '位於 controller command/data paths 與 PHY adapter 的最外層，統一決定 CA、DQ 與 test path 的 ownership。', 'At the outer controller-to-PHY adapter, defining ownership of CA, DQ, and test paths.', ['Pin ownership 不清楚會造成雙方同時驅動或資料被錯誤取樣。', 'Test mode 必須能隔離 functional path，不能只靠軟體約定。'], ['Ambiguous pin ownership causes contention or unintended sampling.', 'Test mode must isolate functional paths in hardware, not by software convention.'], ['哪些 pins 由 controller 產生、哪些由 PHY 產生？', '讀寫 turnaround 由誰保證？', 'test mode 與 functional request 同拍時誰優先？'], ['Which pins originate in the controller and which in the PHY?', 'Who guarantees read/write turnaround?', 'What wins when test mode coincides with functional traffic?'], '本題只定義數位 enable；tri-state cell、voltage、slew 與 bump electrical signoff 屬 PHY/IO。', 'This lab defines digital enables only; tri-state cells, voltage, slew, and bump electrical signoff belong to PHY/IO.'),
  'hbm-command-pin-adapter': ctx('adapter', '位於 dual-command commit 之後、PHY pin encoder 之前，將 accepted bundle 轉成 row/column payload 與 parity。', 'After dual-command commit and before PHY pin encoding, converting accepted bundles into row/column payloads plus parity.', ['HBM4 的 row 與 column 路徑可並行，不能再壓回單一 opcode bus。', 'APAR 必須覆蓋實際送出的 payload，而不是未被接受的 candidate。'], ['HBM4 row and column paths can run together and must not collapse into one opcode bus.', 'APAR covers the payload actually sent, not an unaccepted candidate.'], ['row/column 同拍時 parity 覆蓋哪些 bits？', 'PHY backpressure 時 payload 如何保持？', 'AERR 回來後 controller 如何記錄與恢復？'], ['Which bits are covered when row and column issue together?', 'How is payload held under PHY backpressure?', 'How does the controller log and recover from AERR?'], '命令 truth table 與 CK edge placement 由合法規格／PHY 合約決定；本題只練 accepted bundle 的數位映射。', 'Normative command tables and CK-edge placement come from the licensed standard/PHY contract; this lab models only digital bundle mapping.'),
  'hbm-write-phy-shim': ctx('phyif', '位於 write data queue 與 PHY serializer/launch path 之間，保存 payload ownership 到 launch window 完成。', 'Between the write-data queue and PHY serialization/launch path, retaining payload ownership through the launch window.', ['Command 被接受不代表 data 已經離開 PHY；payload 必須保存到完整 burst 完成。', 'busy 期間覆寫資料會造成 transaction 與 DQ 對不上。'], ['Command acceptance does not mean data has left the PHY; payload ownership lasts through the burst.', 'Overwriting while busy associates the wrong data with the transaction.'], ['WL/BL 改變時 launch window 如何參數化？', 'DBI、ECC metadata 在哪一級對齊？', 'reset 若發生在 burst 中間如何處理？'], ['How is the launch window parameterized for WL/BL?', 'Where are DBI and ECC metadata aligned?', 'What happens if reset occurs mid-burst?'], 'Serializer、WDQS phase、output delay 與 eye margin 在 PHY；RTL 只握手並維持資料 ownership。', 'Serialization, WDQS phase, output delay, and eye margin live in the PHY; RTL maintains handshake and data ownership.'),
  'hbm-read-phy-capture': ctx('phyif', '位於 PHY read-capture output 與 controller return path 之間，把已對齊 beat 轉成同步 valid/data。', 'Between PHY read capture and the controller return path, converting aligned beats into synchronous valid/data.', ['Controller 不應直接以 core clock 猜 RDQS edge；必須由 PHY 回報已完成取樣的 beat。', 'valid/data alignment 是所有 scoreboard 與 ECC path 的基礎。'], ['The controller must not guess RDQS edges with its core clock; the PHY returns aligned beats.', 'Valid/data alignment is foundational for scoreboards and ECC.' ], ['連續 beats 與 bubble 如何表達？', 'read tag 在哪裡與 beat 對齊？', 'training 未完成時 read data 如何 gate？'], ['How are back-to-back beats and bubbles represented?', 'Where is the read tag aligned with each beat?', 'How is read data gated before training completes?'], 'RDQS sampling、deserialization 與 deskew 在 PHY；本題從抽象 sample event 之後開始。', 'RDQS sampling, deserialization, and deskew live in the PHY; this lab starts after an abstract sample event.'),
  'hbm-training-sweep': ctx('training', '位於 initialization manager 與 PHY calibration status 之間，控制 sweep、收集結果並選擇可用 tap。', 'Between initialization control and PHY calibration status, managing sweeps, result collection, and tap selection.', ['Training 是可 timeout、可記錄、可重試的流程，不是固定 firmware delay。', 'Controller 需要知道成功、失敗與選定值，但不應實作類比 delay line。'], ['Training is a timeout-capable, observable, retryable protocol, not a fixed firmware delay.', 'The controller owns success/failure/selection status, not the analog delay line.'], ['first-pass 與 center-of-eye 選擇的差別？', '失敗後是降速、重試還是隔離 lane？', 'warm reset 能否沿用 calibration？'], ['How do first-pass and center-of-eye selection differ?', 'Does failure trigger downshift, retry, or lane isolation?', 'May warm reset reuse calibration?'], 'Pass/fail measurement、eye scan 與 delay cell 屬 PHY；本題只做 digital training sequencer。', 'Pass/fail measurement, eye scan, and delay cells belong to the PHY; this lab implements the digital sequencer.'),
  'hbm-dbi-codec': ctx('reliability', '位於 write/read data path 的 PHY 邊界，以 byte lane 為範圍產生或消除 DBI。', 'At the data-path PHY boundary, generating or removing DBI per byte lane.', ['DBI 降低 bus 同時切換活動，但 metadata 必須和對應 byte 完全對齊。', '跨 byte 共用一個決策會破壞 round-trip correctness。'], ['DBI reduces simultaneous switching, but metadata must align with each byte.', 'Sharing one decision across bytes breaks round-trip correctness.'], ['為何門檻是每 byte 決定？', 'DBI metadata 經過 repair remap 時如何一起搬移？', 'DBI 對功耗與 eye 的改善如何量測？'], ['Why is the decision per byte?', 'How does DBI metadata follow lane repair?', 'How is DBI benefit measured for power and eye margin?'], 'DBI 的 digital codec 可由 RTL 描述；實際 switching noise 與 channel margin 必須由 SI/PI/PHY 分析。', 'The DBI codec is digital RTL; switching noise and channel margin require SI/PI/PHY analysis.'),
  'hbm-data-parity-ras': ctx('reliability', '位於 controller/PHY data boundary 與 RAS telemetry path，保護外部資料傳輸。', 'At the controller/PHY data boundary and RAS telemetry path, protecting external data transfer.', ['DPAR/DERR 保護的是外部 data bus，不能與 on-die ECC 畫成同一層。', '單拍 error 若不 sticky 化，firmware 可能來不及觀察。'], ['DPAR/DERR protects the external data bus and is separate from on-die ECC.', 'A one-cycle error needs sticky telemetry for firmware visibility.'], ['Parity 能偵測哪些錯誤、漏掉哪些錯誤？', 'DERR 後 transaction 是 retry、poison 還是 fatal？', '錯誤 counter 如何避免 overflow？'], ['Which faults can parity detect or miss?', 'Does DERR cause retry, poison, or fatal handling?', 'How is error-counter overflow handled?'], '實體 DPAR sampling 在 PHY；controller 接收同步化的 error event 並決定系統政策。', 'Physical DPAR sampling occurs in the PHY; the controller consumes a synchronized event and chooses system policy.'),
  'hbm-ecc-severity': ctx('reliability', '位於 ECC decoder status 與 firmware/interrupt telemetry 之間，統一 error severity。', 'Between ECC decoder status and firmware/interrupt telemetry, normalizing error severity.', ['Correctable 與 uncorrectable error 需要不同的 scrub、degrade 與 fatal 政策。', '外部 ECC metadata 與 DRAM on-die ECC 必須分開說明 coverage。'], ['Correctable and uncorrectable errors need different scrub, degrade, and fatal policies.', 'External ECC metadata and DRAM on-die ECC have distinct coverage.'], ['CEs/CEm 的產品定義由哪個 profile 決定？', 'UE 如何 poison outstanding transaction？', 'scrub 與正常 traffic 如何仲裁？'], ['Which product profile defines CEs/CEm?', 'How does UE poison an outstanding transaction?', 'How does scrub arbitrate with normal traffic?'], '本題從抽象 decoder result 開始；ECC code construction、DRAM internal correction 與 failure physics 不在此簡化模型。', 'This lab starts from an abstract decoder result; code construction, on-die correction, and failure physics are outside the model.'),
  'hbm-lane-repair-map': ctx('repair', '位於 logical lane bundle 與 PHY physical lanes 之間，套用 soft/hard repair mapping。', 'Between the logical lane bundle and physical PHY lanes, applying soft or hard repair mapping.', ['Repair 不只搬資料，也必須讓 strobe、DBI、parity/ECC metadata 使用一致 mapping。', 'Mapping table 是開機／manufacturing state，更新必須原子化。'], ['Repair must move data plus matching strobe/DBI/parity/ECC metadata.', 'The mapping table is boot/manufacturing state and updates atomically.'], ['soft repair 與 hard repair 的生命週期差別？', '無 spare 時如何 degrade 或 isolate？', 'CK/AERR 為何不能當一般 AWORD remap？'], ['How do soft and hard repair lifetimes differ?', 'How does the system degrade or isolate without a spare?', 'Why can CK/AERR not be remapped like ordinary AWORD lanes?'], 'Fuse、bump 與實體 redundant lane 位於 PHY/package；controller 只消費有效 repair map。', 'Fuses, bumps, and physical redundant lanes live in PHY/package; the controller consumes a valid repair map.'),
  'hbm-ieee1500-wrapper': ctx('repair', '位於 stack test access path，透過 capture/shift/update 讀狀態並套用測試控制。', 'In the stack test-access path, using capture/shift/update to observe status and apply test control.', ['Shadow 與 active state 必須隔離，shift 過程不能擾動 functional control。', '明確優先序才能避免 capture/update 同拍造成不可重現狀態。'], ['Shadow and active state must be isolated so shifting does not disturb functional control.', 'Explicit priority avoids non-reproducible capture/update overlap.'], ['WRCK/WRST_n 與 core clock 的 CDC/RDC 怎麼處理？', '哪些 repair register 允許 update？', 'production test 與 field service 的權限如何分離？'], ['How are WRCK/WRST_n crossings handled?', 'Which repair registers allow update?', 'How are production-test and field-service permissions separated?'], 'IEEE 1500 wrapper 是數位測試介面；ATE pattern、fuse programming 與 package continuity 測試屬 DFT/製造流程。', 'The IEEE 1500 wrapper is digital test access; ATE patterns, fuse programming, and package continuity belong to DFT/manufacturing.'),
  'hbm-package-budget': ctx('package', '位於 PHY/physical integration contract，把 package/interposer 回報的 delay/skew budget 轉成可追蹤的 pass/fail。', 'At the PHY/physical-integration contract, converting reported package/interposer delay and skew into traceable pass/fail budget.', ['Controller/PHY 介面若沒有 budget ownership，timing loss 會在不同團隊之間重複或漏算。', '飽和 arithmetic 可避免違規案例因 unsigned underflow 看似有巨大 margin。'], ['Without budget ownership, timing loss is double-counted or omitted across teams.', 'Saturating arithmetic prevents violations from appearing as huge unsigned margin.'], ['flight time、skew、jitter、setup 分別由誰簽核？', 'PVT corner 如何傳入 budget？', '哪些結果只能由 EM/SI tool 產生？'], ['Who signs off flight time, skew, jitter, and setup?', 'How are PVT corners represented?', 'Which results require EM/SI tools?'], '這只是一個 budget calculator；microbump、interposer、return path、crosstalk 與 power integrity 必須使用實際 package model sign-off。', 'This is only a budget calculator; microbumps, interposer, return path, crosstalk, and power integrity require real package models.'),
  'hbm-thermal-throttle': ctx('performance', '位於 telemetry 與 scheduler policy 之間，把 thermal/power 狀態轉成可執行的 issue budget。', 'Between telemetry and scheduler policy, turning thermal/power status into an executable issue budget.', ['HBM 效能不能只看 peak bandwidth；溫度與電流限制會改變可持續吞吐量。', 'Refresh 仍屬 correctness traffic，不能被一般 ACT throttle 一起關掉。'], ['HBM performance is not just peak bandwidth; thermal/current limits change sustainable throughput.', 'Refresh is correctness traffic and must not be blocked with normal ACT throttling.'], ['threshold 的 hysteresis 如何避免震盪？', 'thermal sensor fail 時採何種 fail-safe？', 'throttle 對 QoS tail latency 的影響？'], ['How does hysteresis prevent oscillation?', 'What is the fail-safe for sensor failure?', 'How does throttling affect QoS tail latency?'], '溫度感測、熱模型與封裝散熱在 RTL 之外；controller 消費同步化等級並執行 policy。', 'Temperature sensing, thermal models, and package cooling are outside RTL; the controller consumes synchronized levels and applies policy.'),
  'hbm-bandwidth-window': ctx('performance', '位於 controller performance monitor，從真正 beat_fire 與 observation cycles 建立實測 throughput。', 'In the controller performance monitor, measuring throughput from true beat_fire events and observation cycles.', ['Peak throughput 是 bus width×rate；實際值還受到 utilization、turnaround、refresh 與 throttle 影響。', '只數 issued commands 可能與真正 data beats 不同。'], ['Peak throughput is bus width times rate; actual throughput also reflects utilization, turnaround, refresh, and throttling.', 'Counting commands may differ from counting actual data beats.'], ['window 太短或太長各有何偏差？', '如何分解 row miss、refresh、turnaround stall？', '多 channel counter 如何避免高扇出？'], ['What biases come from short or long windows?', 'How are row-miss, refresh, and turnaround stalls separated?', 'How do per-channel counters avoid high fanout?'], '本題提供 digital counters；frequency、bus width、package derating 與 workload mapping 必須一起換算成 GB/s。', 'This lab provides digital counters; frequency, bus width, package derating, and workload mapping are needed to derive GB/s.'),
  'hbm-pim-qos-arbiter': ctx('performance', '位於 shared HBM command/data resources 前，協調 host、PIM 與 maintenance traffic。', 'Before shared HBM command/data resources, coordinating host, PIM, and maintenance traffic.', ['PIM 提升資料區域性但仍會競爭 bank、command bus、refresh 與 thermal budget。', 'maintenance 必須保 correctness，host/PIM 則需要 bounded fairness。'], ['PIM improves locality but still competes for banks, command bandwidth, refresh, and thermal budget.', 'Maintenance preserves correctness while host/PIM need bounded fairness.'], ['PIM command 如何加入既有 legality scoreboard？', '如何證明 host/PIM 都不會 starvation？', '效能模型要回報哪些 stall reasons？'], ['How do PIM commands enter existing legality scoreboards?', 'How is starvation freedom proven for host and PIM?', 'Which stall reasons should the performance model expose?'], '本題只做 shared-resource policy；PIM datapath、DRAM internal timing 與模型 accuracy 需由獨立架構／實作驗證。', 'This lab models shared-resource policy only; PIM datapaths, internal DRAM timing, and model accuracy need separate validation.'),
};
