import type { Localized } from './challenges';
import type { LabReference } from './hbm4-advanced-specs';
import type { LabSpec } from './lab-specs';

const b = (zh: string, en: string): Localized => ({ zh, en });
const e = (cycle: string, zhDrive: string, enDrive: string, zhExpect: string, enExpect: string) => ({ cycle, drive: b(zhDrive, enDrive), expect: b(zhExpect, enExpect) });
const comb = b('純組合邏輯；輸出由本拍輸入決定，不含隱藏狀態。', 'Purely combinational; outputs depend only on current inputs with no hidden state.');
const sync = b('所有狀態在 clk 上升緣更新；rst_n 為同步低有效 reset。', 'All state updates on the rising edge of clk; rst_n is synchronous active-low reset.');
const reset = { clk: b('Controller／training clock；只在上升緣提交狀態。', 'Controller/training clock; state commits on rising edges.'), rst_n: b('同步低有效 reset；清除 ownership、counter 與 sticky 狀態。', 'Synchronous active-low reset; clears ownership, counters, and sticky state.') };
const spec = (purpose: Localized, clocking: Localized, ports: Record<string, Localized>, algorithm: Localized[], example: ReturnType<typeof e>[], priority: Localized[] = [], assumptions: Localized[] = []): LabSpec => ({ purpose, clocking, ports, algorithm, example, priority, assumptions });

export const hbm4SystemSpecs: Record<string, LabSpec> = {
  'hbm-pin-ownership': spec(b('建立 pin ownership 真值表，避免 controller、PHY 與 test path 在同一拍對 DQ 做互斥操作。', 'Build the pin-ownership truth table that prevents controller, PHY, and test paths from conflicting on DQ.'), comb,
    { row_valid: b('已接受的 row command。', 'Accepted row command.'), col_valid: b('已接受的 column command。', 'Accepted column command.'), wr_data_valid: b('本拍要 launch write data。', 'Write data launches this cycle.'), rd_data_valid: b('本拍要 sample read data。', 'Read data is sampled this cycle.'), test_mode: b('測試介面取得 pins；functional outputs 必須關閉。', 'Test interface owns the pins; functional outputs are disabled.'), drive_ca: b('Controller/PHY command path 可驅動 CA。', 'Command path may drive CA.'), drive_dq: b('Write path 可驅動 DQ。', 'Write path may drive DQ.'), sample_dq: b('Read path可取樣 DQ。', 'Read path may sample DQ.'), conflict: b('functional read/write 同拍衝突。', 'Functional read/write collision.') },
    [b('先偵測 wr_data_valid&&rd_data_valid。', 'Detect wr_data_valid&&rd_data_valid first.'), b('test_mode 或 conflict 時關閉 DQ drive/sample；test_mode 同時關閉 CA。', 'Disable DQ drive/sample on test mode or conflict; test mode also disables CA.')],
    [e('W0', 'wr=1、rd=0、test=0', 'wr=1, rd=0, test=0', 'drive_dq=1', 'drive_dq=1'), e('X0', 'wr=1、rd=1', 'wr=1, rd=1', 'conflict=1、DQ enable 全 0', 'conflict=1 and both DQ enables=0')],
    [b('test_mode > conflict > normal ownership。', 'test_mode > conflict > normal ownership.')], [b('這是數位 ownership；不描述 pad tri-state 電氣行為。', 'This is digital ownership, not pad tri-state electrical behavior.')]),
  'hbm-command-pin-adapter': spec(b('把 accepted row/column bundle 轉成分離 pins 與 APAR。', 'Convert accepted row/column bundles into separate pins and APAR.'), comb,
    { row_fire: b('row payload 本拍真正提交。', 'Row payload truly commits this cycle.'), row_payload: b('10-bit 縮小 row pin payload。', 'Ten-bit reduced row-pin payload.'), col_fire: b('column payload 本拍真正提交。', 'Column payload truly commits this cycle.'), col_payload: b('8-bit 縮小 column pin payload。', 'Eight-bit reduced column-pin payload.'), r: b('輸出 R[9:0]；無效時為 0。', 'R[9:0] output; zero while invalid.'), c: b('輸出 C[7:0]；無效時為 0。', 'C[7:0] output; zero while invalid.'), r_oe: b('row output-enable，等於 row_fire。', 'Row output enable, equal to row_fire.'), c_oe: b('column output-enable，等於 col_fire。', 'Column output enable, equal to col_fire.'), apar: b('對實際輸出 R/C 的 even parity bit。', 'Even-parity bit for the actual R/C outputs.') },
    [b('以 fire gate payload，idle bus 清零。', 'Gate each payload with fire and zero idle buses.'), b('APAR=^{r,c}，使 ^{r,c,apar}=0。', 'APAR=^{r,c}, making ^{r,c,apar}=0.')], [e('C0', 'row_fire=1、col_fire=1', 'row_fire=1, col_fire=1', '兩組 OE=1；R/C 保持各自 payload；總 parity=even', 'Both OEs=1; R/C retain their payloads; total parity is even')], [], [b('真正 pin encoding/edge placement 必須回查合法規格與 PHY contract。', 'Real pin encoding/edge placement must come from the licensed standard and PHY contract.')]),
  'hbm-write-phy-shim': spec(b('在 write burst launch 期間保存 payload 與 DQ/WDQS ownership。', 'Retain payload plus DQ/WDQS ownership through a write-burst launch window.'), sync,
    { ...reset, accept: b('idle 時接受一筆 write beat。', 'Accept one write beat while idle.'), data_in: b('要保存的 64-bit teaching beat。', 'The 64-bit teaching beat to retain.'), busy: b('launch window 尚未完成；上游不得覆寫。', 'Launch window is active; upstream cannot overwrite.'), dq_oe: b('DQ output-enable，整個 busy window 為 1。', 'DQ output enable, high throughout busy.'), wdqs_en: b('WDQS launch enable，與 DQ ownership 對齊。', 'WDQS launch enable aligned with DQ ownership.'), dq_data: b('被保存到 burst 完成的 payload。', 'Payload held until burst completion.') },
    [b('idle&&accept：latch data，count=2。', 'On idle&&accept, latch data and load count=2.'), b('count 非零每拍減一；busy、dq_oe、wdqs_en 都由 count!=0 產生。', 'Decrement nonzero count; busy, dq_oe, and wdqs_en all decode count!=0.')], [e('A0', 'accept data=A', 'accept data=A', 'edge 後 busy=1、dq_data=A', 'after edge busy=1 and dq_data=A'), e('A1', 'busy 中 accept data=B', 'accept data=B while busy', 'dq_data 仍為 A', 'dq_data remains A')], [b('Reset > idle accept > active countdown。', 'Reset > idle accept > active countdown.')], [b('兩拍為縮小教學 profile，不是產品 burst length。', 'Two cycles is a reduced teaching profile, not a product burst length.')]),
  'hbm-read-phy-capture': spec(b('把 PHY 已完成的 read sample 轉成 controller 同步 valid/data。', 'Convert a completed PHY read sample into synchronous controller valid/data.'), sync,
    { ...reset, rdqs_sample: b('PHY 回報本拍有一筆已對齊 DQ beat。', 'PHY reports one aligned DQ beat this cycle.'), dq_in: b('PHY 已取樣並 deskew 的 64-bit beat。', 'PHY-sampled and deskewed 64-bit beat.'), beat_valid: b('對應 beat_data 有效一拍。', 'Qualifies beat_data for one cycle.'), beat_data: b('最後一次有效 sample 的資料；invalid 時保持。', 'Data from the last valid sample; retained while invalid.') },
    [b('每拍 beat_valid 跟隨 rdqs_sample。', 'beat_valid follows rdqs_sample each cycle.'), b('只有 sample=1 時更新 beat_data。', 'Update beat_data only when sample=1.')], [e('R0', 'sample=1、DQ=A', 'sample=1, DQ=A', 'edge 後 valid=1、data=A', 'after edge valid=1 and data=A'), e('R1', 'sample=0、DQ=B', 'sample=0, DQ=B', 'valid=0、data 仍 A', 'valid=0 and data remains A')], [b('Reset > sample capture > idle hold。', 'Reset > sample capture > idle hold.')]),
  'hbm-training-sweep': spec(b('控制八個抽象 PHY taps 的 sweep，保存第一個通過位置與全失敗狀態。', 'Sweep eight abstract PHY taps, retaining the first passing tap and all-fail status.'), sync,
    { ...reset, start: b('idle 時開始新 sweep。', 'Starts a new sweep while idle.'), sample_valid: b('PHY 回報目前 tap 測量完成。', 'PHY reports completion for the current tap.'), sample_pass: b('目前 tap 通過 margin criterion。', 'Current tap passes the margin criterion.'), busy: b('sweep 進行中。', 'Sweep is in progress.'), done: b('第八筆 sample 完成時脈衝一拍。', 'One-cycle pulse after the eighth sample.'), fail: b('完整 sweep 沒有任何 pass。', 'No tap passed the completed sweep.'), tap: b('目前要測的 tap 0–7。', 'Current tap 0–7.'), selected_tap: b('第一個通過的 tap。', 'First passing tap.') },
    [b('start 清除 found/fail 並從 tap0 開始。', 'start clears found/fail and begins at tap0.'), b('sample_valid 時記錄 first pass；tap7 後 done 並依 found 決定 fail。', 'On sample_valid, record the first pass; after tap7, pulse done and derive fail from found.')], [e('T0–T7', '依序回報八筆 sample', 'Report eight samples in sequence', 'tap 遞增；第一個 pass 被鎖住', 'tap increments and the first pass is retained')], [b('Reset > start while idle > sample processing。', 'Reset > start while idle > sample processing.')], [b('實際產品通常選 pass window 中央並處理多 lane；本題先建立控制合約。', 'A product usually selects the center of a pass window across many lanes; this lab first establishes the control contract.')]),
  'hbm-dbi-codec': spec(b('對八個 bytes 獨立執行 DBI 並證明 encode/decode round trip。', 'Apply DBI independently to eight bytes and prove encode/decode round-trip behavior.'), comb,
    { data_in: b('原始 64-bit payload。', 'Original 64-bit payload.'), encoded: b('每 byte 依 DBI 規則選擇原值或反相。', 'Each byte is original or inverted according to DBI.'), dbi: b('bit i=1 表示 byte i 已反相。', 'Bit i is one when byte i was inverted.'), decoded: b('以 encoded+dbi 還原的 64-bit payload。', 'Payload reconstructed from encoded+dbi.') },
    [b('逐 byte 計算 ones；>4 時反相並設 dbi。', 'Count ones per byte; invert and set dbi when >4.'), b('decode 只看對應 byte 的 dbi，必須滿足 decoded===data_in。', 'Decode each byte with its own dbi; decoded must equal data_in.')], [e('B0', 'byte=FF', 'byte=FF', 'dbi=1、encoded=00、decoded=FF', 'dbi=1, encoded=00, decoded=FF'), e('B1', 'byte=F0', 'byte=F0', '四個 1，不反相', 'four ones, no inversion')]),
  'hbm-data-parity-ras': spec(b('產生外部 data-bus parity，並把接收 mismatch 轉成 pulse 與 sticky RAS 狀態。', 'Generate external data-bus parity and turn receive mismatches into pulse plus sticky RAS status.'), sync,
    { ...reset, tx_data: b('要送往 PHY 的 16-bit teaching payload。', 'Sixteen-bit teaching payload sent to the PHY.'), tx_dpar: b('使 payload+DPAR 為 even parity。', 'Makes payload+DPAR even parity.'), rx_valid: b('本拍 rx_data/rx_dpar 有效。', 'rx_data/rx_dpar are valid this cycle.'), rx_data: b('接收 payload。', 'Received payload.'), rx_dpar: b('接收 parity bit。', 'Received parity bit.'), derr_pulse: b('有效資料 parity mismatch 時脈衝一拍。', 'One-cycle pulse on a valid parity mismatch.'), sticky_error: b('任何 mismatch 後保持到 reset。', 'Retained after any mismatch until reset.') },
    [b('tx_dpar=^tx_data。', 'tx_dpar=^tx_data.'), b('mismatch=^{rx_data,rx_dpar}；只有 rx_valid 才報錯。', 'mismatch=^{rx_data,rx_dpar}; report only while rx_valid.')], [e('E0', 'rx_valid=1、parity 正確', 'rx_valid=1 with correct parity', 'pulse=0、sticky 不變', 'pulse=0 and sticky unchanged'), e('E1', '翻轉 parity', 'flip parity', 'pulse=1、sticky=1', 'pulse=1 and sticky=1')], [b('Reset > error capture。', 'Reset > error capture.')]),
  'hbm-ecc-severity': spec(b('將抽象 ECC result 分成四級 SEV，並保留 UE telemetry。', 'Classify an abstract ECC result into four SEV levels and retain UE telemetry.'), sync,
    { ...reset, valid: b('error_count 本拍有效。', 'error_count is valid this cycle.'), error_count: b('抽象偵測到的錯誤數量。', 'Abstract detected error count.'), severity: b('0=NE、1=CEs、2=CEm、3=UE。', '0=NE, 1=CEs, 2=CEm, 3=UE.'), sticky_ue: b('曾出現 UE；reset 前保持。', 'An UE occurred; retained until reset.') },
    [b('invalid 一律 NE；valid 時 0/1/2/>2 對應四級。', 'Invalid always reports NE; valid 0/1/2/>2 maps to four levels.'), b('只有 valid UE 設 sticky_ue。', 'Only a valid UE sets sticky_ue.')], [e('S0–S3', '依序輸入 count 0/1/2/3', 'drive counts 0/1/2/3', 'severity 依序 0/1/2/3', 'severity is 0/1/2/3')], [b('Reset > UE capture。', 'Reset > UE capture.')], [b('這不是 ECC decoder；產品 code、coverage 與 SEV 定義需回查合法文件。', 'This is not an ECC decoder; product code, coverage, and SEV definitions require authorized documentation.')]),
  'hbm-lane-repair-map': spec(b('把 logical lane remap 到八條 physical lanes 加一條 spare。', 'Remap logical lanes onto eight physical lanes plus one spare.'), comb,
    { repair_enable: b('套用一筆有效 repair map。', 'Apply a valid repair map.'), bad_lane: b('失效 physical lane index 0–7。', 'Failed physical lane index 0–7.'), logical_data: b('八條 logical lane 資料。', 'Eight logical-lane bits.'), physical_data: b('bit0–7 為原 lanes，bit8 為 spare。', 'Bits0–7 are original lanes and bit8 is the spare.') },
    [b('預設 physical={0,logical}。', 'Default physical={0,logical}.'), b('repair 時清 bad physical lane，將其 logical value 搬到 spare。', 'On repair, clear the failed physical lane and move its logical value to the spare.')], [e('L3', 'repair=1、bad_lane=3', 'repair=1, bad_lane=3', 'physical[3]=0、physical[8]=logical[3]', 'physical[3]=0 and physical[8]=logical[3]')], [], [b('完整 mapping 還需同步 remap DQS/DBI/ECC metadata；本題刻意縮小。', 'Complete mapping also covers DQS/DBI/ECC metadata; this lab is reduced.')]),
  'hbm-ieee1500-wrapper': spec(b('以 capture/shift/update 分離 observation shadow 與 active test control。', 'Separate observation shadow state from active test control with capture/shift/update.'), sync,
    { ...reset, capture: b('將 status capture 進 shift register。', 'Capture status into the shift register.'), shift: b('由 WSI 串入一 bit。', 'Shift one bit from WSI.'), update: b('將 shift register 原子套用到 active control。', 'Atomically apply the shift register to active control.'), wsi: b('Wrapper serial input。', 'Wrapper serial input.'), status: b('要觀察的四位元狀態。', 'Four-bit status to observe.'), wso: b('Wrapper serial output=shift_reg[0]。', 'Wrapper serial output=shift_reg[0].'), active_control: b('只有 update 能改變的 active control。', 'Active control changed only by update.') },
    [b('capture 載入 status；shift 做 {wsi,shift_reg[3:1]}。', 'Capture loads status; shift performs {wsi,shift_reg[3:1]}.'), b('update 才把 shift register 原子複製到 active control，capture/shift 不得提早改變 active。', 'Only update atomically copies the shift register into active control; capture and shift must not change active early.')], [e('C/S/U', '先 capture 1010，再 shift wsi=1，再 update', 'capture 1010, shift wsi=1, then update', 'active_control=1101', 'active_control=1101')], [b('Reset > capture > shift > update。', 'Reset > capture > shift > update.')], [b('完整 IEEE 1500 protocol/指令與 ATE flow 不在此縮小 register 題。', 'The full IEEE 1500 protocol/instruction and ATE flow are outside this reduced register lab.')]),
  'hbm-package-budget': spec(b('用飽和 arithmetic 檢查 package/interposer timing budget。', 'Check package/interposer timing budget with saturating arithmetic.'), comb,
    { ui_ps: b('一個 UI 的 teaching budget（ps）。', 'Teaching unit-interval budget in ps.'), flight_ps: b('package/interposer flight-time allocation。', 'Package/interposer flight-time allocation.'), skew_ps: b('lane-to-lane skew allocation。', 'Lane-to-lane skew allocation.'), margin_ps: b('setup/jitter/guard allocation。', 'Setup/jitter/guard allocation.'), pass: b('used<=UI。', 'used<=UI.'), used_ps: b('三項 allocation 的 10-bit sum。', 'Ten-bit sum of all allocations.'), remaining_ps: b('通過時 UI-used；失敗時飽和為 0。', 'UI-used on pass; saturates to zero on fail.') },
    [b('先以擴展位寬計算 used。', 'Compute used with extended width.'), b('比較後才做 subtraction，違規不得 underflow。', 'Subtract only after comparison; violations must not underflow.')], [e('P0', 'UI=100、20+30+10', 'UI=100, 20+30+10', 'used=60、remaining=40、pass=1', 'used=60, remaining=40, pass=1'), e('P1', '總和=101', 'sum=101', 'pass=0、remaining=0', 'pass=0, remaining=0')], [], [b('數值必須來自實際 SI/PI/package model；本站只教 ownership 與 arithmetic。', 'Values must come from real SI/PI/package models; this site teaches ownership and arithmetic only.')]),
  'hbm-thermal-throttle': spec(b('將四級 thermal state decode 為 scheduler ACT budget 與 alert。', 'Decode a four-level thermal state into scheduler ACT budget and alert.'), comb,
    { thermal_level: b('同步化的 0–3 thermal state。', 'Synchronized thermal state 0–3.'), act_budget: b('每個 policy window 可允許的新 ACT 數。', 'New ACT operations allowed per policy window.'), alert: b('level>=2 時通知 telemetry/firmware。', 'Notifies telemetry/firmware at level>=2.') },
    [b('0/1/2/3 對應 4/2/1/0，形成逐級降載。', 'Levels 0/1/2/3 map to 4/2/1/0 for progressive throttling.'), b('alert threshold=2；level 3 禁止新 ACT，但不能阻擋必要 refresh。', 'The alert threshold is 2; level 3 blocks new ACT operations but not required refresh.')], [e('T0–T3', '掃過四級 thermal', 'sweep four thermal levels', 'budget=4/2/1/0', 'budget=4/2/1/0')], [], [b('ACT budget 不得關閉 correctness-required refresh。', 'ACT budget must not block correctness-required refresh.')]),
  'hbm-bandwidth-window': spec(b('在 observation window 計數 cycles 與成功 data beats，輸出可回推 throughput/utilization 的 snapshot。', 'Count cycles and successful data beats in an observation window and emit a snapshot for throughput/utilization.'), sync,
    { ...reset, enable: b('本拍屬於 observation window。', 'Current cycle belongs to the observation window.'), beat_fire: b('本拍真正傳輸一個 data beat。', 'One data beat truly transfers this cycle.'), window_end: b('本拍結束 observation window。', 'Current cycle closes the observation window.'), valid: b('snapshot valid 一拍。', 'Snapshot-valid pulse.'), cycles: b('包含 window_end 當拍的 enable count。', 'Enable count including the window_end cycle.'), beats: b('包含 window_end 當拍的 beat count。', 'Beat count including the window_end cycle.') },
    [b('非 end 時分別累加 enable/beat_fire。', 'Accumulate enable and beat_fire independently before window end.'), b('end 時 snapshot counter+本拍事件、清 counter、valid pulse。', 'At end, snapshot counters plus same-cycle events, clear counters, and pulse valid.')], [e('W0–W4', '五個 enable cycles，其中四個 beat_fire，最後一拍 end', 'five enabled cycles, four beat_fire, end on the last', 'cycles=5、beats=4、valid=1', 'cycles=5, beats=4, valid=1')], [b('Reset > window_end snapshot > ordinary accumulation。', 'Reset > window_end snapshot > ordinary accumulation.')]),
  'hbm-pim-qos-arbiter': spec(b('在 host、PIM 與 urgent refresh 間產生 one-hot grant。', 'Produce a one-hot grant among host, PIM, and urgent refresh.'), sync,
    { ...reset, host_req: b('一般 host memory request。', 'Normal host-memory request.'), pim_req: b('PIM operation request。', 'PIM operation request.'), refresh_urgent: b('不可再延後的 refresh/RFM maintenance。', 'Refresh/RFM maintenance that cannot be postponed.'), grant_host: b('本拍選 host。', 'Host wins this cycle.'), grant_pim: b('本拍選 PIM。', 'PIM wins this cycle.'), grant_refresh: b('本拍選 maintenance。', 'Maintenance wins this cycle.') },
    [b('urgent refresh 獨占；否則單方 request 直接 grant。', 'Urgent refresh is exclusive; otherwise a sole requester wins.'), b('host/pim 同時 request 時依 turn 交替；pointer 只隨真正 grant 前進。', 'On a host/PIM tie, alternate by turn; advance turn only on a true grant.')], [e('Q0/Q1/Q2', 'host=pim=1 持續三拍', 'host=pim=1 for three cycles', 'host、pim、host 交替', 'host, pim, host alternate'), e('R0', 'refresh_urgent=1', 'refresh_urgent=1', '只有 grant_refresh=1', 'only grant_refresh=1')], [b('Reset > refresh > host/PIM policy。', 'Reset > refresh > host/PIM policy.')], [b('完整 PIM protocol 與 DRAM internal execution 不在此 arbiter 題。', 'The full PIM protocol and internal DRAM execution are outside this arbiter lab.')]),
};

const ref = (topicsZh: string, topicsEn: string): LabReference => ({
  source: b('公開 HBM4 系統介面主題＋獨立教學模型', 'Public HBM4 system-interface topics plus an independent teaching model'),
  topics: b(topicsZh, topicsEn),
  profile: b('題目不重製 JEDEC normative tables 或 vendor PHY/package data。產品實作必須使用合法取得的規格、PHY contract、speed bin 與 package/SI/PI model。', 'These labs do not reproduce JEDEC normative tables or vendor PHY/package data. Product work requires authorized standards, the PHY contract, speed bin, and package/SI/PI models.'),
});

export const hbm4SystemReferences: Record<string, LabReference> = {
  'hbm-pin-ownership': ref('完整 pin interface、訊號方向與 ownership', 'Full pin interface, signal directions, and ownership'),
  'hbm-command-pin-adapter': ref('R/C command paths、APAR/AERR 與 PHY boundary', 'R/C command paths, APAR/AERR, and the PHY boundary'),
  'hbm-write-phy-shim': ref('DQ／WDQS write launch contract', 'DQ/WDQS write-launch contract'),
  'hbm-read-phy-capture': ref('DQ／RDQS read-capture contract', 'DQ/RDQS read-capture contract'),
  'hbm-training-sweep': ref('Training、calibration、loopback 與 failure policy', 'Training, calibration, loopback, and failure policy'),
  'hbm-dbi-codec': ref('Per-byte DBI encode/decode 與 switching activity', 'Per-byte DBI encoding/decoding and switching activity'),
  'hbm-data-parity-ras': ref('DPAR／DERR 外部資料匯流排保護', 'DPAR/DERR external data-bus protection'),
  'hbm-ecc-severity': ref('ECC metadata、SEV telemetry 與 on-die ECC 邊界', 'ECC metadata, SEV telemetry, and the on-die ECC boundary'),
  'hbm-lane-repair-map': ref('RA／RD spare lanes、soft/hard repair 與 remap ownership', 'RA/RD spare lanes, soft/hard repair, and remap ownership'),
  'hbm-ieee1500-wrapper': ref('WRCK／WRST_n／WSI／WSO 與 IEEE 1500 access', 'WRCK/WRST_n/WSI/WSO and IEEE 1500 access'),
  'hbm-package-budget': ref('Microbump／interposer／package timing、SI/PI budget ownership', 'Microbump/interposer/package timing and SI/PI budget ownership'),
  'hbm-thermal-throttle': ref('Stack thermal/power telemetry 與 sustainable bandwidth', 'Stack thermal/power telemetry and sustainable bandwidth'),
  'hbm-bandwidth-window': ref('Peak versus measured throughput、utilization 與 stall accounting', 'Peak versus measured throughput, utilization, and stall accounting'),
  'hbm-pim-qos-arbiter': ref('Host/PIM/maintenance 共用資源與 QoS', 'Host/PIM/maintenance shared resources and QoS'),
};
