import type { Challenge } from './challenges';

const pass = `
task check;
  input condition;
  begin
    if (condition !== 1'b1) begin
      $display("@@FAIL@@ check failed at time %0t (including X/Z)", $time);
      $finish;
    end
  end
endtask
`;

// Controller-visible system labs.  Values and widths are intentionally reduced
// teaching profiles; they are not a redistribution of normative speed-bin data.
export const hbm4SystemChallenges: Challenge[] = [
  {
    id: 'hbm-pin-ownership', order: 14, track: 'hbm', difficulty: 'intermediate', minutes: 35, points: 240,
    kind: 'build', judge: 'simulation', language: 'Verilog-2005',
    title: { zh: 'HBM Pin Ownership／方向防衝突', en: 'HBM pin ownership and direction guard' },
    description: { zh: '把 command、write DQ、read DQ 與 test mode 的 ownership 轉成明確的 drive/sample enable，先釐清 Controller、PHY 與測試邏輯各自擁有什麼。', en: 'Turn command, write-DQ, read-DQ, and test-mode ownership into explicit drive/sample enables, clarifying controller, PHY, and test responsibilities.' },
    specs: [{ zh: 'row_valid 或 col_valid 使 drive_ca=1；wr_data_valid 使 drive_dq=1；rd_data_valid 使 sample_dq=1。', en: 'row_valid or col_valid drives drive_ca; wr_data_valid drives drive_dq; rd_data_valid drives sample_dq.' }, { zh: 'test_mode 壓住所有 functional enable；read/write 同拍時 conflict=1 且 DQ 不得 drive/sample。', en: 'test_mode suppresses all functional enables; simultaneous read/write raises conflict and disables both DQ actions.' }],
    testGroups: [{ zh: 'CA ownership', en: 'CA ownership' }, { zh: '讀寫互斥', en: 'Read/write exclusion' }, { zh: '測試模式隔離', en: 'Test-mode isolation' }],
    hints: [{ zh: '先算 rw_conflict，再讓 drive_dq/sample_dq 都以 !rw_conflict 與 !test_mode gating。', en: 'Compute rw_conflict first, then gate drive_dq and sample_dq with !rw_conflict and !test_mode.' }],
    starter: `module hbm_pin_owner(input wire row_valid,input wire col_valid,input wire wr_data_valid,input wire rd_data_valid,input wire test_mode,output wire drive_ca,output wire drive_dq,output wire sample_dq,output wire conflict);assign drive_ca=0;assign drive_dq=0;assign sample_dq=0;assign conflict=0;endmodule`,
    referenceSolution: `module hbm_pin_owner(input wire row_valid,input wire col_valid,input wire wr_data_valid,input wire rd_data_valid,input wire test_mode,output wire drive_ca,output wire drive_dq,output wire sample_dq,output wire conflict);wire rw_conflict=wr_data_valid&&rd_data_valid;assign conflict=rw_conflict&&!test_mode;assign drive_ca=(row_valid||col_valid)&&!test_mode;assign drive_dq=wr_data_valid&&!rw_conflict&&!test_mode;assign sample_dq=rd_data_valid&&!rw_conflict&&!test_mode;endmodule`,
    testbench: `module tb;reg r=0,c=0,w=0,d=0,t=0;wire ca,dq,s,x;hbm_pin_owner dut(r,c,w,d,t,ca,dq,s,x);${pass}initial begin #1;check(!ca&&!dq&&!s&&!x);r=1;#1;check(ca);r=0;w=1;#1;check(dq&&!s&&!x);w=0;d=1;#1;check(!dq&&s&&!x);w=1;#1;check(x&&!dq&&!s);t=1;#1;check(!ca&&!dq&&!s&&!x);$display("@@PASS@@");$finish;end endmodule`,
  },
  {
    id: 'hbm-command-pin-adapter', order: 15, track: 'hbm', difficulty: 'advanced', minutes: 45, points: 300,
    kind: 'build', judge: 'simulation', language: 'Verilog-2005',
    title: { zh: 'Row／Column Command Pin Adapter', en: 'Row/column command pin adapter' },
    description: { zh: '將同步 command bundle 映射成獨立 R[9:0]、C[7:0] 與 APAR；本題停在數位 PHY 合約，不處理 CK 電氣時序。', en: 'Map a synchronous command bundle to separate R[9:0], C[7:0], and APAR outputs. The lab stops at the digital PHY contract and does not model CK electrical timing.' },
    specs: [{ zh: 'row_fire/col_fire 分別控制對應 output-enable；idle bus 輸出 0。', en: 'row_fire and col_fire independently control their output enables; idle buses drive zero.' }, { zh: 'APAR 對所有有效的 row/column payload 產生 even parity。', en: 'APAR provides even parity across every valid row/column payload.' }],
    testGroups: [{ zh: '雙命令同拍', en: 'Dual command in one cycle' }, { zh: 'idle gating', en: 'Idle gating' }, { zh: 'parity', en: 'Parity' }],
    hints: [{ zh: '先以 fire 將無效 payload 清零，再對實際輸出的 R/C 做 reduction XOR。', en: 'First zero invalid payloads with fire, then reduction-XOR the actual R/C outputs.' }],
    starter: `module hbm_cmd_pins(input wire row_fire,input wire[9:0]row_payload,input wire col_fire,input wire[7:0]col_payload,output wire[9:0]r,output wire[7:0]c,output wire r_oe,output wire c_oe,output wire apar);assign r=0;assign c=0;assign r_oe=0;assign c_oe=0;assign apar=0;endmodule`,
    referenceSolution: `module hbm_cmd_pins(input wire row_fire,input wire[9:0]row_payload,input wire col_fire,input wire[7:0]col_payload,output wire[9:0]r,output wire[7:0]c,output wire r_oe,output wire c_oe,output wire apar);assign r_oe=row_fire;assign c_oe=col_fire;assign r=row_fire?row_payload:10'b0;assign c=col_fire?col_payload:8'b0;assign apar=^{r,c};endmodule`,
    testbench: `module tb;reg rf=0,cf=0;reg[9:0]rp=0;reg[7:0]cp=0;wire[9:0]r;wire[7:0]c;wire ro,co,p;hbm_cmd_pins dut(rf,rp,cf,cp,r,c,ro,co,p);${pass}initial begin #1;check(r==0&&c==0&&!ro&&!co&&!p);rf=1;rp=10'h155;#1;check(ro&&!co&&r==10'h155&&c==0&&((^{r,c,p})===1'b0));cf=1;cp=8'ha6;#1;check(ro&&co&&r==rp&&c==cp&&((^{r,c,p})===1'b0));rf=0;#1;check(r==0&&c==cp&&!ro&&co);$display("@@PASS@@");$finish;end endmodule`,
  },
  {
    id: 'hbm-write-phy-shim', order: 16, track: 'hbm', difficulty: 'advanced', minutes: 60, points: 380,
    kind: 'build', judge: 'simulation', language: 'Verilog-2005',
    title: { zh: 'DQ／WDQS Write PHY Shim', en: 'DQ/WDQS write PHY shim' },
    description: { zh: '把 controller 的一筆 64-bit write beat 保存到 PHY boundary，並在固定兩拍 launch window 內維持 DQ ownership 與 WDQS enable。', en: 'Hold one 64-bit controller write beat at the PHY boundary and retain DQ ownership plus WDQS enable for a two-cycle launch window.' },
    specs: [{ zh: 'accept 只在 !busy 時取樣 data；busy 時新的 accept 不能覆寫 payload。', en: 'Sample data on accept only while idle; a new accept while busy cannot overwrite the payload.' }, { zh: '接受後 dq_oe/wdqs_en 維持兩個完整 cycle，之後同時清除。', en: 'After acceptance, dq_oe and wdqs_en remain high for two complete cycles, then clear together.' }],
    testGroups: [{ zh: 'payload ownership', en: 'Payload ownership' }, { zh: '兩拍 launch', en: 'Two-cycle launch' }, { zh: 'busy overwrite protection', en: 'Busy overwrite protection' }],
    hints: [{ zh: '用 2-bit count 表示剩餘 launch cycles；資料只在 idle accept 時更新。', en: 'Use a two-bit count for remaining launch cycles; update data only on an idle accept.' }],
    starter: `module hbm_write_shim(input wire clk,input wire rst_n,input wire accept,input wire[63:0]data_in,output wire busy,output wire dq_oe,output wire wdqs_en,output reg[63:0]dq_data);assign busy=0;assign dq_oe=0;assign wdqs_en=0;always @(posedge clk)if(!rst_n)dq_data<=0;endmodule`,
    referenceSolution: `module hbm_write_shim(input wire clk,input wire rst_n,input wire accept,input wire[63:0]data_in,output wire busy,output wire dq_oe,output wire wdqs_en,output reg[63:0]dq_data);reg[1:0]count;assign busy=count!=0;assign dq_oe=busy;assign wdqs_en=busy;always @(posedge clk)begin if(!rst_n)begin count<=0;dq_data<=0;end else if(!busy&&accept)begin dq_data<=data_in;count<=2;end else if(busy)count<=count-1'b1;end endmodule`,
    testbench: `module tb;reg clk=0,rst_n=0,a=0;reg[63:0]d=0;wire b,oe,st;wire[63:0]q;hbm_write_shim dut(clk,rst_n,a,d,b,oe,st,q);always #5 clk=~clk;${pass}initial begin repeat(2)@(posedge clk);rst_n=1;d=64'h1234;a=1;@(posedge clk);#1;a=0;check(b&&oe&&st&&q==64'h1234);d=64'hdead;a=1;@(posedge clk);#1;check(b&&q==64'h1234);a=0;@(posedge clk);#1;check(!b&&!oe&&!st&&q==64'h1234);$display("@@PASS@@");$finish;end endmodule`,
  },
  {
    id: 'hbm-read-phy-capture', order: 17, track: 'hbm', difficulty: 'advanced', minutes: 50, points: 340,
    kind: 'build', judge: 'simulation', language: 'Verilog-2005',
    title: { zh: 'RDQS Read Beat Capture', en: 'RDQS read-beat capture' },
    description: { zh: '以抽象化的 rdqs_sample 將 PHY 已對齊的一拍 DQ 送回 controller，建立「類比取樣在 PHY、transaction ownership 在 controller」的邊界。', en: 'Use an abstract rdqs_sample to return one PHY-aligned DQ beat to the controller, separating analog sampling from controller transaction ownership.' },
    specs: [{ zh: 'rdqs_sample=1 的上升緣捕捉 dq_in，下一拍輸出 beat_valid=1。', en: 'Capture dq_in on a rising edge with rdqs_sample=1 and assert beat_valid for the following cycle.' }, { zh: '沒有 sample 時 beat_valid=0，beat_data 保留上次資料。', en: 'Without a sample, beat_valid is zero while beat_data retains the last beat.' }],
    testGroups: [{ zh: '單拍 valid', en: 'One-cycle valid' }, { zh: '資料保持', en: 'Data retention' }, { zh: '連續 beats', en: 'Back-to-back beats' }],
    hints: [{ zh: '每拍先預設 beat_valid<=0；sample 時再覆寫成 1 並 capture data。', en: 'Default beat_valid low each cycle, then set it and capture data when sample is high.' }],
    starter: `module hbm_read_capture(input wire clk,input wire rst_n,input wire rdqs_sample,input wire[63:0]dq_in,output reg beat_valid,output reg[63:0]beat_data);always @(posedge clk)begin beat_valid<=0;end endmodule`,
    referenceSolution: `module hbm_read_capture(input wire clk,input wire rst_n,input wire rdqs_sample,input wire[63:0]dq_in,output reg beat_valid,output reg[63:0]beat_data);always @(posedge clk)begin if(!rst_n)begin beat_valid<=0;beat_data<=0;end else begin beat_valid<=rdqs_sample;if(rdqs_sample)beat_data<=dq_in;end end endmodule`,
    testbench: `module tb;reg clk=0,rst_n=0,s=0;reg[63:0]d=0;wire v;wire[63:0]q;hbm_read_capture dut(clk,rst_n,s,d,v,q);always #5 clk=~clk;${pass}initial begin repeat(2)@(posedge clk);rst_n=1;d=64'h11;s=1;@(posedge clk);#1;check(v&&q==64'h11);s=0;d=64'h22;@(posedge clk);#1;check(!v&&q==64'h11);s=1;@(posedge clk);#1;check(v&&q==64'h22);d=64'h33;@(posedge clk);#1;check(v&&q==64'h33);$display("@@PASS@@");$finish;end endmodule`,
  },
  {
    id: 'hbm-training-sweep', order: 18, track: 'hbm', difficulty: 'advanced', minutes: 70, points: 440,
    kind: 'build', judge: 'simulation', language: 'Verilog-2005',
    title: { zh: 'Training／Calibration Tap Sweep', en: 'Training/calibration tap sweep' },
    description: { zh: '控制八個抽象 delay taps 的 sweep，收集 PHY 回報的 pass/fail，完成後選第一個通過 tap；真正 eye sampling 與 delay line 留在 PHY。', en: 'Sweep eight abstract delay taps, collect PHY pass/fail results, and select the first passing tap. Actual eye sampling and delay lines stay in the PHY.' },
    specs: [{ zh: 'start 後 busy=1，sample_valid 每次記錄目前 tap，然後 tap+1。', en: 'After start, busy is high; every sample_valid records the current tap then increments it.' }, { zh: '第八筆 sample 後 done pulse；若沒有任何 pass，fail=1。', en: 'Pulse done after the eighth sample; assert fail if no tap passed.' }],
    testGroups: [{ zh: '八 tap sweep', en: 'Eight-tap sweep' }, { zh: 'first-pass selection', en: 'First-pass selection' }, { zh: 'all-fail', en: 'All-fail' }],
    hints: [{ zh: '用 found bit 確保 selected_tap 只被第一個 pass 改寫。', en: 'Use a found bit so only the first passing sample updates selected_tap.' }],
    starter: `module hbm_training(input wire clk,input wire rst_n,input wire start,input wire sample_valid,input wire sample_pass,output reg busy,output reg done,output reg fail,output reg[2:0]tap,output reg[2:0]selected_tap);always @(posedge clk)if(!rst_n)begin busy<=0;done<=0;fail<=0;tap<=0;selected_tap<=0;end endmodule`,
    referenceSolution: `module hbm_training(input wire clk,input wire rst_n,input wire start,input wire sample_valid,input wire sample_pass,output reg busy,output reg done,output reg fail,output reg[2:0]tap,output reg[2:0]selected_tap);reg found;always @(posedge clk)begin if(!rst_n)begin busy<=0;done<=0;fail<=0;tap<=0;selected_tap<=0;found<=0;end else begin done<=0;if(start&&!busy)begin busy<=1;fail<=0;tap<=0;found<=0;end else if(busy&&sample_valid)begin if(sample_pass&&!found)begin found<=1;selected_tap<=tap;end if(tap==7)begin busy<=0;done<=1;fail<=!(found||sample_pass);end else tap<=tap+1'b1;end end end endmodule`,
    testbench: `module tb;reg clk=0,rst_n=0,start=0,sv=0,sp=0;wire busy,done,fail;wire[2:0]tap,sel;integer i;hbm_training dut(clk,rst_n,start,sv,sp,busy,done,fail,tap,sel);always #5 clk=~clk;${pass}initial begin repeat(2)@(posedge clk);rst_n=1;start=1;@(posedge clk);#1;start=0;check(busy&&tap==0);sv=1;for(i=0;i<8;i=i+1)begin sp=(i==3)||(i==4);@(posedge clk);#1;end sv=0;check(done&&!busy&&!fail&&sel==3);@(posedge clk);#1;start=1;@(posedge clk);#1;start=0;sv=1;sp=0;repeat(8)@(posedge clk);#1;check(done&&fail);$display("@@PASS@@");$finish;end endmodule`,
  },
  {
    id: 'hbm-dbi-codec', order: 19, track: 'hbm', difficulty: 'advanced', minutes: 55, points: 360,
    kind: 'build', judge: 'simulation', language: 'Verilog-2005',
    title: { zh: 'Per-byte DBI Encode／Decode', en: 'Per-byte DBI encode/decode' },
    description: { zh: '每個 byte 獨立計算 data bus inversion；1 的數量超過四個時反相 payload 並拉高對應 DBI bit，降低同時切換活動。', en: 'Apply data-bus inversion per byte. If a byte has more than four ones, invert it and assert its DBI bit to reduce switching activity.' },
    specs: [{ zh: '64-bit data 分成八個 bytes；每 byte 獨立判斷。', en: 'Split 64-bit data into eight bytes and decide independently.' }, { zh: 'decode 必須以 dbi 將 encoded_data 還原成原始 data。', en: 'Decode must reconstruct the original data using dbi.' }],
    testGroups: [{ zh: '邊界 popcount=4/5', en: 'Popcount boundary 4/5' }, { zh: '八 byte 獨立', en: 'Eight independent bytes' }, { zh: 'round trip', en: 'Round trip' }],
    hints: [{ zh: '用 function 計算 8-bit popcount，再用 generate/for 逐 byte 編碼。', en: 'Use a function for eight-bit popcount, then encode each byte in a loop.' }],
    starter: `module hbm_dbi(input wire[63:0]data_in,output reg[63:0]encoded,output reg[7:0]dbi,output reg[63:0]decoded);integer i;always @*begin encoded=0;dbi=0;decoded=0;end endmodule`,
    referenceSolution: `module hbm_dbi(input wire[63:0]data_in,output reg[63:0]encoded,output reg[7:0]dbi,output reg[63:0]decoded);integer i,j;integer ones;reg[7:0]b;always @*begin encoded=0;dbi=0;decoded=0;for(i=0;i<8;i=i+1)begin b=data_in[i*8+:8];ones=0;for(j=0;j<8;j=j+1)ones=ones+b[j];dbi[i]=(ones>4);encoded[i*8+:8]=dbi[i]?~b:b;decoded[i*8+:8]=dbi[i]?~encoded[i*8+:8]:encoded[i*8+:8];end end endmodule`,
    testbench: `module tb;reg[63:0]d;wire[63:0]e,r;wire[7:0]b;integer i;hbm_dbi dut(d,e,b,r);${pass}initial begin d=64'h00ff_f0f0_ffff_0f0f;#1;check(r===d);check(b[0]==0);check(b[2]==1);d=0;#1;check(e==0&&b==0&&r==0);for(i=0;i<100;i=i+1)begin d={$random,$random};#1;check(r===d);end $display("@@PASS@@");$finish;end endmodule`,
  },
  {
    id: 'hbm-data-parity-ras', order: 20, track: 'hbm', difficulty: 'advanced', minutes: 50, points: 340,
    kind: 'build', judge: 'simulation', language: 'Verilog-2005',
    title: { zh: 'DPAR／DERR Data-bus Protection', en: 'DPAR/DERR data-bus protection' },
    description: { zh: '在 controller/PHY 資料邊界產生 DPAR，並把接收端 parity mismatch 轉成單拍 DERR 與 sticky telemetry；它和 on-die ECC 是不同保護層。', en: 'Generate DPAR at the controller/PHY data boundary and convert a receive parity mismatch into a DERR pulse plus sticky telemetry. This is distinct from on-die ECC.' },
    specs: [{ zh: 'tx_dpar 使 {tx_data,tx_dpar} 為 even parity。', en: 'tx_dpar makes {tx_data,tx_dpar} even parity.' }, { zh: 'rx_valid 時才檢查；錯誤產生 derr_pulse 並鎖住 sticky_error。', en: 'Check only on rx_valid; a mismatch pulses derr_pulse and latches sticky_error.' }],
    testGroups: [{ zh: 'TX parity', en: 'TX parity' }, { zh: 'RX error pulse', en: 'RX error pulse' }, { zh: 'sticky telemetry', en: 'Sticky telemetry' }],
    hints: [{ zh: 'even parity bit 可直接使用 reduction XOR；receiver 檢查 ^{data,parity}。', en: 'The even-parity bit is a reduction XOR; the receiver checks ^{data,parity}.' }],
    starter: `module hbm_data_parity(input wire clk,input wire rst_n,input wire[15:0]tx_data,output wire tx_dpar,input wire rx_valid,input wire[15:0]rx_data,input wire rx_dpar,output reg derr_pulse,output reg sticky_error);assign tx_dpar=0;always @(posedge clk)begin derr_pulse<=0;end endmodule`,
    referenceSolution: `module hbm_data_parity(input wire clk,input wire rst_n,input wire[15:0]tx_data,output wire tx_dpar,input wire rx_valid,input wire[15:0]rx_data,input wire rx_dpar,output reg derr_pulse,output reg sticky_error);wire mismatch=^{rx_data,rx_dpar};assign tx_dpar=^tx_data;always @(posedge clk)begin if(!rst_n)begin derr_pulse<=0;sticky_error<=0;end else begin derr_pulse<=rx_valid&&mismatch;if(rx_valid&&mismatch)sticky_error<=1;end end endmodule`,
    testbench: `module tb;reg clk=0,rst_n=0,v=0,p=0;reg[15:0]tx=0,rx=0;wire tp,e,s;hbm_data_parity dut(clk,rst_n,tx,tp,v,rx,p,e,s);always #5 clk=~clk;${pass}initial begin repeat(2)@(posedge clk);rst_n=1;tx=16'h1234;#1;check(^{tx,tp}===0);rx=16'ha55a;p=^rx;v=1;@(posedge clk);#1;check(!e&&!s);p=~p;@(posedge clk);#1;check(e&&s);v=0;@(posedge clk);#1;check(!e&&s);$display("@@PASS@@");$finish;end endmodule`,
  },
  {
    id: 'hbm-ecc-severity', order: 21, track: 'hbm', difficulty: 'advanced', minutes: 50, points: 350,
    kind: 'build', judge: 'simulation', language: 'Verilog-2005',
    title: { zh: 'ECC／SEV Severity Classification', en: 'ECC/SEV severity classification' },
    description: { zh: '把抽象 ECC decoder 回報的 error_count 分類為 NE、CEs、CEm、UE，並對 UE 建立 sticky interrupt 狀態。', en: 'Classify an abstract ECC decoder error_count into NE, CEs, CEm, or UE and latch a sticky interrupt state for UE.' },
    specs: [{ zh: 'severity：0=NE、1=CEs、2=CEm、3=UE；valid=0 一律回 NE。', en: 'severity: 0=NE, 1=CEs, 2=CEm, 3=UE; valid=0 always reports NE.' }, { zh: 'error_count 0/1/2/>2 對應四級；UE sticky 只由 reset 清除。', en: 'error_count 0/1/2/>2 maps to the four levels; only reset clears UE sticky.' }],
    testGroups: [{ zh: '四級分類', en: 'Four-level classification' }, { zh: 'valid gating', en: 'Valid gating' }, { zh: 'UE sticky', en: 'UE sticky' }],
    hints: [{ zh: 'severity 是組合 decode；sticky_ue 是 sequential telemetry，兩者不要混成同一狀態。', en: 'severity is combinational decode; sticky_ue is sequential telemetry. Keep them separate.' }],
    starter: `module hbm_ecc_sev(input wire clk,input wire rst_n,input wire valid,input wire[2:0]error_count,output reg[1:0]severity,output reg sticky_ue);always @*severity=0;always @(posedge clk)if(!rst_n)sticky_ue<=0;endmodule`,
    referenceSolution: `module hbm_ecc_sev(input wire clk,input wire rst_n,input wire valid,input wire[2:0]error_count,output reg[1:0]severity,output reg sticky_ue);always @*begin severity=0;if(valid)begin if(error_count==0)severity=0;else if(error_count==1)severity=1;else if(error_count==2)severity=2;else severity=3;end end always @(posedge clk)begin if(!rst_n)sticky_ue<=0;else if(valid&&error_count>2)sticky_ue<=1;end endmodule`,
    testbench: `module tb;reg clk=0,rst_n=0,v=0;reg[2:0]n=0;wire[1:0]sev;wire u;hbm_ecc_sev dut(clk,rst_n,v,n,sev,u);always #5 clk=~clk;${pass}initial begin repeat(2)@(posedge clk);rst_n=1;v=1;n=0;#1;check(sev==0);n=1;#1;check(sev==1);n=2;#1;check(sev==2);n=3;#1;check(sev==3);@(posedge clk);#1;check(u);v=0;n=7;#1;check(sev==0);@(posedge clk);#1;check(u);$display("@@PASS@@");$finish;end endmodule`,
  },
  {
    id: 'hbm-lane-repair-map', order: 22, track: 'hbm', difficulty: 'capstone', minutes: 70, points: 470,
    kind: 'build', judge: 'simulation', language: 'Verilog-2005',
    title: { zh: 'RA／RD Lane Repair Remap', en: 'RA/RD lane-repair remap' },
    description: { zh: '以八條 teaching lanes 加一條 spare 建立 logical-to-physical remap；repair enable 後，壞 lane 位置不再驅動，對應 logical bit 移到 spare。', en: 'Build logical-to-physical remapping for eight teaching lanes plus one spare. Once repair is enabled, the failed physical lane is disabled and its logical bit moves to the spare.' },
    specs: [{ zh: '沒有 repair 時 physical[7:0]=logical、physical[8]=0。', en: 'Without repair, physical[7:0]=logical and physical[8]=0.' }, { zh: 'repair 時 physical[bad_lane]=0、physical[8]=logical[bad_lane]，其他 lane 不變。', en: 'With repair, physical[bad_lane]=0, physical[8]=logical[bad_lane], and other lanes remain unchanged.' }],
    testGroups: [{ zh: '透明 mapping', en: 'Transparent mapping' }, { zh: '所有 bad lane', en: 'Every failed lane' }, { zh: 'spare ownership', en: 'Spare ownership' }],
    hints: [{ zh: '先複製 logical 到 physical[7:0]，再覆寫 bad lane 與 spare。', en: 'First copy logical into physical[7:0], then override the failed lane and spare.' }],
    starter: `module hbm_lane_repair(input wire repair_enable,input wire[2:0]bad_lane,input wire[7:0]logical_data,output reg[8:0]physical_data);always @*physical_data=0;endmodule`,
    referenceSolution: `module hbm_lane_repair(input wire repair_enable,input wire[2:0]bad_lane,input wire[7:0]logical_data,output reg[8:0]physical_data);always @*begin physical_data={1'b0,logical_data};if(repair_enable)begin physical_data[bad_lane]=1'b0;physical_data[8]=logical_data[bad_lane];end end endmodule`,
    testbench: `module tb;reg en=0;reg[2:0]bad=0;reg[7:0]d=8'ha5;wire[8:0]p;integer i;hbm_lane_repair dut(en,bad,d,p);${pass}initial begin #1;check(p==9'h0a5);en=1;for(i=0;i<8;i=i+1)begin bad=i;#1;check(p[8]===d[i]);check(p[i]===1'b0);check((p[7:0]|(8'b1<<i))== (d|(8'b1<<i)));end $display("@@PASS@@");$finish;end endmodule`,
  },
  {
    id: 'hbm-ieee1500-wrapper', order: 23, track: 'hbm', difficulty: 'advanced', minutes: 65, points: 420,
    kind: 'build', judge: 'simulation', language: 'Verilog-2005',
    title: { zh: 'IEEE 1500 Capture／Shift／Update', en: 'IEEE 1500 capture/shift/update wrapper' },
    description: { zh: '建立四位元 teaching wrapper register：Capture 收進 status、Shift 由 WSI 串移、Update 才把 shadow 套用到 active control。', en: 'Build a four-bit teaching wrapper register: Capture loads status, Shift serializes from WSI, and Update applies shadow state to active control.' },
    specs: [{ zh: '同拍優先序 capture > shift > update；WSO 為 shift_reg[0]。', en: 'Same-cycle priority is capture > shift > update; WSO is shift_reg[0].' }, { zh: '只有 update 可以改 active_control。', en: 'Only update may change active_control.' }],
    testGroups: [{ zh: 'capture', en: 'Capture' }, { zh: 'serial shift', en: 'Serial shift' }, { zh: 'update isolation', en: 'Update isolation' }],
    hints: [{ zh: '使用 shadow shift_reg 與 active_control 兩組 registers；不能 shift 時直接改控制輸出。', en: 'Use separate shadow shift_reg and active_control registers; shifting must not directly alter control.' }],
    starter: `module hbm_wrapper1500(input wire clk,input wire rst_n,input wire capture,input wire shift,input wire update,input wire wsi,input wire[3:0]status,output wire wso,output reg[3:0]active_control);reg[3:0]shift_reg;assign wso=0;always @(posedge clk)if(!rst_n)begin shift_reg<=0;active_control<=0;end endmodule`,
    referenceSolution: `module hbm_wrapper1500(input wire clk,input wire rst_n,input wire capture,input wire shift,input wire update,input wire wsi,input wire[3:0]status,output wire wso,output reg[3:0]active_control);reg[3:0]shift_reg;assign wso=shift_reg[0];always @(posedge clk)begin if(!rst_n)begin shift_reg<=0;active_control<=0;end else if(capture)shift_reg<=status;else if(shift)shift_reg<={wsi,shift_reg[3:1]};else if(update)active_control<=shift_reg;end endmodule`,
    testbench: `module tb;reg clk=0,rst_n=0,cap=0,sh=0,up=0,si=0;reg[3:0]st=0;wire so;wire[3:0]a;hbm_wrapper1500 dut(clk,rst_n,cap,sh,up,si,st,so,a);always #5 clk=~clk;${pass}initial begin repeat(2)@(posedge clk);rst_n=1;st=4'b1010;cap=1;@(posedge clk);#1;cap=0;check(so==0&&a==0);sh=1;si=1;@(posedge clk);#1;sh=0;check(so==1&&a==0);up=1;@(posedge clk);#1;up=0;check(a==4'b1101);$display("@@PASS@@");$finish;end endmodule`,
  },
  {
    id: 'hbm-package-budget', order: 24, track: 'hbm', difficulty: 'advanced', minutes: 45, points: 300,
    kind: 'constraint', judge: 'simulation', language: 'Verilog-2005',
    title: { zh: 'Package／Interposer Timing Budget', en: 'Package/interposer timing budget' },
    description: { zh: '把 package flight time、lane skew 與 setup margin 轉成 controller/PHY 可檢查的 budget；這是數位合約檢查，不是取代 EM／SI 模擬。', en: 'Convert package flight time, lane skew, and setup margin into a controller/PHY budget check. This digital contract does not replace EM/SI simulation.' },
    specs: [{ zh: 'used_ps=flight_ps+skew_ps+margin_ps；used<=ui_ps 時 pass=1。', en: 'used_ps=flight_ps+skew_ps+margin_ps; pass is one when used<=ui_ps.' }, { zh: 'remaining_ps 飽和在 0，不可 unsigned underflow。', en: 'remaining_ps saturates at zero and must not underflow.' }],
    testGroups: [{ zh: '剛好壓線', en: 'Exact boundary' }, { zh: '超出 budget', en: 'Budget violation' }, { zh: '剩餘 margin', en: 'Remaining margin' }],
    hints: [{ zh: '先用 10-bit intermediate 做加法，避免 8-bit overflow。', en: 'Use a ten-bit intermediate sum to avoid eight-bit overflow.' }],
    starter: `module hbm_package_budget(input wire[7:0]ui_ps,input wire[7:0]flight_ps,input wire[7:0]skew_ps,input wire[7:0]margin_ps,output wire pass,output wire[9:0]used_ps,output wire[9:0]remaining_ps);assign pass=0;assign used_ps=0;assign remaining_ps=0;endmodule`,
    referenceSolution: `module hbm_package_budget(input wire[7:0]ui_ps,input wire[7:0]flight_ps,input wire[7:0]skew_ps,input wire[7:0]margin_ps,output wire pass,output wire[9:0]used_ps,output wire[9:0]remaining_ps);assign used_ps={2'b0,flight_ps}+{2'b0,skew_ps}+{2'b0,margin_ps};assign pass=used_ps<={2'b0,ui_ps};assign remaining_ps=pass?({2'b0,ui_ps}-used_ps):10'b0;endmodule`,
    testbench: `module tb;reg[7:0]ui=100,f=20,s=30,m=10;wire ok;wire[9:0]u,r;hbm_package_budget dut(ui,f,s,m,ok,u,r);${pass}initial begin #1;check(ok&&u==60&&r==40);f=40;s=30;m=30;#1;check(ok&&u==100&&r==0);m=31;#1;check(!ok&&u==101&&r==0);ui=8'hff;f=8'hff;s=8'hff;m=8'hff;#1;check(!ok&&u==765&&r==0);$display("@@PASS@@");$finish;end endmodule`,
  },
  {
    id: 'hbm-thermal-throttle', order: 25, track: 'hbm', difficulty: 'advanced', minutes: 45, points: 320,
    kind: 'build', judge: 'simulation', language: 'Verilog-2005',
    title: { zh: 'Thermal／Power Throttle Policy', en: 'Thermal/power throttle policy' },
    description: { zh: '把封裝或 stack 回報的四級 thermal state 轉成每個 window 可 issue 的 ACT budget，讓系統效能模型能量化降頻／節流影響。', en: 'Convert a four-level package/stack thermal state into an ACT issue budget per window so performance modeling can quantify throttling.' },
    specs: [{ zh: 'thermal 0/1/2/3 對應 budget 4/2/1/0。', en: 'thermal levels 0/1/2/3 map to budgets 4/2/1/0.' }, { zh: 'thermal>=2 時 alert=1；budget=0 表示停止新的 ACT，不代表停止 refresh。', en: 'alert is one at thermal>=2; budget zero blocks new ACT but not refresh.' }],
    testGroups: [{ zh: '四級 budget', en: 'Four budgets' }, { zh: 'alert threshold', en: 'Alert threshold' }],
    hints: [{ zh: '用完整 case 並給 default，避免 X 或保留值推導 latch。', en: 'Use a complete case with default to avoid latches on X/reserved values.' }],
    starter: `module hbm_thermal_policy(input wire[1:0]thermal_level,output reg[2:0]act_budget,output wire alert);assign alert=0;always @*act_budget=0;endmodule`,
    referenceSolution: `module hbm_thermal_policy(input wire[1:0]thermal_level,output reg[2:0]act_budget,output wire alert);assign alert=thermal_level>=2;always @*begin case(thermal_level)0:act_budget=4;1:act_budget=2;2:act_budget=1;default:act_budget=0;endcase end endmodule`,
    testbench: `module tb;reg[1:0]t;wire[2:0]b;wire a;hbm_thermal_policy dut(t,b,a);${pass}initial begin t=0;#1;check(b==4&&!a);t=1;#1;check(b==2&&!a);t=2;#1;check(b==1&&a);t=3;#1;check(b==0&&a);$display("@@PASS@@");$finish;end endmodule`,
  },
  {
    id: 'hbm-bandwidth-window', order: 26, track: 'hbm', difficulty: 'advanced', minutes: 60, points: 390,
    kind: 'build', judge: 'simulation', language: 'Verilog-2005',
    title: { zh: '實際 Throughput／Efficiency Counter', en: 'Actual throughput/efficiency counter' },
    description: { zh: '在固定觀測 window 內同時計算總 cycles 與成功 data beats，形成可由 bus width、frequency 與 utilization 回推的實際吞吐量證據。', en: 'Count total cycles and successful data beats in a fixed window, producing evidence for actual throughput derived from bus width, frequency, and utilization.' },
    specs: [{ zh: '每個 enable cycle 增加 cycles；beat_fire 同拍增加 beats。', en: 'Increment cycles on every enabled cycle and beats on each beat_fire.' }, { zh: 'window_end 時 snapshot 包含該拍事件，輸出 valid 一拍並清零下一個 window。', en: 'At window_end, the snapshot includes same-cycle events, pulses valid, and clears for the next window.' }],
    testGroups: [{ zh: 'same-cycle snapshot', en: 'Same-cycle snapshot' }, { zh: 'window reset', en: 'Window reset' }, { zh: 'idle beats', en: 'Idle beats' }],
    hints: [{ zh: 'snapshot 使用 count + 本拍事件；不要先清 counter 再讀舊值。', en: 'Snapshot count plus current events; do not clear counters before accounting for the current cycle.' }],
    starter: `module hbm_bw_counter(input wire clk,input wire rst_n,input wire enable,input wire beat_fire,input wire window_end,output reg valid,output reg[15:0]cycles,output reg[15:0]beats);reg[15:0]cycle_count,beat_count;always @(posedge clk)if(!rst_n)begin valid<=0;cycles<=0;beats<=0;cycle_count<=0;beat_count<=0;end endmodule`,
    referenceSolution: `module hbm_bw_counter(input wire clk,input wire rst_n,input wire enable,input wire beat_fire,input wire window_end,output reg valid,output reg[15:0]cycles,output reg[15:0]beats);reg[15:0]cycle_count,beat_count;always @(posedge clk)begin if(!rst_n)begin valid<=0;cycles<=0;beats<=0;cycle_count<=0;beat_count<=0;end else begin valid<=0;if(window_end)begin cycles<=cycle_count+(enable?1:0);beats<=beat_count+(beat_fire?1:0);valid<=1;cycle_count<=0;beat_count<=0;end else begin if(enable)cycle_count<=cycle_count+1'b1;if(beat_fire)beat_count<=beat_count+1'b1;end end end endmodule`,
    testbench: `module tb;reg clk=0,rst_n=0,en=0,b=0,e=0;wire v;wire[15:0]c,n;hbm_bw_counter dut(clk,rst_n,en,b,e,v,c,n);always #5 clk=~clk;${pass}initial begin repeat(2)@(posedge clk);rst_n=1;en=1;b=1;repeat(3)@(posedge clk);#1;b=0;@(posedge clk);#1;e=1;b=1;@(posedge clk);#1;e=0;b=0;check(v&&c==5&&n==4);@(posedge clk);#1;check(!v);e=1;@(posedge clk);#1;check(v&&c==2&&n==0);$display("@@PASS@@");$finish;end endmodule`,
  },
  {
    id: 'hbm-pim-qos-arbiter', order: 27, track: 'hbm', difficulty: 'capstone', minutes: 75, points: 500,
    kind: 'build', judge: 'simulation', language: 'Verilog-2005',
    title: { zh: 'Host／PIM／Refresh QoS Arbiter', en: 'Host/PIM/refresh QoS arbiter' },
    description: { zh: '整合一般 host traffic、PIM traffic 與 urgent refresh：維護最高優先；其餘兩者同時要求時 round-robin，避免 PIM 或 host 永久飢餓。', en: 'Arbitrate normal host traffic, PIM traffic, and urgent refresh. Maintenance has highest priority; host and PIM use round-robin when both request.' },
    specs: [{ zh: 'refresh_urgent 時只可 grant_refresh。', en: 'When refresh_urgent is high, only grant_refresh may assert.' }, { zh: 'host/pim 同時要求時交替；pointer 只在真正 grant 時更新。', en: 'Alternate when host and PIM request together; update the pointer only on an actual grant.' }],
    testGroups: [{ zh: 'refresh preemption', en: 'Refresh preemption' }, { zh: 'host/PIM fairness', en: 'Host/PIM fairness' }, { zh: 'one-hot grant', en: 'One-hot grant' }],
    hints: [{ zh: '用一個 turn bit 記錄下次雙方衝突要選誰；單方 request 也算真正 grant。', en: 'Use a turn bit to remember who wins the next tie; a sole request is also a real grant.' }],
    starter: `module hbm_pim_qos(input wire clk,input wire rst_n,input wire host_req,input wire pim_req,input wire refresh_urgent,output reg grant_host,output reg grant_pim,output reg grant_refresh);always @*begin grant_host=host_req;grant_pim=pim_req;grant_refresh=refresh_urgent;end endmodule`,
    referenceSolution: `module hbm_pim_qos(input wire clk,input wire rst_n,input wire host_req,input wire pim_req,input wire refresh_urgent,output reg grant_host,output reg grant_pim,output reg grant_refresh);reg turn;always @*begin grant_host=0;grant_pim=0;grant_refresh=0;if(refresh_urgent)grant_refresh=1;else if(host_req&&pim_req)begin if(turn)grant_pim=1;else grant_host=1;end else if(host_req)grant_host=1;else if(pim_req)grant_pim=1;end always @(posedge clk)begin if(!rst_n)turn<=0;else if(grant_host)turn<=1;else if(grant_pim)turn<=0;end endmodule`,
    testbench: `module tb;reg clk=0,rst_n=0,h=0,p=0,r=0;wire gh,gp,gr;hbm_pim_qos dut(clk,rst_n,h,p,r,gh,gp,gr);always #5 clk=~clk;${pass}initial begin repeat(2)@(posedge clk);rst_n=1;h=1;p=1;#1;check(gh&&!gp&&!gr);@(posedge clk);#1;check(!gh&&gp&&!gr);@(posedge clk);#1;check(gh&&!gp);r=1;#1;check(!gh&&!gp&&gr);@(posedge clk);#1;r=0;p=0;#1;check(gh&&!gp&&!gr);h=0;#1;check(!gh&&!gp&&!gr);$display("@@PASS@@");$finish;end endmodule`,
  },
];
