import type { Localized } from './challenges';
import { hbm4AdvancedReferences, hbm4AdvancedSpecs, type LabReference } from './hbm4-advanced-specs';

export type PortInfo = { name: string; direction: string; width: string };
export type TimingExample = { cycle: string; drive: Localized; expect: Localized };
export type LabSpec = {
  purpose: Localized;
  clocking: Localized;
  ports: Record<string, Localized>;
  algorithm: Localized[];
  priority: Localized[];
  example: TimingExample[];
  assumptions: Localized[];
};

const b = (zh: string, en: string): Localized => ({ zh, en });
const e = (cycle: string, zhDrive: string, enDrive: string, zhExpect: string, enExpect: string): TimingExample => ({ cycle, drive: b(zhDrive, enDrive), expect: b(zhExpect, enExpect) });
const spec = (purpose: Localized, clocking: Localized, ports: Record<string, Localized>, algorithm: Localized[], example: TimingExample[], priority: Localized[] = [], assumptions: Localized[] = []): LabSpec => ({ purpose, clocking, ports, algorithm, priority, example, assumptions });

const syncClock = b('所有狀態在 clk 上升緣更新；rst_n 是同步低有效 reset。組合輸出由「目前狀態」計算。', 'All state updates on the rising edge of clk; rst_n is a synchronous active-low reset. Combinational outputs use current state.');
const combinational = b('純組合模組：輸入改變後，同一模擬時間步內輸出必須穩定；沒有 clock 或內部狀態。', 'Purely combinational: outputs settle in the same simulation time step after inputs change; there is no clock or internal state.');
const resetPorts = { clk: b('模組時脈；只在上升緣提交狀態。', 'Module clock; state commits only on rising edges.'), rst_n: b('同步低有效 reset；在 clk 上升緣為 0 時清除所有狀態。', 'Synchronous active-low reset; clears all state when low at a rising edge.') };

export const labSpecs: Record<string, LabSpec> = {
  ...hbm4AdvancedSpecs,
  'dram-address-map': spec(
    b('建立 controller 的第一級位址解碼器，把 16-bit 線性 request address 唯一切成 column、bank、channel、row。輸出只描述目的地，不儲存資料也不發 DRAM command。', 'Build the controller’s first address decoder, uniquely slicing a 16-bit request address into column, bank, channel, and row. It selects a destination; it neither stores data nor issues a DRAM command.'),
    combinational,
    { addr: b('待解碼的 16-bit byte-address 教學值。', 'The 16-bit educational byte-address to decode.'), channel: b('addr[7:6]；選擇四個 channel 之一。', 'addr[7:6]; selects one of four channels.'), bank: b('addr[5:4]；選擇四個 bank 之一。', 'addr[5:4]; selects one of four banks.'), row: b('addr[15:8]；DRAM row index。', 'addr[15:8]; DRAM row index.'), column: b('addr[3:0]；row 內的 column offset。', 'addr[3:0]; column offset within the row.') },
    [b('不得重新排列或 XOR 位元；每個輸出直接 continuous-assign 到指定 slice。', 'Do not reorder or XOR bits; continuously assign every output to its specified slice.'), b('所有 16 個輸入位元必須恰好出現在一個輸出欄位，不能遺失或重複。', 'Every one of the 16 input bits must appear in exactly one output field.')],
    [e('T0', "addr = 16'hA53C", "addr = 16'hA53C", "row=A5、channel=0、bank=3、column=C", 'row=A5, channel=0, bank=3, column=C')],
    [], [b('這是刻意縮小的教學 mapping，不代表任何產品的 JEDEC 位址配置。', 'This reduced teaching map is not a JEDEC product address map.')],
  ),
  'dram-bank-fsm': spec(
    b('追蹤單一 bank 是否有 open row，並在命令進入 scheduler/issue path 前拒絕非法 ACT、RD、PRE。cmd_ok 是本拍合法性；row_open/open_row 是跨拍狀態。', 'Track whether one bank has an open row and reject illegal ACT, RD, or PRE before issue. cmd_ok is current-cycle legality; row_open/open_row are persistent state.'),
    syncClock,
    { ...resetPorts, cmd_valid: b('本拍有待檢查命令；為 0 時 cmd/cmd_row 不得改變狀態。', 'A command is present this cycle; when low, cmd/cmd_row cannot change state.'), cmd: b('2-bit opcode：0=ACT、1=RD、2=PRE、3=非法/保留。', '2-bit opcode: 0=ACT, 1=RD, 2=PRE, 3=illegal/reserved.'), cmd_row: b('ACT 要開啟的 row；RD/PRE 時不使用。', 'Row opened by ACT; ignored for RD/PRE.'), cmd_ok: b('組合合法性：cmd_valid=1 且目前 bank 狀態允許命令時為 1。', 'Combinational legality: high only for a valid command allowed by current bank state.'), row_open: b('狀態位：1 表示 bank 目前已有 open row。', 'State bit: one means the bank currently has an open row.'), open_row: b('最近一次合法 ACT 寫入的 row；非法命令不得改寫。', 'Row written by the last legal ACT; illegal commands must not overwrite it.') },
    [b('Closed bank：只允許 ACT；合法 ACT 在上升緣設 row_open=1、open_row=cmd_row。', 'Closed bank: only ACT is legal; a legal ACT sets row_open=1 and open_row=cmd_row at the edge.'), b('Open bank：允許 RD 與 PRE，不允許第二個 ACT。合法 PRE 在上升緣清除 row_open。', 'Open bank: RD and PRE are legal, a second ACT is not. A legal PRE clears row_open at the edge.'), b('只有 cmd_valid && cmd_ok 才能更新狀態。', 'State may update only when cmd_valid && cmd_ok.')],
    [e('C0', 'reset 後送 RD', 'Drive RD after reset', 'cmd_ok=0，row_open 保持 0', 'cmd_ok=0; row_open remains 0'), e('C1', "送 ACT，cmd_row=8'h42", "Drive ACT with cmd_row=8'h42", '邊緣前 cmd_ok=1；邊緣後 row_open=1、open_row=42', 'cmd_ok=1 before the edge; row_open=1 and open_row=42 after it'), e('C2', '送 PRE', 'Drive PRE', 'cmd_ok=1；邊緣後 row_open=0', 'cmd_ok=1; row_open=0 after the edge')],
    [b('Reset 優先於命令；同一拍只存在一個 cmd。', 'Reset has priority over commands; only one cmd exists per cycle.')],
  ),
  'dram-trcd-guard': spec(
    b('在 ACT 真正發出後建立 tRCD 等待窗；scheduler 只有在 rd_allowed=1 時才可選 RD。這個 block 不會自行發 RD。', 'Create a tRCD wait window after an ACT is actually issued; the scheduler may select RD only while rd_allowed is high. This block never issues RD itself.'),
    syncClock,
    { ...resetPorts, act_valid: b('本拍 ACT 已被 issue/接受；不是只有 candidate。', 'An ACT was actually issued/accepted this cycle, not merely considered.'), rd_allowed: b('目前是否已滿足 ACT→RD 最短等待；ACT 當拍必須為 0。', 'Whether the ACT-to-RD minimum wait has elapsed; must be low on the ACT cycle.') },
    [b('Reset 後沒有 pending delay，rd_allowed=1。', 'After reset there is no pending delay, so rd_allowed=1.'), b('act_valid=1 時載入 TRCD；其後每個上升緣非零減一，永不 underflow。', 'When act_valid=1, load TRCD; decrement once per later edge while nonzero, never underflow.'), b('rd_allowed = (counter==0) && !act_valid。', 'rd_allowed = (counter==0) && !act_valid.')],
    [e('C0', 'act_valid=1', 'act_valid=1', 'rd_allowed=0；edge 後 counter=3', 'rd_allowed=0; counter=3 after edge'), e('C1–C2', 'act_valid=0', 'act_valid=0', 'counter 依序 2、1；rd_allowed=0', 'counter becomes 2 then 1; rd_allowed=0'), e('C3', 'act_valid=0', 'act_valid=0', 'edge 後 counter=0，rd_allowed=1', 'counter=0 after edge; rd_allowed=1')],
    [b('新的 ACT 重新載入等待值，優先於 decrement。', 'A new ACT reloads the delay and has priority over decrement.')], [b('TRCD=3 是教學週期數；產品值由 speed bin 與 PHY 合約換算。', 'TRCD=3 is an educational cycle value; product values come from the speed bin and PHY contract.')],
  ),
  'dram-frfcfs-select': spec(
    b('在兩筆已通過 timing legality 的 request 中產生一個 one-hot grant。它只做效能政策，不負責判斷 DRAM 命令是否合法。', 'Choose a one-hot grant among two requests that already passed timing legality. This is performance policy, not DRAM command legality.'),
    combinational,
    { v0: b('request 0 有效。', 'Request 0 is valid.'), row0: b('request 0 的 target row。', 'Target row of request 0.'), age0: b('request 0 等待年齡；數值越大越老。', 'Wait age of request 0; larger is older.'), v1: b('request 1 有效。', 'Request 1 is valid.'), row1: b('request 1 的 target row。', 'Target row of request 1.'), age1: b('request 1 等待年齡；數值越大越老。', 'Wait age of request 1; larger is older.'), bank_open: b('共同 target bank 是否已有 open row。', 'Whether the common target bank has an open row.'), open_row: b('target bank 目前 open row。', 'Current open row of the target bank.'), g0: b('one-hot grant request 0。', 'One-hot grant for request 0.'), g1: b('one-hot grant request 1。', 'One-hot grant for request 1.') },
    [b('沒有 valid：g0=g1=0；只有一筆 valid：grant 該筆。', 'No valid request: no grant; one valid request: grant it.'), b('兩筆 valid：唯一 row hit 優先。兩者同為 hit 或 miss 時，age 較大者優先。', 'With both valid, a unique row hit wins. If both hit or both miss, larger age wins.'), b('hit 與 age 都相同時固定選 request 0，避免不確定輸出。', 'If hit and age tie, deterministically choose request 0.')],
    [e('T0', 'bank_open=1、open_row=22；req0 row=22 age=0，req1 row=33 age=255', 'bank_open=1, open_row=22; req0 row=22 age=0, req1 row=33 age=255', 'g0=1：row hit 高於 age', 'g0=1: row hit outranks age'), e('T1', '兩者皆 hit，age0=10、age1=10', 'Both hit, age0=10, age1=10', 'g0=1：固定 tie-break', 'g0=1: deterministic tie-break')],
    [b('valid → row-hit → age → index 0 tie-break。', 'valid → row hit → age → index-0 tie-break.')], [b('輸入 request 已通過 timing/refresh mask；本題不處理 starvation 上界。', 'Input requests already passed timing/refresh masks; this lab does not bound starvation.')],
  ),
  'dram-refresh-deadline': spec(
    b('計算距離上次 refresh 的 age，在 deadline 前兩拍要求 scheduler 插入 refresh；若超過 deadline，鎖住 overdue 供 CSR/IRQ 除錯。', 'Track age since the last refresh, request refresh two cycles before the deadline, and latch overdue for CSR/IRQ debug if the deadline is missed.'),
    syncClock,
    { ...resetPorts, tick: b('為 1 時 age 前進一個 controller cycle；為 0 時凍結。', 'Advances age by one controller cycle when high; freezes it when low.'), refresh_issued: b('本拍 refresh 命令真的被接受；在 edge 將 age 清零。', 'A refresh command was actually accepted this cycle; clears age at the edge.'), must_refresh: b('組合預警：age >= MAX_AGE-2。', 'Combinational warning: age >= MAX_AGE-2.'), overdue: b('Sticky error；miss deadline 後保持 1，只有 reset 清除。', 'Sticky error; remains high after a missed deadline until reset.') },
    [b('refresh_issued 優先，將 age 清零，即使 tick 同時為 1。', 'refresh_issued has priority and clears age even when tick is also high.'), b('否則 tick && age<MAX_AGE 時 age+1；到 MAX_AGE 後飽和。', 'Otherwise tick increments age while below MAX_AGE; it saturates at MAX_AGE.'), b('若 tick && !refresh_issued && age>=MAX_AGE-1，edge 後 overdue=1。', 'If tick && !refresh_issued && age>=MAX_AGE-1, overdue becomes high after the edge.')],
    [e('C6', 'MAX_AGE=8、age=6', 'MAX_AGE=8, age=6', 'must_refresh=1、overdue=0', 'must_refresh=1, overdue=0'), e('C8', '持續 tick 且未 refresh', 'Continue ticking without refresh', 'overdue=1 並保持', 'overdue=1 and sticky'), e('任意', 'refresh_issued=1', 'refresh_issued=1', 'edge 後 age=0、must_refresh=0；overdue 不清除', 'age=0 and must_refresh=0 after edge; overdue remains')],
    [b('Reset > refresh_issued > tick increment。', 'Reset > refresh_issued > tick increment.')],
  ),
  'dram-write-drain': spec(
    b('以高低水位 hysteresis 控制 scheduler 的 read-priority/write-drain 模式，避免 write queue 深度在單一 threshold 附近造成每拍 R↔W 切換。', 'Use high/low-watermark hysteresis to select read-priority or write-drain mode, avoiding cycle-by-cycle R↔W thrashing near one threshold.'),
    syncClock,
    { ...resetPorts, depth: b('目前 write queue 使用量，0–15。', 'Current write-queue occupancy, 0–15.'), drain: b('狀態輸出；1 要求 scheduler 優先排空 writes。', 'State output; one asks the scheduler to prioritize draining writes.') },
    [b('Reset 後 drain=0。若 drain=0 且 depth>=HI，edge 後進入 drain。', 'Reset sets drain=0. If drain=0 and depth>=HI, enter drain after the edge.'), b('drain=1 時，即使 depth 降到 HI 以下仍保持；只有 depth<=LO 才離開。', 'While draining, remain active below HI and exit only when depth<=LO.'), b('LO < depth < HI 時保持先前狀態。', 'Hold prior state when LO < depth < HI.')],
    [e('C0', 'depth=5、HI=6', 'depth=5, HI=6', 'drain=0', 'drain=0'), e('C1', 'depth=6', 'depth=6', 'edge 後 drain=1', 'drain=1 after edge'), e('C2–C3', 'depth=5 再到 3', 'depth=5 then 3', 'drain 保持 1', 'drain remains 1'), e('C4', 'depth=2、LO=2', 'depth=2, LO=2', 'edge 後 drain=0', 'drain=0 after edge')],
    [b('Reset 優先；進入與離開條件互斥。', 'Reset has priority; enter and exit conditions are mutually exclusive.')],
  ),
  'dram-timing-wheel': spec(
    b('用自由運行 timestamp 與 deadline 集中表示 ACT→RD、RD→PRE 兩條命令間距；輸出只是 legality mask，不會自行排程。', 'Use a free-running timestamp and deadlines to represent ACT→RD and RD→PRE spacing centrally. Outputs are legality masks, not schedulers.'),
    syncClock,
    { ...resetPorts, act: b('本拍 ACT 已 issue；建立 rd_deadline=now+3。', 'An ACT issued this cycle; sets rd_deadline=now+3.'), rd: b('本拍 RD 已 issue；建立 pre_deadline=now+4。', 'An RD issued this cycle; sets pre_deadline=now+4.'), rd_ok: b('已有 ACT 且 now 已到 rd_deadline，並排除 ACT 當拍。', 'High after an ACT once now reaches rd_deadline, excluding the ACT cycle.'), pre_ok: b('已有 RD 且 now 已到 pre_deadline，並排除 RD 當拍。', 'High after an RD once now reaches pre_deadline, excluding the RD cycle.') },
    [b('now 每個非 reset 上升緣加一，自然以 16-bit 回繞。', 'now increments every non-reset rising edge and naturally wraps at 16 bits.'), b('ACT/RD 只在真的 issue 時寫入各自 deadline 與 valid bit。', 'ACT/RD write their deadlines and valid bits only on actual issue.'), b('以 signed(now-deadline)>=0 判斷到期，支援半個計數範圍內的回繞。', 'Use signed(now-deadline)>=0 for expiry, tolerating wrap within half the counter range.')],
    [e('C0', 'act=1、now=N', 'act=1, now=N', 'rd_ok=0；rd_deadline=N+3', 'rd_ok=0; rd_deadline=N+3'), e('C3', 'act=0、now=N+3', 'act=0, now=N+3', 'rd_ok=1', 'rd_ok=1'), e('C4', 'rd=1、now=M', 'rd=1, now=M', 'pre_ok=0；pre_deadline=M+4', 'pre_ok=0; pre_deadline=M+4')],
    [b('Reset > timestamp advance；ACT 與 RD 更新不同 deadline，可同拍定義。', 'Reset > timestamp advance; ACT and RD update separate deadlines and may be defined in one cycle.')], [b('所有 delay 都遠小於 32768 cycles，才能安全使用 16-bit signed difference。', 'All delays are far below 32768 cycles so the 16-bit signed-difference method is safe.')],
  ),
  'dram-command-generator': spec(
    b('將一筆讀 request 與 bank/timing 狀態轉成下一個必要命令。它每拍最多選 NOP、ACT、RD、PRE 之一；bank state 由外部在命令被接受後更新。', 'Translate one read request plus bank/timing state into the next required command. Select at most one of NOP, ACT, RD, or PRE per cycle; external logic updates bank state after acceptance.'),
    combinational,
    { req_valid: b('目前有一筆待服務 read request。', 'A read request is waiting for service.'), req_row: b('request 的 target row。', 'Target row of the request.'), row_open: b('target bank 是否 open。', 'Whether the target bank is open.'), open_row: b('target bank 目前 open row。', 'Current open row of the target bank.'), act_ok: b('timing layer 允許 ACT。', 'Timing layer permits ACT.'), rd_ok: b('timing layer 允許 RD。', 'Timing layer permits RD.'), pre_ok: b('timing layer 允許 PRE。', 'Timing layer permits PRE.'), cmd_valid: b('本拍有命令輸出。', 'A command is emitted this cycle.'), cmd: b('0=NOP、1=ACT、2=RD、3=PRE。', '0=NOP, 1=ACT, 2=RD, 3=PRE.') },
    [b('req_valid=0：輸出 NOP 且 cmd_valid=0。', 'If req_valid=0, output NOP with cmd_valid=0.'), b('Bank closed：act_ok 才輸出 ACT。Bank open 且 row hit：rd_ok 才輸出 RD。', 'If bank is closed, emit ACT only when act_ok. If open with a row hit, emit RD only when rd_ok.'), b('Bank open 且 row conflict：pre_ok 才輸出 PRE；等待外部關 bank 後下一拍再考慮 ACT。', 'If open with a row conflict, emit PRE only when pre_ok; wait for external state closure before considering ACT later.')],
    [e('T0', 'req_valid=1、row_open=0、act_ok=1', 'req_valid=1, row_open=0, act_ok=1', 'cmd_valid=1、cmd=ACT', 'cmd_valid=1, cmd=ACT'), e('T1', 'row_open=1、req_row=open_row、rd_ok=1', 'row_open=1, req_row=open_row, rd_ok=1', 'cmd=RD', 'cmd=RD'), e('T2', 'row_open=1、req_row!=open_row、pre_ok=1', 'row_open=1, req_row!=open_row, pre_ok=1', 'cmd=PRE', 'cmd=PRE')],
    [b('狀態分支 closed > row-hit > row-conflict；各分支再由對應 *_ok gate。', 'State branches are closed > row hit > row conflict; each is gated by its matching *_ok.')],
  ),
  'hbm-pseudo-channel-map': spec(
    b('將 20-bit 教學位址分散到 HBM 的 channel→pseudo-channel→bank-group→bank 階層。它是 ingress steering，不處理 queue、timing 或實體 microbump。', 'Steer a 20-bit educational address through the HBM channel→pseudo-channel→bank-group→bank hierarchy. This is ingress routing, not queueing, timing, or physical microbumps.'),
    combinational,
    { addr: b('待解碼的 20-bit 線性位址。', 'The 20-bit linear address to decode.'), channel: b('addr[11:9]，8 個 channel 之一。', 'addr[11:9], one of eight channels.'), pc: b('addr[8]，channel 內兩個 pseudo-channel 之一。', 'addr[8], one of two pseudo-channels in a channel.'), bg: b('addr[7:6]，bank group。', 'addr[7:6], bank group.'), bank: b('addr[5:4]，bank-group 內 bank。', 'addr[5:4], bank within the group.'), row: b('addr[19:12]，row index。', 'addr[19:12], row index.'), column: b('addr[3:0]，column offset。', 'addr[3:0], column offset.') },
    [b('直接切割 column[3:0]、bank[5:4]、BG[7:6]、PC[8]、channel[11:9]、row[19:12]。', 'Directly slice column[3:0], bank[5:4], BG[7:6], PC[8], channel[11:9], and row[19:12].'), b('輸出串接 {row,channel,pc,bg,bank,column} 必須等於 addr。', 'Concatenating {row,channel,pc,bg,bank,column} must reproduce addr.')],
    [e('T0', "addr=20'hA55AA", "addr=20'hA55AA", '輸出各欄位立即更新，串接值仍為 A55AA', 'All fields update immediately and concatenate back to A55AA')],
    [], [b('這是縮小的 teaching profile，實際 mapping 由產品配置決定。', 'This is a reduced teaching profile; the product configuration defines the real map.')],
  ),
  'hbm-bankgroup-tccd': spec(
    b('追蹤上一個真正發出的 column command 與其 bank group，對候選命令套用 same-BG=4、different-BG=2 的最小間距。', 'Track the last issued column command and its bank group, applying minimum spacing of 4 cycles for same-BG and 2 for different-BG candidates.'),
    syncClock,
    { ...resetPorts, issue: b('本拍 column command 真的被接受；觸發 history 更新。', 'A column command was actually accepted; updates history.'), issue_bg: b('被接受命令的 bank group。', 'Bank group of the accepted command.'), candidate_bg: b('scheduler 正在檢查的候選 bank group。', 'Bank group of the candidate being checked.'), allowed: b('候選相對於 last_bg/age 是否符合 tCCD。', 'Whether the candidate satisfies tCCD relative to last_bg/age.') },
    [b('Reset 後 last_valid=0，因此第一筆永遠 allowed。', 'After reset last_valid=0, so the first command is always allowed.'), b('issue edge 保存 issue_bg，並將 age 設為 1；沒有 issue 時 age 飽和增加。', 'On issue, save issue_bg and set age=1; without issue, increment age with saturation.'), b('candidate_bg==last_bg 要 age>=4；不同 BG 要 age>=2。allowed 不會自行 issue。', 'Same BG requires age>=4; different BG requires age>=2. allowed never issues by itself.')],
    [e('C0', 'issue=1、issue_bg=1', 'issue=1, issue_bg=1', 'edge 後 last_bg=1、age=1', 'last_bg=1 and age=1 after edge'), e('C1', 'candidate_bg=2', 'candidate_bg=2', 'allowed=0', 'allowed=0'), e('C2', 'candidate_bg=2', 'candidate_bg=2', 'age=2，allowed=1', 'age=2, allowed=1'), e('C4', 'candidate_bg=1', 'candidate_bg=1', 'age=4，allowed=1', 'age=4, allowed=1')],
    [b('issue reload 優先於 age increment。', 'Issue reload has priority over age increment.')],
  ),
  'hbm-hierarchical-arbiter': spec(
    b('用 4-entry round-robin 代表 HBM channel 內的 pseudo-channel winner 仲裁。req 已是各 PC 本地仲裁結果；本模組只選全域一筆。', 'Use a four-entry round-robin arbiter for pseudo-channel winners within an HBM channel. Each req is already a local PC winner; this block chooses one global issue.'),
    syncClock,
    { ...resetPorts, req: b('四個 PC 的可發請求 bitmap；bit i=1 表示 PC i 有合法候選。', 'Ready bitmap for four PCs; bit i marks a legal candidate from PC i.'), grant: b('one-hot winner；沒有 req 時為 0000。', 'One-hot winner; 0000 when no request exists.') },
    [b('ptr 指向下一次掃描起點；依 ptr、ptr+1、ptr+2、ptr+3 循環找第一個 req=1。', 'ptr is the next scan start; search ptr, ptr+1, ptr+2, ptr+3 cyclically for the first asserted req.'), b('組合 grant 最多一位；只有 grant 非零的上升緣才將 ptr 移到 winner+1。', 'Combinational grant is at most one-hot; update ptr to winner+1 only on a granted edge.'), b('Reset ptr=0；idle 不移動 ptr。', 'Reset ptr=0; idle holds ptr.')],
    [e('C0', 'ptr=0、req=1111', 'ptr=0, req=1111', 'grant=0001；edge 後 ptr=1', 'grant=0001; ptr=1 after edge'), e('C1', 'req=1111', 'req=1111', 'grant=0010；edge 後 ptr=2', 'grant=0010; ptr=2 after edge'), e('C2', 'req=1010、ptr=2', 'req=1010, ptr=2', '掃描 2→3，grant=1000', 'scan 2→3, grant=1000')],
    [b('循環距離最短者優先；同拍只授權一個 PC。', 'The shortest cyclic distance wins; only one PC is granted per cycle.')],
  ),
  'hbm-refresh-domain': spec(
    b('為四個 pseudo-channel 建立互相獨立的三拍 refresh busy window。某一 PC refresh 時，只阻擋該 PC，不凍結整個 HBM channel。', 'Create independent three-cycle refresh-busy windows for four pseudo-channels. Refreshing one PC blocks only that PC, not the entire HBM channel.'),
    syncClock,
    { ...resetPorts, ref_start: b('one-hot 或 multi-hot refresh 啟動；bit i 在本拍開始 PC i 的 3-cycle busy。', 'One- or multi-hot refresh starts; bit i starts a three-cycle busy window for PC i.'), cmd_allowed: b('逐 PC 命令允許 bitmap；ref_start 當拍及 counter 非零時對應 bit=0。', 'Per-PC command-allow bitmap; a bit is low on ref_start and while its counter is nonzero.') },
    [b('每個 PC 有獨立 2-bit counter。ref_start[i] 時載入 3。', 'Each PC owns an independent 2-bit counter loaded with 3 on ref_start[i].'), b('沒有新的 ref_start 且 counter 非零時每拍減一。', 'Without a new ref_start, decrement a nonzero counter each cycle.'), b('cmd_allowed[i] = (counter[i]==0) && !ref_start[i]。', 'cmd_allowed[i] = (counter[i]==0) && !ref_start[i].')],
    [e('C0', 'ref_start=0010', 'ref_start=0010', 'cmd_allowed=1101；PC1 counter 載入 3', 'cmd_allowed=1101; PC1 counter loads 3'), e('C1', 'ref_start=1000', 'ref_start=1000', 'PC1 與 PC3 同時 blocked；PC0/2 allowed', 'PC1 and PC3 blocked; PC0/2 allowed'), e('C4', '無新 refresh', 'No new refresh', '兩個 domain 各依自己的起始時間釋放', 'Each domain releases according to its own start time')],
    [b('同一 PC 的新 ref_start 重新載入 3，優先於 decrement。', 'A new ref_start for a PC reloads 3 and has priority over decrement.')],
  ),
  'hbm-channel-capstone': spec(
    b('建立一個可複製到 32-channel stack 的 channel issue slice。兩個 pseudo-channel 的 row/column 路徑各自通過 legality 與 round-robin，正常模式可同拍 dual-issue；maintenance request 則先 drain，再取得唯一 command slot。', 'Build one channel-issue slice that can replicate across a 32-channel stack. Row and column paths for two pseudo-channels pass independent legality and round-robin selection, allowing normal dual issue; maintenance first drains, then owns the command slot.'),
    syncClock,
    { ...resetPorts, row_valid: b('PC[1:0] 的 row-command candidates。', 'Row-command candidates for PC[1:0].'), row_timing_ok: b('每個 row candidate 已通過 bank state、tRRD/tFAW、refresh 等 legality。', 'Each row candidate passed bank state, tRRD/tFAW, refresh, and other legality checks.'), col_valid: b('PC[1:0] 的 column-command candidates。', 'Column-command candidates for PC[1:0].'), col_timing_ok: b('每個 column candidate 已通過 row hit、tRCD/tCCD/turnaround 等 legality。', 'Each column candidate passed row-hit, tRCD/tCCD/turnaround, and other legality checks.'), maintenance_valid: b('REF/RFM/DRFM/MRS/power 等 maintenance transaction 要求 drain 並取得 command ownership。', 'A REF/RFM/DRFM/MRS/power maintenance transaction requests drain and command ownership.'), channel_quiescent: b('兩個 PC 的 queue/outstanding/command pipeline 都已排空。', 'Both PCs have drained queues, outstanding work, and command pipelines.'), phy_ready: b('PHY adapter 本拍可接受完整 command bundle。', 'The PHY adapter can accept the complete command bundle this cycle.'), row_grant: b('row path 的 one-hot PC winner；0 表示沒有 row issue。', 'One-hot PC winner for the row path; zero means no row issue.'), col_grant: b('column path 的 one-hot PC winner；可與 row_grant 同拍。', 'One-hot PC winner for the column path; may coincide with row_grant.'), maint_grant: b('maintenance_valid&&channel_quiescent&&phy_ready；取得唯一 maintenance commit。', 'maintenance_valid&&channel_quiescent&&phy_ready; the unique maintenance commit.') },
    [b('row_eligible=row_valid&row_timing_ok；col_eligible=col_valid&col_timing_ok。兩條路徑各有自己的 1-bit round-robin pointer。', 'row_eligible=row_valid&row_timing_ok and col_eligible=col_valid&col_timing_ok. Each path has an independent one-bit round-robin pointer.'), b('maintenance_valid=0 且 phy_ready=1 時，row/column 各選最多一個 PC；兩者可同拍 fire。', 'When maintenance_valid=0 and phy_ready=1, row and column independently select at most one PC and may fire together.'), b('maintenance_valid=1 時，所有 normal grants=0；只有 channel_quiescent&&phy_ready 才 maint_grant=1。', 'When maintenance_valid=1, all normal grants are zero; maint_grant requires channel_quiescent&&phy_ready.'), b('pointer 只在對應 grant 真正成立的 edge 前進；PHY stall 或 maintenance drain 時保持。', 'Each pointer advances only on its actual grant edge and holds during PHY stalls or maintenance drain.')],
    [e('C0', '兩條 valid/timing 都=11、pointer 都=0、phy_ready=1', 'both valid/timing vectors=11, both pointers=0, phy_ready=1', 'row_grant=01、col_grant=01；edge 後兩 pointer=1', 'row_grant=01 and col_grant=01; both pointers become one'), e('C1', '條件不變', 'conditions unchanged', 'row_grant=10、col_grant=10', 'row_grant=10 and col_grant=10'), e('M0', 'maintenance_valid=1、channel_quiescent=0', 'maintenance_valid=1, channel_quiescent=0', '所有 grant=0，等待 drain', 'all grants=0 while draining'), e('M1', 'channel_quiescent=1、phy_ready=1', 'channel_quiescent=1, phy_ready=1', 'maint_grant=1；normal grants 仍為 0', 'maint_grant=1; normal grants remain zero')],
    [b('Reset > maintenance exclusion > PHY readiness > row/column legality > independent policy。', 'Reset > maintenance exclusion > PHY readiness > row/column legality > independent policy.')],
    [b('此 capstone 接收已解碼的 abstract candidates；實際 command encoding、DQ data path、training 與 electrical timing 位於 adapter/PHY。', 'This capstone accepts decoded abstract candidates; actual command encoding, DQ datapath, training, and electrical timing live in the adapter/PHY.')],
  ),
  'lpddr-power-sequence': spec(
    b('控制 LPDDR power-down 的安全數位順序：先停止/排空流量，再 gate clock、assert isolation、關 power；喚醒時反向恢復。', 'Control a safe LPDDR power-down sequence: stop/drain traffic, gate clock, assert isolation, power off, then reverse safely on wake.'),
    syncClock,
    { ...resetPorts, request_sleep: b('要求進入 sleep；只在 IDLE 採樣。', 'Request sleep; sampled in IDLE.'), request_wake: b('要求離開 SLEEP。', 'Request wake from SLEEP.'), busy: b('controller 仍有 outstanding 工作；為 1 不得進 isolation/power-off。', 'Controller still has outstanding work; isolation/power-off is forbidden while high.'), pgood: b('外部 power domain 已穩定的同步狀態。', 'Synchronized status that the external power domain is stable.'), gate_clk: b('要求 clock-gating；1 表示關閉受控時脈。', 'Clock-gating request; one means gate the controlled clock.'), isolation: b('要求 isolation cells clamp 跨 power-domain 訊號。', 'Request isolation cells to clamp cross-domain signals.'), power_on: b('邏輯 power-domain enable；0 表示 domain off。', 'Logical power-domain enable; zero means off.'), in_sleep: b('對 firmware/status 表示已完成 sleep entry。', 'Status to firmware indicating completed sleep entry.') },
    [b('狀態順序 IDLE→DRAIN→ISO→SLEEP→PUP→RESTORE→IDLE。', 'State order is IDLE→DRAIN→ISO→SLEEP→PUP→RESTORE→IDLE.'), b('DRAIN 等到 busy=0；ISO 一拍先 gate+isolate；SLEEP 才 power_on=0。', 'DRAIN waits for busy=0; ISO gates and isolates for one cycle; only SLEEP powers off.'), b('request_wake 使 SLEEP→PUP，先 power_on=1 且保持 isolation；pgood 後 RESTORE 解 isolation，再下一拍開 clock。', 'request_wake moves SLEEP→PUP, powering on while isolated; after pgood, RESTORE removes isolation, then the next cycle ungates the clock.')],
    [e('C0', 'IDLE、request_sleep=1、busy=1', 'IDLE, request_sleep=1, busy=1', '進 DRAIN；power 仍 on', 'enter DRAIN; power remains on'), e('C2', 'DRAIN、busy=0', 'DRAIN, busy=0', '進 ISO：gate_clk=1、isolation=1、power_on=1', 'enter ISO: gate_clk=1, isolation=1, power_on=1'), e('C3', 'ISO', 'ISO', '進 SLEEP：power_on=0、in_sleep=1', 'enter SLEEP: power_on=0, in_sleep=1'), e('Wake', 'request_wake=1，之後 pgood=1', 'request_wake=1, then pgood=1', 'PUP 保持 isolate；RESTORE 解 isolate；最後回 IDLE', 'PUP stays isolated; RESTORE removes isolation; finally return IDLE')],
    [b('Reset > state transition；request_sleep 只在 IDLE 有效，request_wake 只在 SLEEP 有效。', 'Reset > state transition; request_sleep matters only in IDLE and request_wake only in SLEEP.')],
  ),
  'lpddr-init-sequencer': spec(
    b('將 LPDDR 初始化抽象為可驗證的數位脈衝序列：MR0→MR1→ZQ→training request→等待 training done→ready。', 'Abstract LPDDR initialization as a verifiable digital pulse sequence: MR0→MR1→ZQ→training request→wait for training done→ready.'),
    syncClock,
    { ...resetPorts, start: b('從 idle 啟動一次初始化。', 'Starts one initialization from idle.'), train_done: b('PHY 回報 training 完成；只在等待狀態採樣。', 'PHY reports training complete; sampled only in the wait state.'), mr0: b('一拍 mode-register-0 programming strobe。', 'One-cycle mode-register-0 programming strobe.'), mr1: b('一拍 mode-register-1 programming strobe。', 'One-cycle mode-register-1 programming strobe.'), zq: b('一拍 ZQ calibration request strobe。', 'One-cycle ZQ-calibration request strobe.'), train_req: b('一拍 PHY training request。', 'One-cycle PHY-training request.'), ready: b('Sticky 狀態：初始化完成，可開放正常 traffic。', 'Sticky status: initialization complete and normal traffic may start.') },
    [b('狀態 I→M0→M1→Z→T→W→R；每個 action output 只由對應 state decode。', 'States I→M0→M1→Z→T→W→R; each action output decodes from exactly one state.'), b('W 可停留任意週期直到 train_done=1；R 自保持 ready=1。', 'W may wait indefinitely for train_done; R self-holds ready=1.'), b('start 在非 idle 狀態不得重啟或打亂序列。', 'start outside idle must not restart or disturb the sequence.')],
    [e('C0', 'I 且 start=1', 'I with start=1', 'edge 後 M0，mr0=1', 'M0 after edge, mr0=1'), e('C1–C3', '無額外輸入', 'No extra input', 'mr1、zq、train_req 各依序一拍', 'mr1, zq, and train_req pulse one cycle each'), e('C4…', 'train_done=0', 'train_done=0', '所有 strobe=0、ready=0，停在 W', 'all strobes=0, ready=0, remain in W'), e('Done', 'train_done=1', 'train_done=1', '下一拍 ready=1 並保持', 'ready=1 next cycle and remains high')],
    [b('Reset 優先；其餘依 state 單向前進。', 'Reset has priority; otherwise the state advances monotonically.')], [b('實際 MR 值、等待時間與 training 演算法位於產品設定/PHY。', 'Actual MR values, delays, and training algorithms belong to product configuration/PHY.')],
  ),
  'lpddr-dvfs-quiesce': spec(
    b('在改變 LPDDR 頻率前關閉新 request admission、等待 outstanding 歸零，再向 PHY 發出 change request；完成後才重新接單。', 'Before changing LPDDR frequency, close request admission, wait for outstanding work to drain, then request a PHY change; reopen only after completion.'),
    syncClock,
    { ...resetPorts, dvfs_req: b('要求開始一次 DVFS transaction；只在 RUN 採樣。', 'Requests one DVFS transaction; sampled in RUN.'), outstanding: b('已接受但尚未完成的 transaction 數；必須到 0 才能改頻。', 'Count of accepted but incomplete transactions; must reach zero before changing frequency.'), phy_done: b('PHY/clock manager 回報頻率切換完成。', 'PHY/clock manager reports frequency change complete.'), accept_enable: b('frontend admission gate；只有 RUN 為 1。', 'Frontend admission gate; high only in RUN.'), phy_change: b('對 PHY 的 level request；整個 CHANGE 狀態保持 1。', 'Level request to the PHY; held high throughout CHANGE.'), done: b('切換完成的一拍 pulse。', 'One-cycle completion pulse.') },
    [b('RUN 收到 dvfs_req 後進 DRAIN，accept_enable 立即在新 state 變 0。', 'RUN receiving dvfs_req enters DRAIN; accept_enable becomes low in the new state.'), b('DRAIN 等 outstanding==0，再進 CHANGE 並將 phy_change=1。', 'DRAIN waits for outstanding==0, then enters CHANGE and asserts phy_change.'), b('CHANGE 等 phy_done；收到後回 RUN 並 pulse done 一拍。', 'CHANGE waits for phy_done; then returns to RUN and pulses done for one cycle.')],
    [e('C0', 'RUN、dvfs_req=1、outstanding=3', 'RUN, dvfs_req=1, outstanding=3', 'edge 後 DRAIN、accept_enable=0', 'DRAIN after edge, accept_enable=0'), e('C1–C2', 'outstanding>0', 'outstanding>0', 'phy_change=0，繼續 drain', 'phy_change=0, continue draining'), e('C3', 'outstanding=0', 'outstanding=0', 'edge 後 CHANGE、phy_change=1', 'CHANGE after edge, phy_change=1'), e('C4', 'phy_done=1', 'phy_done=1', 'edge 後 RUN、accept_enable=1、done=1 一拍', 'RUN after edge, accept_enable=1, done pulses')],
    [b('Reset > RUN request；CHANGE 中 phy_done 才能結束。', 'Reset > RUN request; only phy_done ends CHANGE.')],
  ),
  'lpddr-controller-capstone': spec(
    b('用兩條明確合約整合 LPDDR controller：req_ready 控制「能否接收新 request」，cmd_issue 控制「既有 queue 能否向 PHY 發命令」。', 'Integrate an LPDDR controller with two explicit contracts: req_ready controls admission of a new request, while cmd_issue controls issue of queued work to the PHY.'),
    combinational,
    { init_ready: b('初始化/training 已完成。', 'Initialization/training is complete.'), quiesce: b('DVFS/maintenance 正在停止 traffic。', 'DVFS/maintenance is quiescing traffic.'), sleeping: b('memory/controller 正在低功耗狀態。', 'Memory/controller is in low power.'), queue_full: b('request queue 無空位。', 'Request queue has no free entry.'), queue_empty: b('request queue 沒有待發命令。', 'Request queue has no pending command.'), timing_ok: b('queue head 的 DRAM timing 合法。', 'DRAM timing is legal for the queue head.'), phy_ready: b('PHY command interface 可接受一筆。', 'PHY command interface can accept one item.'), req_ready: b('frontend 可在本拍接受 request。', 'Frontend may accept a request this cycle.'), cmd_issue: b('controller 可在本拍提交 queue head 到 PHY。', 'Controller may commit the queue head to PHY this cycle.') },
    [b('operational = init_ready && !quiesce && !sleeping。', 'operational = init_ready && !quiesce && !sleeping.'), b('req_ready = operational && !queue_full。', 'req_ready = operational && !queue_full.'), b('cmd_issue = operational && !queue_empty && timing_ok && phy_ready。queue_full 不阻擋既有資料 issue。', 'cmd_issue = operational && !queue_empty && timing_ok && phy_ready. queue_full does not block issue of existing work.')],
    [e('T0', 'init_ready=1、非 quiesce/sleep、queue 未滿且非空、timing/PHY ready', 'init_ready=1, not quiesced/asleep, queue not full or empty, timing/PHY ready', 'req_ready=1、cmd_issue=1', 'req_ready=1, cmd_issue=1'), e('T1', 'queue_full=1 但 queue 非空且可發', 'queue_full=1 but queue has legal work', 'req_ready=0、cmd_issue=1', 'req_ready=0, cmd_issue=1'), e('T2', 'quiesce=1', 'quiesce=1', '兩者皆 0', 'both outputs are 0')],
    [b('init/power/DVFS operational gate 是最外層；admission 與 issue 再各自檢查資源。', 'The init/power/DVFS operational gate is outermost; admission and issue then check their own resources.')],
  ),
  'gddr-turnaround-guard': spec(
    b('記錄上一筆已發出的資料方向，對下一個 candidate 套用不對稱 R→W=2、W→R=3 dead cycles；同方向可連續。', 'Remember the last issued data direction and apply asymmetric dead time of R→W=2 and W→R=3 cycles to the next candidate; same-direction traffic may continue.'),
    syncClock,
    { ...resetPorts, issue: b('本拍資料命令真的被接受。', 'A data command was actually accepted this cycle.'), issue_is_write: b('被接受命令方向：1=write、0=read。', 'Direction of accepted command: 1=write, 0=read.'), candidate_is_write: b('目前 scheduler candidate 方向。', 'Direction of the current scheduler candidate.'), allowed: b('相對於最後一次 issue，candidate 是否滿足 turnaround。', 'Whether the candidate satisfies turnaround relative to the last issue.') },
    [b('Reset 後 valid=0，第一筆任何方向都 allowed。', 'After reset valid=0, so the first command in either direction is allowed.'), b('issue edge 保存方向並將 age=1；idle 時 age 飽和增加。', 'On issue, save direction and set age=1; increment age with saturation while idle.'), b('同方向 allowed=1；last read→candidate write 要 age>=2；last write→candidate read 要 age>=3。', 'Same direction is allowed; last read→candidate write requires age>=2; last write→candidate read requires age>=3.')],
    [e('C0', 'issue read', 'Issue a read', 'edge 後 last_w=0、age=1', 'last_w=0, age=1 after edge'), e('C1', 'candidate write', 'Candidate write', 'allowed=0', 'allowed=0'), e('C2', 'candidate write', 'Candidate write', 'age=2、allowed=1', 'age=2, allowed=1'), e('W→R', 'write 後 candidate read', 'Candidate read after a write', '必須等到 age=3', 'must wait until age=3')],
    [b('issue reload 優先於 age increment；candidate 不更新任何狀態。', 'Issue reload has priority over age increment; candidates never update state.')],
  ),
  'gddr-command-parity': spec(
    b('在 GDDR command/address 邏輯路徑產生偶同位元，並在接收/監視路徑只對有效碼字檢查 parity error。', 'Generate even parity on the logical GDDR command/address path and check parity errors only for valid received codewords.'),
    combinational,
    { tx_cmd: b('16-bit 待傳 command/address 教學碼字。', '16-bit educational command/address codeword to transmit.'), tx_parity: b('使 {tx_cmd,tx_parity} 的 XOR 為 0 的偶同位元。', 'Even parity bit making XOR of {tx_cmd,tx_parity} equal zero.'), rx_valid: b('rx_cmd/rx_parity 本拍有效。', 'rx_cmd/rx_parity are valid this cycle.'), rx_cmd: b('接收到的 16-bit codeword。', 'Received 16-bit codeword.'), rx_parity: b('隨 codeword 接收的 parity bit。', 'Parity bit received with the codeword.'), rx_error: b('rx_valid=1 且整體 XOR=1 時為 1。', 'High when rx_valid=1 and the total XOR is one.') },
    [b('tx_parity = ^tx_cmd，形成 even parity。', 'tx_parity = ^tx_cmd to form even parity.'), b('rx_error = rx_valid && ((^rx_cmd) ^ rx_parity)。', 'rx_error = rx_valid && ((^rx_cmd) ^ rx_parity).'), b('rx_valid=0 時即使輸入 X/錯誤也不得報 error。', 'When rx_valid=0, do not report an error even if inputs are invalid.')],
    [e('T0', "tx_cmd=16'h1234", "tx_cmd=16'h1234", 'tx_parity 使 17-bit XOR=0', 'tx_parity makes the 17-bit XOR zero'), e('T1', 'rx 複製 tx、rx_valid=1', 'rx copies tx, rx_valid=1', 'rx_error=0', 'rx_error=0'), e('T2', '翻轉 rx_cmd 任一 bit', 'Flip any one rx_cmd bit', 'rx_error=1', 'rx_error=1')],
    [], [b('Parity 保證偵測奇數個 bit error，不保證所有偶數個錯誤。', 'Parity detects any odd number of bit errors, not all even-numbered errors.')],
  ),
  'gddr-retry-queue': spec(
    b('保存一筆已送出但尚未 ACK 的 payload ownership。NACK 時重送保存值；ACK 前上游不能覆寫 entry。', 'Retain ownership of one payload that has been sent but not ACKed. Replay the stored value on NACK; upstream cannot overwrite the entry before ACK.'),
    syncClock,
    { ...resetPorts, in_valid: b('上游提供新 payload。', 'Upstream presents a new payload.'), in_data: b('新 8-bit 教學 payload。', 'New 8-bit educational payload.'), in_ready: b('entry 為空，可接受新 payload。', 'The entry is empty and may accept a new payload.'), ack: b('對目前 owned payload 的正確認可。', 'Positive acknowledgment for the owned payload.'), nack: b('要求重送目前 owned payload。', 'Requests replay of the owned payload.'), send: b('一拍 transmit/replay pulse。', 'One-cycle transmit/replay pulse.'), send_data: b('被擁有並送出的 payload；直到 ACK 不得改變。', 'Owned payload being transmitted; must not change before ACK.'), owned: b('entry valid/ownership 狀態。', 'Entry-valid/ownership state.') },
    [b('in_ready=!owned；in_valid&&in_ready 在 edge 擷取 in_data、owned=1、send=1。', 'in_ready=!owned; in_valid&&in_ready captures in_data, sets owned=1, and pulses send.'), b('owned&&ack 釋放 entry；owned&&nack 保持 entry 並 pulse send。', 'owned&&ack frees the entry; owned&&nack retains it and pulses send.'), b('沒有事件時 send 每拍預設回 0，send_data 保持。', 'Without an event, send defaults low each cycle and send_data holds.')],
    [e('C0', 'owned=0、in_valid=1、in_data=A5', 'owned=0, in_valid=1, in_data=A5', 'edge 後 owned=1、send=1、send_data=A5', 'owned=1, send=1, send_data=A5 after edge'), e('C1', '上游改 in_data=11', 'Upstream changes in_data=11', 'in_ready=0、send_data 仍 A5', 'in_ready=0, send_data remains A5'), e('C2', 'nack=1', 'nack=1', 'send=1 且仍送 A5', 'send=1 and data remains A5'), e('C3', 'ack=1', 'ack=1', 'owned=0、in_ready=1', 'owned=0, in_ready=1')],
    [b('新接受 > ACK > NACK；因 in_ready=!owned，新接受不會與 ACK 同拍利用剛釋放空間。', 'New acceptance > ACK > NACK; because in_ready=!owned, a same-cycle ACK does not provide fall-through acceptance.')],
  ),
  'gddr-controller-capstone': spec(
    b('形成 GDDR PHY 前的 atomic issue gate：retry 優先；新 transaction 只有在 timing、turnaround、ownership 與 PHY 資源全部可用時接受。', 'Form the atomic issue gate before the GDDR PHY: retry has priority; a new transaction is accepted only when timing, turnaround, ownership, and PHY resources all permit it.'),
    combinational,
    { new_valid: b('scheduler 提供新 transaction。', 'Scheduler presents a new transaction.'), timing_ok: b('DRAM bank/BG timing 合法。', 'DRAM bank/BG timing is legal.'), turnaround_ok: b('資料匯流排方向等待已完成。', 'Data-bus turnaround wait is complete.'), retry_owned: b('retry buffer 目前擁有舊 transaction。', 'Retry buffer currently owns an old transaction.'), retry_pending: b('舊 transaction 已被要求重送。', 'Replay has been requested for the old transaction.'), phy_ready: b('PHY datapath 本拍可接受資料。', 'PHY datapath can accept data this cycle.'), issue_retry: b('本拍向 PHY 重送 owned transaction。', 'Replay the owned transaction to the PHY this cycle.'), new_accept: b('本拍原子接受並發出新 transaction。', 'Atomically accept and issue a new transaction this cycle.') },
    [b('issue_retry = retry_owned && retry_pending && phy_ready。', 'issue_retry = retry_owned && retry_pending && phy_ready.'), b('new_accept = new_valid && timing_ok && turnaround_ok && !retry_owned && !retry_pending && phy_ready。', 'new_accept = new_valid && timing_ok && turnaround_ok && !retry_owned && !retry_pending && phy_ready.'), b('issue_retry 與 new_accept 永遠互斥。', 'issue_retry and new_accept are always mutually exclusive.')],
    [e('T0', 'new_valid=1、所有 guard=1、沒有 retry', 'new_valid=1, all guards=1, no retry', 'new_accept=1、issue_retry=0', 'new_accept=1, issue_retry=0'), e('T1', 'retry_owned=1、retry_pending=1、phy_ready=1', 'retry_owned=1, retry_pending=1, phy_ready=1', 'issue_retry=1、new_accept=0', 'issue_retry=1, new_accept=0'), e('T2', 'phy_ready=0', 'phy_ready=0', '兩者皆 0', 'both outputs are 0')],
    [b('Retry 優先並排除新接受；所有 issue 最後都受 phy_ready gate。', 'Retry has priority and excludes new acceptance; every issue is finally gated by phy_ready.')],
  ),
  'pcie-credit-manager': spec(
    b('追蹤縮小版 PCIe header/data flow-control credits。只有兩種 credit 都足夠才 grant TLP；grant 消耗、FC update 補回。', 'Track reduced PCIe header/data flow-control credits. Grant a TLP only when both are sufficient; grants consume credits and FC updates replenish them.'),
    syncClock,
    { ...resetPorts, tx_valid: b('TX 有一筆待送 TLP。', 'TX has a TLP ready to send.'), tx_h_cost: b('該 TLP 要消耗的 header credits。', 'Header-credit cost of the TLP.'), tx_d_cost: b('該 TLP 要消耗的 data credits。', 'Data-credit cost of the TLP.'), fc_valid: b('本拍收到有效 flow-control update。', 'A valid flow-control update arrived this cycle.'), fc_h_add: b('update 增加的 header credits。', 'Header credits added by the update.'), fc_d_add: b('update 增加的 data credits。', 'Data credits added by the update.'), tx_grant: b('tx_valid 且兩種目前 credit 都足夠。', 'tx_valid and both current credit pools are sufficient.'), h_credit: b('目前 header-credit 計數。', 'Current header-credit count.'), d_credit: b('目前 data-credit 計數。', 'Current data-credit count.') },
    [b('Reset h_credit=4、d_credit=16。', 'Reset h_credit=4 and d_credit=16.'), b('tx_grant = tx_valid && h_credit>=tx_h_cost && d_credit>=tx_d_cost；不足時兩個 pool 都不能扣。', 'tx_grant requires both pools to cover their costs; if either is short, neither pool is decremented.'), b('grant edge 扣成本；fc_valid edge 加 update。', 'Subtract costs on a grant edge and add updates on an fc_valid edge.')],
    [e('C0', 'h=4、d=16；tx cost h=2、d=8', 'h=4, d=16; tx cost h=2, d=8', 'tx_grant=1；edge 後 h=2、d=8', 'tx_grant=1; h=2, d=8 after edge'), e('C1', 'tx cost h=3、d=1', 'tx cost h=3, d=1', 'header 不足，tx_grant=0，兩計數不變', 'header shortage, tx_grant=0, both counts hold'), e('C2', 'fc_valid=1、add h=4、d=8', 'fc_valid=1, add h=4, d=8', 'edge 後 h=6、d=16', 'h=6, d=16 after edge')],
    [b('Reset 最高優先；grant 與 fc_valid 同拍時採 net update：old-cost+add，兩個事件都不能遺失。', 'Reset has highest priority; simultaneous grant and fc_valid use a net update, old-cost+add, preserving both events.')], [b('本題刻意縮成兩個 pool；正式 PCIe 需依 traffic class 與 posted/non-posted/completion 分類。', 'This lab reduces flow control to two pools; real PCIe separates traffic classes and posted/non-posted/completion credits.')],
  ),
  'pcie-tag-tracker': spec(
    b('用 8-bit bitmap 管理 non-posted request tag ownership。配置只允許 free tag；completion 釋放 owned tag，未知 completion 產生一拍 error。', 'Manage ownership of eight non-posted request tags with a bitmap. Allocate only a free tag; completions free owned tags, and unknown completions pulse an error.'),
    syncClock,
    { ...resetPorts, alloc_valid: b('requester 嘗試配置 alloc_tag。', 'Requester attempts to allocate alloc_tag.'), alloc_tag: b('欲配置的 3-bit tag index。', 'Three-bit tag index to allocate.'), alloc_ready: b('目前 outstanding[alloc_tag]==0，可接受配置。', 'Current outstanding[alloc_tag] is zero, so allocation may proceed.'), cpl_valid: b('completion parser 提供一筆完成。', 'Completion parser presents a completion.'), cpl_tag: b('完成所攜帶的 tag。', 'Tag carried by the completion.'), cpl_error: b('未知/重複 completion 的一拍 pulse。', 'One-cycle pulse for an unknown/duplicate completion.'), outstanding: b('每個 tag 的 ownership bitmap；1=已配置未完成。', 'Ownership bitmap; one means allocated and incomplete.') },
    [b('alloc_ready=!outstanding[alloc_tag]。alloc_valid&&alloc_ready 在 edge 將該 bit 設 1。', 'alloc_ready=!outstanding[alloc_tag]. Allocation sets that bit on the edge.'), b('cpl_valid 且 bit=1 時清除；bit=0 時不改 bitmap 並 pulse cpl_error。', 'A completion clears an owned bit; an unowned tag leaves the bitmap unchanged and pulses cpl_error.'), b('cpl_error 每個正常週期先清 0，因此只維持一拍。', 'cpl_error defaults low each normal cycle and lasts one cycle.')],
    [e('C0', 'alloc_valid=1、alloc_tag=3、bit3=0', 'alloc_valid=1, alloc_tag=3, bit3=0', 'alloc_ready=1；edge 後 outstanding[3]=1', 'alloc_ready=1; outstanding[3]=1 after edge'), e('C1', '再次 alloc tag3', 'Allocate tag3 again', 'alloc_ready=0，不改狀態', 'alloc_ready=0, state holds'), e('C2', 'cpl_valid=1、cpl_tag=3', 'cpl_valid=1, cpl_tag=3', 'edge 後 bit3=0、cpl_error=0', 'bit3=0, cpl_error=0 after edge'), e('C3', '再次 completion tag3', 'Complete tag3 again', 'cpl_error=1 一拍', 'cpl_error pulses for one cycle')],
    [b('本題允許 allocation 與 completion 在同拍輸入；若同 tag，程式中後面的 completion assignment 決定 bitmap，產品需寫 assertion 固化語意。', 'Allocation and completion may coincide; for the same tag, the later completion assignment determines the bitmap, so a product needs an assertion defining this semantic.')],
  ),
  'pcie-replay-timer': spec(
    b('對一筆需要 ACK 的 Data Link packet 啟動 timeout。ACK 清除 outstanding；超時 pulse replay_request 並重新計時，但 transaction 仍 outstanding。', 'Run a timeout for one Data Link packet requiring ACK. ACK clears outstanding; timeout pulses replay_request and restarts timing while the transaction remains outstanding.'),
    syncClock,
    { ...resetPorts, sent: b('本拍送出一筆新的、需要 ACK 的 packet；只有無 outstanding 時接受。', 'A new ACK-requiring packet was sent; accepted only when none is outstanding.'), ack: b('目前 outstanding packet 的 ACK。', 'ACK for the current outstanding packet.'), outstanding: b('是否有等待 ACK 的 packet。', 'Whether a packet is awaiting ACK.'), replay_request: b('timeout 時的一拍重送請求。', 'One-cycle replay request on timeout.') },
    [b('ack 最高優先：清 outstanding 與 timer。', 'ACK has highest priority and clears outstanding and timer.'), b('若 sent&&!outstanding，建立 outstanding 並將 timer=0。', 'If sent&&!outstanding, create outstanding and set timer=0.'), b('outstanding 時每拍計數；timer>=TIMEOUT-1 時 pulse replay_request 並將 timer=0。', 'While outstanding, count each cycle; at timer>=TIMEOUT-1, pulse replay_request and reset timer.'), b('replay_request 每拍預設 0。', 'replay_request defaults low every cycle.')],
    [e('C0', 'sent=1、無 outstanding', 'sent=1 with no outstanding', 'edge 後 outstanding=1、timer=0', 'outstanding=1, timer=0 after edge'), e('C1–C3', '沒有 ACK、TIMEOUT=4', 'No ACK, TIMEOUT=4', 'timer 累加，replay_request=0', 'timer increments, replay_request=0'), e('C4', '仍無 ACK', 'Still no ACK', 'replay_request=1 一拍、timer 重設、outstanding 保持 1', 'replay_request pulses, timer resets, outstanding remains 1'), e('任意', 'ack=1', 'ack=1', '優先清除，不產生 replay', 'clear with priority; no replay')],
    [b('Reset > ACK > new sent > timeout/count。', 'Reset > ACK > new sent > timeout/count.')],
  ),
  'controller-tag-completion': spec(
    b('建立 end-to-end exactly-once checker：每個 accepted tag 必須只 outstanding 一次，且只能被完成一次；任何重複/未知事件鎖住 sticky_error。', 'Build an end-to-end exactly-once checker: each accepted tag may be outstanding once and completed once; duplicate or unknown events latch sticky_error.'),
    syncClock,
    { ...resetPorts, accept: b('controller 接受一筆新 transaction。', 'Controller accepts a new transaction.'), accept_tag: b('新 transaction 的 3-bit identity。', 'Three-bit identity of the new transaction.'), complete: b('controller 對上游回報完成。', 'Controller reports a completion upstream.'), complete_tag: b('完成對應的 identity。', 'Identity carried by the completion.'), sticky_error: b('重複 accept 或未知/重複 complete 後保持 1，直到 reset。', 'Latches after duplicate accept or unknown/duplicate complete until reset.'), outstanding: b('8-entry transaction ownership bitmap。', 'Eight-entry transaction-ownership bitmap.') },
    [b('accept：若 bit=0 則設 1；若已為 1，bitmap 保持且 sticky_error=1。', 'On accept, set a free bit; if already set, hold the bitmap and latch sticky_error.'), b('complete：若 bit=1 則清 0；若為 0，sticky_error=1。', 'On complete, clear an owned bit; if clear, latch sticky_error.'), b('沒有錯誤時 sticky_error 不自動清除。', 'sticky_error never auto-clears.')],
    [e('C0', 'accept tag2', 'accept tag2', 'outstanding[2]=1、error=0', 'outstanding[2]=1, error=0'), e('C1', 'complete tag2', 'complete tag2', 'outstanding[2]=0、error=0', 'outstanding[2]=0, error=0'), e('C2', '再次 complete tag2', 'complete tag2 again', 'sticky_error=1 並保持', 'sticky_error=1 and remains high')],
    [b('本題明定 accept/complete 都檢查 edge 前的舊 bitmap：free tag 同拍 accept+complete 會保留新 ownership 並報 unknown-completion error；owned tag 同拍事件會報 duplicate-accept 並由 complete 清除。', 'Both events inspect the pre-edge bitmap: simultaneous accept+complete on a free tag keeps the new ownership and reports unknown completion; on an owned tag it reports duplicate accept and completion clears ownership.')],
  ),
  'pcie-tlp-router': spec(
    b('解碼縮小版 PCIe TLP type 與 data-format，將有效 packet 唯一分流為 posted、non-posted、completion；不合法組合只能標 malformed。', 'Decode a reduced PCIe TLP type and data format, routing a valid packet exclusively to posted, non-posted, or completion; illegal combinations must route only to malformed.'),
    combinational,
    { valid: b('目前 header 有效；為 0 時所有分類輸出為 0。', 'Current header is valid; when low, every class output is zero.'), tlp_type: b('教學 type：0=MRd、1=MWr、2=Cpl、其他保留。', 'Teaching type: 0=MRd, 1=MWr, 2=Cpl, others reserved.'), has_data: b('TLP 是否攜帶 data payload。', 'Whether the TLP carries a data payload.'), posted: b('合法 MWr 分流 pulse。', 'Route pulse for a legal MWr.'), nonposted: b('合法 MRd 分流 pulse。', 'Route pulse for a legal MRd.'), completion: b('Cpl 分流 pulse。', 'Route pulse for a Cpl.'), malformed: b('未知 type 或 type/data 組合不合法。', 'Unknown type or illegal type/data combination.') },
    [b('先將四個輸出預設為 0；valid=0 時停止。', 'Default all four outputs to zero and stop when valid=0.'), b('type0 MRd 只有 has_data=0 才 nonposted；type1 MWr 只有 has_data=1 才 posted。', 'Type-0 MRd is non-posted only without data; type-1 MWr is posted only with data.'), b('type2 一律 completion；其他 type malformed。任何 valid TLP 恰有一個分類輸出。', 'Type 2 is completion; all other types are malformed. Every valid TLP asserts exactly one class output.')],
    [e('T0', 'valid=1、type=0、has_data=0', 'valid=1, type=0, has_data=0', 'nonposted=1', 'nonposted=1'), e('T1', 'valid=1、type=1、has_data=0', 'valid=1, type=1, has_data=0', 'malformed=1，不可 posted', 'malformed=1, not posted'), e('T2', 'valid=1、type=2', 'valid=1, type=2', 'completion=1', 'completion=1')],
    [b('Malformed detection 優先於正常 route；四個輸出必須 one-hot-or-zero。', 'Malformed detection overrides normal routing; the four outputs must be one-hot-or-zero.')], [b('這是縮小 type 表，不是完整 PCIe Base Specification header decoder。', 'This reduced type table is not a full PCIe Base Specification header decoder.')],
  ),
  'pcie-replay-buffer': spec(
    b('實作 depth-2 DLL replay FIFO，保存尚未 ACK 的 sequence/payload。ACK 只移除匹配 head 的項目；replay_req 讀出目前 head，不改 FIFO。', 'Implement a depth-two DLL replay FIFO retaining unacknowledged sequence/payload pairs. ACK removes only a matching head; replay_req exposes the head without modifying the FIFO.'),
    syncClock,
    { ...resetPorts, push: b('送出新 packet 時要求保存。', 'Requests storage of a newly transmitted packet.'), push_seq: b('新 packet 的 3-bit DLL sequence。', 'Three-bit DLL sequence of the new packet.'), push_data: b('縮小的 8-bit packet payload。', 'Reduced 8-bit packet payload.'), push_ready: b('count<2，FIFO 有空位。', 'count<2; FIFO has space.'), ack: b('收到 cumulative/head ACK 事件。', 'A cumulative/head ACK event arrived.'), ack_seq: b('ACK 所指 sequence；必須等於 head 才 pop。', 'Sequence named by ACK; must equal head to pop.'), replay_req: b('要求讀出目前 head 進行重送。', 'Requests the current head for replay.'), replay_valid: b('replay_req 且 FIFO 非空。', 'replay_req and FIFO nonempty.'), replay_seq: b('目前 head sequence。', 'Current head sequence.'), replay_data: b('目前 head payload。', 'Current head payload.'), count: b('有效 entry 數，範圍 0–2。', 'Valid-entry count, 0–2.') },
    [b('put=push&&push_ready；pop=ack&&count!=0&&ack_seq==head_seq。錯誤 ACK 忽略。', 'put=push&&push_ready; pop=ack&&count!=0&&ack_seq==head_seq. Ignore a wrong ACK.'), b('只 put：寫 tail、count+1；只 pop：entry1 shift 到 entry0、count-1。', 'Put only: write tail and increment count. Pop only: shift entry1 to entry0 and decrement count.'), b('count=1 時 put+pop 可同拍交換 head 且 count 保持 1。count=2 時 push_ready=0，因此即使同拍 ACK 也不接受新 push。', 'At count=1, simultaneous put+pop replaces the head and holds count=1. At count=2, push_ready=0, so a same-cycle ACK does not accept a new push.'), b('replay 輸出純讀取，不 pop、不改 count。', 'Replay output is read-only and neither pops nor changes count.')],
    [e('C0', 'push seq1/dataAA', 'push seq1/dataAA', 'count=1、head=1/AA', 'count=1, head=1/AA'), e('C1', 'push seq2/dataBB', 'push seq2/dataBB', 'count=2、push_ready=0', 'count=2, push_ready=0'), e('C2', 'replay_req=1', 'replay_req=1', 'replay_valid=1、輸出 1/AA，count 不變', 'replay_valid=1, output 1/AA, count unchanged'), e('C3', 'ack=1、ack_seq=1', 'ack=1, ack_seq=1', 'head 變 2/BB、count=1', 'head becomes 2/BB, count=1')],
    [b('Reset > 同拍 put/pop case；只有 head-matching ACK 可 pop。', 'Reset > simultaneous put/pop case; only a head-matching ACK may pop.')],
  ),
  'pcie-completion-reorder': spec(
    b('保存兩筆依 issue 排序的 tag；completion 可依 tag 亂序寫入 done/data，但 retire 只能從最老 head 依序送回上游。', 'Store two tags in issue order. Completions may fill done/data out of order by tag, but retirement returns only the oldest completed head upstream.'),
    syncClock,
    { ...resetPorts, issue: b('接受一筆新 non-posted request identity；僅 count<2 有效。', 'Accepts a new non-posted request identity only when count<2.'), issue_tag: b('新 request 的 3-bit tag。', 'Three-bit tag of the new request.'), cpl: b('本拍收到 completion。', 'A completion arrived this cycle.'), cpl_tag: b('completion tag，用於兩筆 CAM 比對。', 'Completion tag used for two-entry CAM matching.'), cpl_data: b('縮小的 completion payload。', 'Reduced completion payload.'), retire_ready: b('上游可接受 head completion。', 'Upstream can accept the head completion.'), retire_valid: b('FIFO 非空且 head done。', 'FIFO nonempty and head is done.'), retire_data: b('head completion data；retire_valid=1 時有效。', 'Head completion data, valid while retire_valid=1.'), count: b('已 issue 且未 retire 的 entry 數，0–2。', 'Number of issued but unretired entries, 0–2.') },
    [b('issue 依序填 entry0、entry1，並將新 entry done=0。', 'Issue fills entry0 then entry1 and clears the new entry’s done bit.'), b('cpl 以 tag 比對有效 entries；匹配者寫 data 並設 done=1，不改順序。', 'Completion matches valid entries by tag, writes data, and sets done without changing order.'), b('retire = retire_valid&&retire_ready；retire 時 entry1 shift 到 head、count-1。', 'retire = retire_valid&&retire_ready; retirement shifts entry1 to head and decrements count.'), b('後面的 entry 即使先 done，也必須等 head retire。', 'A younger completed entry must wait until the head retires.')],
    [e('C0–C1', '依序 issue tag1、tag2', 'Issue tag1 then tag2', 'count=2、head=tag1', 'count=2, head=tag1'), e('C2', '先收到 cpl tag2/dataB2', 'Receive cpl tag2/dataB2 first', 'entry1 done，但 retire_valid=0', 'entry1 done, but retire_valid=0'), e('C3', '收到 cpl tag1/dataA1', 'Receive cpl tag1/dataA1', 'retire_valid=1、retire_data=A1', 'retire_valid=1, retire_data=A1'), e('C4', 'retire_ready=1', 'retire_ready=1', 'tag1 retire；head 變 tag2，立即可 retire B2', 'tag1 retires; tag2 becomes head and B2 is ready')],
    [b('Completion fill 使用 tag；retirement 永遠只使用 issue-order head。', 'Completion fill uses tags; retirement always uses the issue-order head.')], [b('本題不處理 unknown tag error、split completion 或同拍複雜 bypass；產品需擴充。', 'This lab omits unknown-tag errors, split completions, and complex same-cycle bypass; products must extend it.')],
  ),
  'pcie-ltssm-recovery': spec(
    b('建立縮小的 PCIe link lifecycle：DETECT→POLL→L0→RECOVERY。link_up 只在 L0，讓上層 traffic 在 training/recovery 期間被關閉。', 'Build a reduced PCIe link lifecycle: DETECT→POLL→L0→RECOVERY. link_up is high only in L0, gating upper-layer traffic during training/recovery.'),
    syncClock,
    { ...resetPorts, receiver_detect: b('PIPE/PHY 回報偵測到 receiver。', 'PIPE/PHY reports receiver detected.'), training_done: b('Polling/training 成功。', 'Polling/training completed successfully.'), link_error: b('L0 中偵測需進 Recovery 的錯誤。', 'Error in L0 requiring Recovery.'), recovery_ok: b('Recovery training 成功，可回 L0。', 'Recovery training succeeded; return to L0.'), recovery_fail: b('Recovery 失敗，回 Detect 重建鏈路。', 'Recovery failed; return to Detect.'), link_up: b('state==L0 的組合狀態；上層 admission gate。', 'Combinational state==L0 status and upper-layer admission gate.'), state: b('0=DETECT、1=POLL、2=L0、3=RECOVERY。', '0=DETECT, 1=POLL, 2=L0, 3=RECOVERY.') },
    [b('Reset→DETECT。DETECT 只在 receiver_detect 進 POLL。', 'Reset→DETECT. receiver_detect moves DETECT to POLL.'), b('POLL 只在 training_done 進 L0；L0 只在 link_error 進 RECOVERY。', 'training_done moves POLL to L0; link_error moves L0 to RECOVERY.'), b('RECOVERY：recovery_ok 回 L0；否則 recovery_fail 回 DETECT；都沒有則停留。', 'RECOVERY: recovery_ok returns to L0; otherwise recovery_fail returns to DETECT; otherwise hold.'), b('link_up 直接 decode state，不另存 flag。', 'Decode link_up directly from state; do not store a second flag.')],
    [e('C0', 'DETECT、receiver_detect=1', 'DETECT, receiver_detect=1', 'edge 後 POLL、link_up=0', 'POLL after edge, link_up=0'), e('C1', 'POLL、training_done=1', 'POLL, training_done=1', 'edge 後 L0、link_up=1', 'L0 after edge, link_up=1'), e('C2', 'L0、link_error=1', 'L0, link_error=1', 'edge 後 RECOVERY、link_up=0', 'RECOVERY after edge, link_up=0'), e('C3', 'recovery_fail=1', 'recovery_fail=1', 'edge 後 DETECT', 'DETECT after edge')],
    [b('RECOVERY 中 recovery_ok 優先於 recovery_fail。', 'In RECOVERY, recovery_ok has priority over recovery_fail.')], [b('完整 LTSSM 有更多狀態與 timeout；此題只教上層 traffic gate 與 recovery ownership。', 'A complete LTSSM has many more states and timers; this lab teaches upper-layer gating and recovery ownership.')],
  ),
  'pcie-controller-capstone': spec(
    b('在 PCIe requester 入口做一次 atomic resource commit：只有 link、credit、tag、replay buffer 四項都可用，才能接受 non-posted request，並同拍配置 tag、消耗 credit。', 'Perform an atomic resource commit at the PCIe requester ingress. Accept a non-posted request only when link, credit, tag, and replay space are all available, allocating the tag and consuming credit on the same event.'),
    combinational,
    { req_valid: b('上游提出一筆 non-posted transaction。', 'Upstream presents a non-posted transaction.'), link_up: b('LTSSM 位於 L0，可接受上層 traffic。', 'LTSSM is in L0 and permits upper-layer traffic.'), credit_ok: b('所需 header/data credit 都足夠。', 'All required header/data credits are available.'), tag_free: b('allocator 有可用 tag。', 'Allocator has a free tag.'), replay_space: b('DLL replay buffer 可保存新 packet。', 'DLL replay buffer has space for the new packet.'), req_ready: b('四項資源的組合 AND；與 req_valid 無關。', 'Combinational AND of all four resources; independent of req_valid.'), accept: b('req_valid&&req_ready；唯一 transaction commit event。', 'req_valid&&req_ready; the sole transaction-commit event.'), allocate_tag: b('必須與 accept 完全相同。', 'Must be exactly identical to accept.'), consume_credit: b('必須與 accept 完全相同。', 'Must be exactly identical to accept.') },
    [b('req_ready = link_up && credit_ok && tag_free && replay_space。', 'req_ready = link_up && credit_ok && tag_free && replay_space.'), b('accept = req_valid && req_ready。', 'accept = req_valid && req_ready.'), b('allocate_tag = accept；consume_credit = accept。不能先占一半資源再等待另一半。', 'allocate_tag = accept and consume_credit = accept. Never reserve only part of the resources while waiting for the rest.')],
    [e('T0', '四項資源=1、req_valid=1', 'All four resources=1, req_valid=1', 'req_ready=1、accept/allocate/consume=1', 'req_ready=1, accept/allocate/consume=1'), e('T1', 'tag_free=0', 'tag_free=0', 'req_ready=0，三個 commit 輸出=0', 'req_ready=0 and all commit outputs=0'), e('T2', '四項資源=1、req_valid=0', 'All resources=1, req_valid=0', 'req_ready=1，但 accept/allocate/consume=0', 'req_ready=1, but accept/allocate/consume=0')],
    [b('所有資源是同一 atomic accept 的平等前置條件；任一缺少皆不得產生 side effect。', 'All resources are equal prerequisites of one atomic accept; a missing resource forbids every side effect.')],
  ),
};

export function parseModulePorts(source: string): PortInfo[] {
  const start = source.search(/\bmodule\b/);
  const end = source.indexOf(');', start);
  if (start < 0 || end < 0) return [];
  const header = source.slice(start, end + 2);
  const ports: PortInfo[] = [];
  const pattern = /\b(input|output|inout)\s+(?:(?:wire|reg|logic)\s*)?(?:\[([^\]]+)\]\s*)?([A-Za-z_]\w*)/g;
  for (const match of header.matchAll(pattern)) {
    ports.push({ name: match[3], direction: match[1], width: match[2] ? `[${match[2].replaceAll(/\s+/g, '')}]` : '1' });
  }
  return ports;
}

const hbmReference = (clause: string, topicsZh: string, topicsEn: string): LabReference => ({
  source: b(`JEDEC JESD270-4A，${clause}`, `JEDEC JESD270-4A, ${clause}`),
  topics: b(topicsZh, topicsEn),
  profile: b('題目採縮小且獨立撰寫的 executable profile；產品數值與完整命令編碼必須回查合法取得的規格與 vendor speed-bin。', 'The lab uses a reduced, independently authored executable profile; product values and complete encodings must come from the licensed standard and vendor speed bin.'),
});

export const labReferences: Record<string, LabReference> = {
  ...hbm4AdvancedReferences,
  'hbm-pseudo-channel-map': hbmReference('§3.1–3.2', 'Channel、pseudo-channel、addressing 與 bank-group organization', 'Channel, pseudo-channel, addressing, and bank-group organization'),
  'hbm-bankgroup-tccd': hbmReference('§3.2.1、§6.3.3、§10', 'Bank-group 對 tCCD_S/L/R 的影響', 'Bank-group effects on tCCD_S/L/R'),
  'hbm-hierarchical-arbiter': hbmReference('§3.1–3.2', '從 channel/PC/bank 組織推導的 controller hierarchy', 'Controller hierarchy derived from channel/PC/bank organization'),
  'hbm-refresh-domain': hbmReference('§3.1.2、§6.3.2.5', 'Per-pseudo-channel refresh timing 與 shared command constraints', 'Per-pseudo-channel refresh timing and shared-command constraints'),
  'hbm-channel-capstone': hbmReference('§3、§6.3、§10', 'HBM channel-level command legality、timing 與 scheduling integration', 'HBM channel-level command legality, timing, and scheduling integration'),
};
